In [1]:
import pandas as pd
import numpy as np
import random
import pyomo.environ as pyo
from pyomo.environ import *
from pyomo.environ import SolverFactory
import yfinance as yf
from pathlib import Path
import os
import matplotlib.pyplot as plt

In [128]:
anos = ['2025-12-31',
 '2024-12-31',
 '2023-12-31',
 '2022-12-31',
 '2021-12-31',
 '2020-12-31',
 '2019-12-31',
 '2018-12-31',
 '2017-12-31',
 '2016-12-31',
 '2015-12-31',
 ]

In [3]:
lista_macro = []

for filename in os.listdir(path='../../base_dados/brapi/macro'):
    
    # 2. Reconstruct the full absolute or relative path to the file
    full_path = os.path.join('../../base_dados/brapi/macro/',filename)
    
    # 3. Check if the current item is actually a file (and not a subfolder)
    # if os.path.isfile(full_path):
        
    #     # 4. Open and process the file safely
    #     with open(full_path, "r", encoding="utf-8") as file:
    #         content = file.read()
    #         print(f"--- Content of {filename} ---")
    #         print(pd.read_csv(full_path))
    dicio = {
        'macro':filename,
        'data':pd.read_csv(full_path)
    }

    lista_macro.append(dicio)

In [4]:
lista_macro[0]['data'].set_index('date', inplace=True)

In [5]:
lista_macro[0]['data'].describe().loc['std']['valor_anual']

4.231617229847328

In [6]:
selic_d = lista_macro[0]['data']

In [7]:
basedados_ativos = Path('../../base_dados/retornos_ativos_2015_2026.csv') 
basedados_ibov = Path('../../base_dados/retorno_ibov_2015_2026.csv') 

lista_magic_formula = []

for filename in os.listdir(path='../../base_dados/brapi/magic_formula/'):
    
    # 2. Reconstruct the full absolute or relative path to the file
    full_path = os.path.join('../../base_dados/brapi/magic_formula/', filename)
    
    # 3. Check if the current item is actually a file (and not a subfolder)
    # if os.path.isfile(full_path):
        
    #     # 4. Open and process the file safely
    #     with open(full_path, "r", encoding="utf-8") as file:
    #         content = file.read()
    #         print(f"--- Content of {filename} ---")
    #         print(pd.read_csv(full_path))
    dicio = {
        'ativo':filename,
        'data':pd.read_csv(full_path)
    }

    lista_magic_formula.append(dicio)

df_ativos=pd.read_csv(basedados_ativos).set_index(['Date']).fillna(0)

df_ibov=pd.read_csv(basedados_ibov).set_index(['Date']).fillna(0)

In [8]:
lista_ativos=[]
for ativo in df_ativos.columns.tolist():
    lista_ativos.append(ativo.replace('.SA',''))
    df_ativos.rename(columns={ativo:ativo.replace('.SA','')},inplace=True)

In [9]:
df_ativos.shape[0]

2857

In [10]:
print(f'tamanho mf original: ',len(lista_magic_formula))
lista_mf_check = []
lista_ativos_finais = []
for i in range(len(lista_magic_formula)):
    if lista_magic_formula[i]['ativo'] in lista_ativos:
        lista_ativos_finais.append(lista_magic_formula[i]['ativo'])
        dc = {
            'ativo':lista_magic_formula[i]['ativo'],
            'data':lista_magic_formula[i]['data']
        }
        lista_mf_check.append(dc)
    else:
        print(f"Nao está na lista: {lista_magic_formula[i]['ativo']}")
print(f'tamanho mf Final: ',len(lista_mf_check))

tamanho mf original:  69
tamanho mf Final:  69

In [11]:
lista_mf_check

[{'ativo': 'ABEV3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.903659  0.111531
  1            1  2024-12-31  0.624135  0.141094
  2            2  2023-12-31  0.840339  0.101218
  3            3  2022-12-31  0.646090  0.093623
  4            4  2021-12-31  0.585286  0.089962
  5            5  2020-12-31  0.598088  0.085787
  6            6  2019-12-31  0.637351  0.073615
  7            7  2018-12-31  0.824850  0.092799
  8            8  2017-12-31  1.105830  0.069359
  9            9  2016-12-31  1.198593  0.096538
  10          10  2015-12-31  1.084847  0.104877
  11          11  2014-12-31  1.081966  0.102054
  12          12  2013-12-31  0.892491  0.099119
  13          13  2012-12-31  0.762046  0.000204},
 {'ativo': 'ALOS3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.719754  0.069923
  1            1  2024-12-31  0.690710  0.089326
  2            2  2023-12-31  3.051214  0.259800
  3            3  2022-12-31  0.206836       inf
  4            4  2021-12-31  0.456978       inf
  5            5  2020-12-31  0.220283       inf
  6            6  2019-12-31  0.193321       inf
  7            7  2018-12-31  6.024537       inf
  8            8  2017-12-31  1.949780       inf
  9            9  2016-12-31  4.287691       inf
  10          10  2015-12-31  3.291680       inf
  11          11  2014-12-31  1.977544       inf
  12          12  2013-12-31  2.104842       inf
  13          13  2012-12-31  0.897487       inf},
 {'ativo': 'AXIA3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.064941  0.014983
  1            1  2024-12-31  0.319325  0.122528
  2            2  2023-12-31  0.242834  0.068578
  3            3  2022-12-31  0.133297  0.039493
  4            4  2021-12-31  0.265099  0.107879
  5            5  2020-12-31  0.167610  0.074150
  6            6  2019-12-31  0.174593  0.071820
  7            7  2018-12-31  0.428382  0.151772
  8            8  2017-12-31  0.160349  0.044873
  9            9  2016-12-31  0.719660  0.155647
  10          10  2015-12-31 -0.406177 -0.154538
  11          11  2014-12-31 -0.046108 -0.026978
  12          12  2013-12-31 -0.119544 -0.106080
  13          13  2012-12-31 -0.130519 -0.113419},
 {'ativo': 'AZZA3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.215762  0.128598
  1            1  2024-12-31  0.082977  0.041399
  2            2  2023-12-31  0.369151  0.079842
  3            3  2022-12-31  0.382122  0.072475
  4            4  2021-12-31  0.881259  0.062808
  5            5  2020-12-31  0.094982  0.367190
  6            6  2019-12-31  0.272046  0.046478
  7            7  2018-12-31  0.285784  0.050134
  8            8  2017-12-31  0.306746  0.046652
  9            9  2016-12-31  0.262059  0.102043
  10          10  2015-12-31  0.261149  0.116814
  11          11  2014-12-31  0.287171  0.098323
  12          12  2013-12-31  0.310794  0.090454
  13          13  2012-12-31  0.286662  0.059698},
 {'ativo': 'B3SA3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.713721  0.060542
  1            1  2024-12-31  0.878188  0.074786
  2            2  2023-12-31  0.694163  0.050049
  3            3  2022-12-31  0.637924  0.076321
  4            4  2021-12-31  0.699233  0.104680
  5            5  2020-12-31  0.680557  0.056322
  6            6  2019-12-31  1.041395  0.142838
  7            7  2018-12-31  1.019145  0.146111
  8            8  2017-12-31  0.936325  0.096421
  9            9  2016-12-31  0.130038  0.188709
  10          10  2015-12-31  0.326941  0.988273
  11          11  2014-12-31  1.094273  0.233499
  12          12  2013-12-31  0.741219  0.348422
  13          13  2012-12-31  0.648707  0.265084},
 {'ativo': 'BBAS3',
  'data':     Unnamed: 0     endDate  ROC  EY
  0            0  2025-12-31  NaN NaN
  1            1  2024-12-31  NaN NaN
  2            2  2023-12-31  NaN NaN
  3            3  2022-12-31  NaN NaN
  4            4  2021-12-31  NaN NaN
  5            5  2020-12-31  NaN NaN
  6            6  2019-12-31  NaN NaN
  7            7  2018-12-31  NaN NaN
  8            8  2017-12-31  NaN NaN
  9            9  2016-12-31  NaN NaN
  10          10  2015-12-31  NaN NaN
  11          11  2014-12-31  NaN NaN
  12          12  2013-12-31  NaN NaN
  13          13  2012-12-31  NaN NaN},
 {'ativo': 'BBDC3',
  'data':     Unnamed: 0     endDate  ROC  EY
  0            0  2025-12-31  NaN NaN
  1            1  2024-12-31  NaN NaN
  2            2  2023-12-31  NaN NaN
  3            3  2022-12-31  NaN NaN
  4            4  2021-12-31  NaN NaN
  5            5  2020-12-31  NaN NaN
  6            6  2019-12-31  NaN NaN
  7            7  2018-12-31  NaN NaN
  8            8  2017-12-31  NaN NaN
  9            9  2016-12-31  NaN NaN
  10          10  2015-12-31  NaN NaN
  11          11  2014-12-31  NaN NaN
  12          12  2013-12-31  NaN NaN
  13          13  2012-12-31  NaN NaN},
 {'ativo': 'BBDC4',
  'data':     Unnamed: 0     endDate  ROC  EY
  0            0  2025-12-31  NaN NaN
  1            1  2024-12-31  NaN NaN
  2            2  2023-12-31  NaN NaN
  3            3  2022-12-31  NaN NaN
  4            4  2021-12-31  NaN NaN
  5            5  2020-12-31  NaN NaN
  6            6  2019-12-31  NaN NaN
  7            7  2018-12-31  NaN NaN
  8            8  2017-12-31  NaN NaN
  9            9  2016-12-31  NaN NaN
  10          10  2015-12-31  NaN NaN
  11          11  2014-12-31  NaN NaN
  12          12  2013-12-31  NaN NaN
  13          13  2012-12-31  NaN NaN},
 {'ativo': 'BBSE3',
  'data':     Unnamed: 0     endDate        ROC        EY
  0            0  2025-12-31   3.983830  0.166919
  1            1  2024-12-31   5.994063  0.177086
  2            2  2023-12-31  19.545107  0.176966
  3            3  2022-12-31   5.164468  0.086261
  4            4  2021-12-31   2.753881  0.125766
  5            5  2020-12-31   3.789294  0.080948
  6            6  2019-12-31  12.013021  0.171213
  7            7  2018-12-31   1.580919  0.099242
  8            8  2017-12-31   1.416078  0.108787
  9            9  2016-12-31  16.503715  0.098131
  10          10  2015-12-31 -20.061500  0.128590
  11          11  2014-12-31   1.271809  0.097588
  12          12  2013-12-31   1.403861  0.105026
  13          13  2012-12-31   0.000000       NaN},
 {'ativo': 'BEEF3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.240157  0.205351
  1            1  2024-12-31  0.145643  0.127028
  2            2  2023-12-31  0.145585  0.150818
  3            3  2022-12-31  0.240123  0.168552
  4            4  2021-12-31  0.183205  0.169824
  5            5  2020-12-31  0.199017  0.181278
  6            6  2019-12-31  0.233035  0.131980
  7            7  2018-12-31  0.117628  0.085907
  8            8  2017-12-31  0.143344  0.121648
  9            9  2016-12-31  0.176402  0.155370
  10          10  2015-12-31  0.226887  0.134997
  11          11  2014-12-31  0.144555  0.136146
  12          12  2013-12-31  0.163722  0.134071
  13          13  2012-12-31  0.169980  0.139286},
 {'ativo': 'BPAC11',
  'data':     Unnamed: 0     endDate  ROC  EY
  0            0  2025-12-31  NaN NaN
  1            1  2024-12-31  NaN NaN
  2            2  2023-12-31  NaN NaN
  3            3  2022-12-31  NaN NaN
  4            4  2021-12-31  NaN NaN
  5            5  2020-12-31  NaN NaN
  6            6  2019-12-31  NaN NaN
  7            7  2018-12-31  NaN NaN
  8            8  2017-12-31  NaN NaN
  9            9  2016-12-31  NaN NaN
  10          10  2015-12-31  NaN NaN
  11          11  2014-12-31  NaN NaN
  12          12  2013-12-31  NaN NaN
  13          13  2012-12-31  NaN NaN},
 {'ativo': 'BRAP4',
  'data':     Unnamed: 0     endDate        ROC        EY
  0            0  2025-12-31   2.162672  0.060438
  1            1  2024-12-31   4.723258  0.217542
  2            2  2023-12-31   9.610382  0.252545
  3            3  2022-12-31  55.274992  0.495016
  4            4  2021-12-31  32.760607  1.457539
  5            5  2020-12-31   3.841907  0.321432
  6            6  2019-12-31  -1.730019 -0.155033
  7            7  2018-12-31  11.545886  0.675647
  8            8  2017-12-31  -3.804793  1.342298
  9            9  2016-12-31   0.494947  0.637546
  10          10  2015-12-31  -7.205282 -1.492670
  11          11  2014-12-31  -0.216593  0.027943
  12          12  2013-12-31   0.018078  0.007128
  13          13  2012-12-31  -4.440988  0.189836},
 {'ativo': 'BRAV3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.115289  0.078124
  1            1  2024-12-31  0.134226  0.072084
  2            2  2023-12-31  0.186759  0.077443
  3            3  2022-12-31  0.093234  0.028632
  4            4  2021-12-31  0.134119  0.091781
  5            5  2020-12-31 -0.170792 -0.043180
  6            6  2019-12-31 -0.047091 -0.002175
  7            7  2018-12-31  0.152746       inf
  8            8  2017-12-31  0.126629       inf
  9            9  2016-12-31  0.057557       inf
  10          10  2015-12-31 -0.095170      -inf
  11          11  2014-12-31  0.042049       inf
  12          12  2013-12-31  0.058873       inf
  13          13  2012-12-31  0.022440       inf},
 {'ativo': 'BRKM5',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31 -0.057016 -0.029679
  1            1  2024-12-31 -0.020397 -0.014920
  2            2  2023-12-31 -0.050605 -0.043848
  3            3  2022-12-31  0.082173  0.067607
  4            4  2021-12-31  0.481351  0.275591
  5            5  2020-12-31 -0.001611 -0.001175
  6            6  2019-12-31 -0.001344 -0.000939
  7            7  2018-12-31  0.276543  0.154093
  8            8  2017-12-31  0.327055  0.185303
  9            9  2016-12-31  0.263859  0.142050
  10          10  2015-12-31  0.202776  0.139175
  11          11  2014-12-31  0.120259  0.101037
  12          12  2013-12-31  0.102175  0.081121
  13          13  2012-12-31  0.072533  0.062476},
 {'ativo': 'CMIG4',
  'data':     Unnamed: 0     endDate        ROC        EY
  0            0  2025-12-31   1.604456  0.120912
  1            1  2024-12-31   5.482017  0.207758
  2            2  2023-12-31   3.557296  0.188540
  3            3  2022-12-31   1.217974  0.150554
  4            4  2021-12-31   1.485031  0.165125
  5            5  2020-12-31   0.575826  0.101526
  6            6  2019-12-31   0.665097  0.064364
  7            7  2018-12-31   0.353323  0.060415
  8            8  2017-12-31   1.001925  0.091994
  9            9  2016-12-31   2.944315  0.059122
  10          10  2015-12-31  16.859418  0.163333
  11          11  2014-12-31   2.825974  0.173080
  12          12  2013-12-31   0.664545  0.187823
  13          13  2012-12-31   0.628747  0.110785},
 {'ativo': 'COGN3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.241949  0.078817
  1            1  2024-12-31  0.249333  0.134186
  2            2  2023-12-31  0.143974  0.042627
  3            3  2022-12-31  0.060067  0.020822
  4            4  2021-12-31  0.011072  0.005165
  5            5  2020-12-31 -0.387455 -0.153624
  6            6  2019-12-31  0.134106  0.030151
  7            7  2018-12-31  0.227030  0.054529
  8            8  2017-12-31  0.411082  0.067366
  9            9  2016-12-31  0.581904  0.097352
  10          10  2015-12-31  0.715407  0.101319
  11          11  2014-12-31  0.540251  0.047363
  12          12  2013-12-31  0.676364  0.213405
  13          13  2012-12-31  0.446927  0.117799},
 {'ativo': 'CPFE3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  1.362020  0.113894
  1            1  2024-12-31  1.212344  0.159409
  2            2  2023-12-31  1.255742  0.167953
  3            3  2022-12-31  0.937332  0.224368
  4            4  2021-12-31  0.650196  0.173718
  5            5  2020-12-31  0.623290  0.199395
  6            6  2019-12-31  0.503561  0.123973
  7            7  2018-12-31  0.387088  0.117210
  8            8  2017-12-31  0.417318  0.116727
  9            9  2016-12-31  0.234727  0.094231
  10          10  2015-12-31  0.203091  0.099585
  11          11  2014-12-31  0.243522  0.105820
  12          12  2013-12-31  0.247181  0.134955
  13          13  2012-12-31  0.275765  0.112416},
 {'ativo': 'CPLE3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.633406  0.082383
  1            1  2024-12-31  0.362358  0.095977
  2            2  2023-12-31  0.242567  0.087791
  3            3  2022-12-31  0.238252  0.081499
  4            4  2021-12-31  0.407867  0.177783
  5            5  2020-12-31  0.378119  0.152471
  6            6  2019-12-31  0.242533  0.213449
  7            7  2018-12-31  0.221192  0.164166
  8            8  2017-12-31  0.227290  0.162692
  9            9  2016-12-31  0.266116  0.182698
  10          10  2015-12-31  0.176132  0.209412
  11          11  2014-12-31  0.180619  0.206957
  12          12  2013-12-31  0.131622  0.205823
  13          13  2012-12-31  0.102899  0.235921},
 {'ativo': 'CSAN3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31 -0.003221 -0.001837
  1            1  2024-12-31  0.074639  0.039964
  2            2  2023-12-31  0.293982  0.132119
  3            3  2022-12-31  0.207619  0.084994
  4            4  2021-12-31  0.218889  0.105988
  5            5  2020-12-31  0.390649  0.051359
  6            6  2019-12-31  0.580379  0.200660
  7            7  2018-12-31  0.672507  0.178949
  8            8  2017-12-31  0.895553  0.187082
  9            9  2016-12-31  0.804935  0.208681
  10          10  2015-12-31  0.913121  0.139534
  11          11  2014-12-31  1.220118  0.109110
  12          12  2013-12-31  0.578900  0.084973
  13          13  2013-03-31  0.172102  0.085881},
 {'ativo': 'CSMG3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.819077  0.276762
  1            1  2024-12-31  0.807507  0.351270
  2            2  2023-12-31  0.778743  0.420532
  3            3  2022-12-31  0.630463  0.328156
  4            4  2021-12-31  0.398285  0.239091
  5            5  2020-12-31  0.599193  0.344388
  6            6  2019-12-31  0.498940  0.327504
  7            7  2018-12-31  0.420680  0.174097
  8            8  2017-12-31  0.431622  0.219424
  9            9  2016-12-31  1.093258  0.179977
  10          10  2015-12-31  0.531788  0.071964
  11          11  2014-12-31  1.632656  0.143535
  12          12  2013-12-31  1.834066  0.183586
  13          13  2012-12-31  1.306207  0.201944},
 {'ativo': 'CSNA3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.133148  0.075279
  1            1  2024-12-31  0.094689  0.071548
  2            2  2023-12-31  0.144124  0.086299
  3            3  2022-12-31  0.221442  0.159161
  4            4  2021-12-31  0.642640  0.506298
  5            5  2020-12-31  0.201378  0.103049
  6            6  2019-12-31  0.170229  0.084948
  7            7  2018-12-31  0.373014  0.193266
  8            8  2017-12-31  0.155607  0.083458
  9            9  2016-12-31  0.077558  0.053066
  10          10  2015-12-31  0.178682  0.166370
  11          11  2014-12-31  0.111841  0.078246
  12          12  2013-12-31  0.121159  0.078153
  13          13  2012-12-31  0.018270  0.021391},
 {'ativo': 'CXSE3',
  'data':     Unnamed: 0     endDate        ROC        EY
  0            0  2025-12-31   5.444059  0.100541
  1            1  2024-12-31   5.039275  0.115759
  2            2  2023-12-31  79.945533  0.128667
  3            3  2022-12-31   3.909279  0.186909
  4            4  2021-12-31   2.494263  0.128704
  5            5  2020-12-31   3.745947       inf
  6            6  2019-12-31   2.788075       inf
  7            7  2018-12-31   3.177800       inf
  8            8  2017-12-31   3.804848       inf
  9            9  2016-12-31   3.696039       inf
  10          10  2015-12-31  15.785824       inf},
 {'ativo': 'CYRE3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.197256  0.116742
  1            1  2024-12-31  0.232447  0.192066
  2            2  2023-12-31  0.174204  0.104270
  3            3  2022-12-31  0.163248  0.123254
  4            4  2021-12-31  0.192460  0.154920
  5            5  2020-12-31  0.547699  0.227092
  6            6  2019-12-31  0.181189  0.066582
  7            7  2018-12-31  0.012172  0.010715
  8            8  2017-12-31  0.003738  0.003739
  9            9  2016-12-31  0.041770  0.053711
  10          10  2015-12-31  0.121427  0.190958
  11          11  2014-12-31  0.201924  0.189694
  12          12  2013-12-31  0.202062  0.158204
  13          13  2012-12-31  0.163917  0.140426},
 {'ativo': 'CYRE4',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.197256  0.116742
  1            1  2024-12-31  0.232447  0.192066
  2            2  2023-12-31  0.174204  0.104270
  3            3  2022-12-31  0.163248  0.123254
  4            4  2021-12-31  0.192460  0.154920
  5            5  2020-12-31  0.547699  0.227092
  6            6  2019-12-31  0.181189  0.066582
  7            7  2018-12-31  0.012172  0.010715
  8            8  2017-12-31  0.003738  0.003739
  9            9  2016-12-31  0.041770  0.053711
  10          10  2015-12-31  0.121427  0.190958
  11          11  2014-12-31  0.201924  0.189694
  12          12  2013-12-31  0.202062  0.158204
  13          13  2012-12-31  0.163917  0.140426},
 {'ativo': 'DIRR3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.210397  0.068090
  1            1  2024-12-31  0.229911  0.121855
  2            2  2023-12-31  0.159399  0.098259
  3            3  2022-12-31  0.187800  0.097764
  4            4  2021-12-31  0.131322  0.099467
  5            5  2020-12-31  0.101366  0.075901
  6            6  2019-12-31  0.100591  0.070669
  7            7  2018-12-31 -0.019841 -0.013280
  8            8  2017-12-31 -0.077348 -0.069000
  9            9  2016-12-31  0.001613  0.001839
  10          10  2015-12-31  0.088083  0.116446
  11          11  2014-12-31  0.123577  0.181963
  12          12  2013-12-31  0.143568  0.231289
  13          13  2012-12-31  0.126376  0.208104},
 {'ativo': 'EGIE3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.213784  0.089344
  1            1  2024-12-31  0.305913  0.157808
  2            2  2023-12-31  0.328474  0.136922
  3            3  2022-12-31  0.369811  0.140094
  4            4  2021-12-31  0.286079  0.122964
  5            5  2020-12-31  0.311319  0.146089
  6            6  2019-12-31  0.266826  0.116007
  7            7  2018-12-31  0.244118  0.146390
  8            8  2017-12-31  0.292707  0.155509
  9            9  2016-12-31  0.206109  0.177127
  10          10  2015-12-31  0.220563       inf
  11          11  2014-12-31  0.209569       inf
  12          12  2013-12-31  0.242039       inf
  13          13  2012-12-31  0.255293       inf},
 {'ativo': 'EMBJ3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.131550  0.044257
  1            1  2024-12-31  0.147065  0.070264
  2            2  2023-12-31  0.074026  0.058137
  3            3  2022-12-31 -0.025033 -0.025837
  4            4  2021-12-31  0.039418  0.032374
  5            5  2020-12-31 -0.056388 -0.078682
  6            6  2019-12-31 -0.050025 -0.054437
  7            7  2018-12-31  0.004429  0.004767
  8            8  2017-12-31  0.050253  0.051051
  9            9  2016-12-31  0.038271  0.039518
  10          10  2015-12-31  0.052719  0.036603
  11          11  2014-12-31  0.092899  0.059820
  12          12  2013-12-31  0.140808  0.102018
  13          13  2012-12-31  0.138160  0.094822},
 {'ativo': 'ENEV3',
  'data':     Unnamed: 0     endDate       ROC        EY

In [12]:
df_ativos = df_ativos.filter(lista_ativos_finais)

In [134]:
#ativos
df_ativos_2015 = df_ativos[df_ativos.index.str.startswith('2015')]
df_ativos_2016 = df_ativos[df_ativos.index.str.startswith('2016')]
df_ativos_2017 = df_ativos[df_ativos.index.str.startswith('2017')]
df_ativos_2018 = df_ativos[df_ativos.index.str.startswith('2018')]
df_ativos_2019 = df_ativos[df_ativos.index.str.startswith('2019')]
df_ativos_2020 = df_ativos[df_ativos.index.str.startswith('2020')]
df_ativos_2021 = df_ativos[df_ativos.index.str.startswith('2021')]
df_ativos_2022 = df_ativos[df_ativos.index.str.startswith('2022')]
df_ativos_2023 = df_ativos[df_ativos.index.str.startswith('2023')]
df_ativos_2024 = df_ativos[df_ativos.index.str.startswith('2024')]
df_ativos_2025 = df_ativos[df_ativos.index.str.startswith('2025')]
df_ativos_2026 = df_ativos[df_ativos.index.str.startswith('2026')]

#ibov
df_ibov_2015 = df_ibov[df_ibov.index.str.startswith('2015')]
df_ibov_2016 = df_ibov[df_ibov.index.str.startswith('2016')]
df_ibov_2017 = df_ibov[df_ibov.index.str.startswith('2017')]
df_ibov_2018 = df_ibov[df_ibov.index.str.startswith('2018')]
df_ibov_2019 = df_ibov[df_ibov.index.str.startswith('2019')]
df_ibov_2020 = df_ibov[df_ibov.index.str.startswith('2020')]
df_ibov_2021 = df_ibov[df_ibov.index.str.startswith('2021')]
df_ibov_2022 = df_ibov[df_ibov.index.str.startswith('2022')]
df_ibov_2023 = df_ibov[df_ibov.index.str.startswith('2023')]
df_ibov_2024 = df_ibov[df_ibov.index.str.startswith('2024')]
df_ibov_2025 = df_ibov[df_ibov.index.str.startswith('2025')]
df_ibov_2026 = df_ibov[df_ibov.index.str.startswith('2026')]

In [14]:
selic_d_2016 = selic_d[selic_d.index.isin(df_ativos_2016.index)]
selic_d_2016['valor_diario'] = selic_d_2016['valor_diario']/100

C:\Users\joaon\AppData\Local\Temp\ipykernel_1420\111084625.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selic_d_2016['valor_diario'] = selic_d_2016['valor_diario']/100

In [15]:
df_ativos_2016

,ABEV3,ALOS3,AXIA3,AZZA3,B3SA3,BBAS3,BBDC3,BBDC4,BBSE3,BEEF3,...,SUZB3,TAEE11,TOTS3,UGPA3,USIM5,VALE3,VBBR3,VIVT3,WEGE3,YDUQ3
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-04,-0.035854,0.001236,-0.057292,-0.059524,-0.040404,-0.033922,-0.014634,-0.014523,-0.061652,-0.060150,...,0.0,-0.035821,-0.010957,-0.048801,-0.058064,-0.026094,0.0,-0.102649,-0.020736,-0.003584
2016-01-05,0.015689,0.000000,0.022100,0.007089,0.038277,0.003511,0.007792,0.003634,0.063951,0.035200,...,0.0,-0.015480,-0.004887,0.022956,-0.082192,-0.013396,0.0,0.001647,0.048498,-0.103597
2016-01-06,-0.009725,0.000617,-0.018018,-0.014580,-0.000922,0.000000,-0.017700,-0.014173,-0.007822,-0.014683,...,0.0,0.003145,0.024886,-0.007140,-0.089552,-0.073483,0.0,0.001645,-0.022802,0.085072
2016-01-07,-0.026574,-0.000617,-0.049541,0.031123,-0.041513,-0.023793,-0.032032,-0.020234,-0.039419,-0.050196,...,0.0,-0.033229,-0.026198,-0.040240,-0.057377,-0.059483,0.0,-0.000328,-0.028666,-0.005178
2016-01-08,0.013057,0.004938,-0.027027,0.013854,0.012512,0.000000,-0.002068,-0.019566,0.019006,-0.013212,...,0.0,0.042802,0.002296,0.016057,0.026087,-0.033914,0.0,-0.047963,-0.004805,-0.059479
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-12-23,0.011378,0.007647,0.015454,0.002057,0.028758,0.028462,0.023971,0.020935,0.005535,0.001688,...,0.0,-0.007264,0.000419,-0.001212,-0.002525,-0.007486,0.0,0.012324,0.026971,0.041892
2016-12-26,0.011250,0.015761,0.020591,-0.014374,0.008895,0.015707,0.020483,0.018309,0.002936,0.007582,...,0.0,-0.015610,0.002094,0.001517,0.012658,0.031759,0.0,0.007928,-0.008754,0.000000
2016-12-27,-0.004326,-0.010345,-0.017106,-0.000417,0.013854,0.006995,0.002509,-0.009709,-0.015368,0.010869,...,0.0,0.005946,0.001671,0.005455,0.025000,-0.005002,0.0,-0.001405,0.016305,-0.004539
2016-12-28,0.007449,-0.011614,0.014726,0.037516,0.024844,0.012432,0.023239,0.035947,0.040134,-0.007444,...,0.0,0.012315,0.007092,0.013261,-0.007317,0.031709,0.0,-0.003657,0.002673,0.005212
2016-12-29,0.010475,0.012338,0.003078,0.006830,0.000000,0.014445,0.018169,0.016474,0.011075,0.012500,...,0.0,0.009246,-0.004142,0.017995,0.007371,-0.037481,0.0,0.027668,0.033333,0.023979

## EXCESSO DOS ANOS e SIGMA (MAtriz de covariancia)

##### EXCESSO PARA TODOS

In [ ]:
excesso_final = []
dict_excesso = {}
for an in anos:
    ano = an.split("-")[0]
    if ano == '2015':
        pass
    else:
        try:
            df = f'df_ativos_{ano}'
            df_f = pd.DataFrame(eval(df))
            slc = selic_d[selic_d.index.isin(df_f.index)]
            slc['valor_diario'] = slc['valor_diario']/100

            print(f"Tamanho DF de {ano}: ", len(df_f))
            print(f"Tamanho Selic: ", len(df_f))
            dict_excesso[ano] = df_f.sub(slc['valor_diario'],axis=0)

            print("Atualizado, Ano: ",ano)
        except Exception as e:
            print(e)
            print("ERror")

Atualizado, Ano:  2016
Atualizado, Ano:  2017
Atualizado, Ano:  2018
Atualizado, Ano:  2019
Atualizado, Ano:  2020
Atualizado, Ano:  2021
Atualizado, Ano:  2022
Atualizado, Ano:  2023
Atualizado, Ano:  2024
Atualizado, Ano:  2025

C:\Users\joaon\AppData\Local\Temp\ipykernel_1420\182802722.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  slc['valor_diario'] = slc['valor_diario']/100

In [151]:
dict_excesso['2017']

,ABEV3,ALOS3,AXIA3,AZZA3,B3SA3,BBAS3,BBDC3,BBDC4,BBSE3,BEEF3,...,SUZB3,TAEE11,TOTS3,UGPA3,USIM5,VALE3,VBBR3,VIVT3,WEGE3,YDUQ3
2017-01-02,-0.005595,-0.013456,-0.013698,-0.000507,-0.013440,-0.019687,-0.011089,-0.007004,-0.017069,-0.020683,...,-0.000107,0.031715,-0.018826,-0.008142,-0.004985,-0.024250,-0.000107,-0.019364,-0.025914,-0.022259
2017-01-03,0.020125,0.001069,-0.007219,0.034224,0.041048,0.045645,0.040418,0.042246,0.035479,0.024262,...,-0.000107,0.001762,0.051185,0.016093,0.051363,0.044186,-0.000107,0.017705,0.050224,0.055556
2017-01-04,-0.007920,0.005768,0.011083,0.028453,0.018772,-0.005316,-0.000441,-0.006441,0.031479,-0.022257,...,-0.000107,-0.008970,-0.006156,-0.016049,0.060499,-0.018067,-0.000107,-0.002885,-0.024067,-0.005012
2017-01-05,0.005344,-0.001859,-0.004091,0.005521,-0.012267,-0.002551,0.005567,0.010963,-0.020296,-0.010174,...,-0.000107,0.004599,0.005166,0.005784,0.010881,0.038025,-0.000107,-0.036598,-0.002692,-0.016127
2017-01-06,-0.008541,0.003403,-0.001441,-0.001973,-0.000693,0.010740,0.007526,0.006196,-0.015560,-0.004345,...,-0.000107,-0.008538,-0.031181,-0.004500,-0.028368,-0.026719,-0.000107,0.023599,0.008313,-0.007621
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-12-25,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,...,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083
2017-12-26,0.010378,0.009878,-0.020317,0.005549,0.003058,0.010779,0.011733,0.002020,-0.002210,0.007677,...,-0.008666,0.014828,0.003228,-0.001843,0.004386,0.001425,-0.000083,0.014686,0.017635,0.002556
2017-12-27,0.006976,0.007017,-0.001170,0.005130,0.013781,0.012243,0.006326,0.001118,0.008088,0.036491,...,0.002082,-0.001979,-0.008004,0.003850,0.012153,0.000168,-0.000083,-0.018381,-0.000488,-0.009150
2017-12-28,-0.005690,-0.007133,0.052148,0.050628,0.004770,-0.006640,0.020611,0.014910,0.003793,-0.011225,...,0.009096,0.013213,-0.002196,0.012883,-0.000083,0.009952,-0.000083,0.004550,-0.023575,-0.031370
2017-12-29,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,...,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083,-0.000083

In [16]:
exc_2016 = df_ativos_2016.sub(selic_d_2016['valor_diario'], axis=0)
sharpe_2016 = exc_2016.mean() / df_ativos_2016.std()   # Series: index=ticker

In [17]:
for an in anos:
    ano = an.split("-")[0]

    load_dataframe_ano =

2025
2024
2023
2022
2021
2020
2019
2018
2017
2016
2015

## COMEÇO SIGMA

In [18]:
sigma_2016 = exc_2016.cov()

In [19]:
sigma_2016

,ABEV3,ALOS3,AXIA3,AZZA3,B3SA3,BBAS3,BBDC3,BBDC4,BBSE3,BEEF3,...,SUZB3,TAEE11,TOTS3,UGPA3,USIM5,VALE3,VBBR3,VIVT3,WEGE3,YDUQ3
ABEV3,1.857643e-04,3.882087e-05,1.412656e-04,8.976009e-05,1.298149e-04,1.648507e-04,1.258232e-04,1.299559e-04,1.516443e-04,3.599310e-05,...,3.078583e-07,6.104436e-05,1.038451e-04,1.093155e-04,8.645480e-05,1.929648e-04,-4.704233e-10,1.160840e-04,1.314712e-04,1.062520e-04
ALOS3,3.882087e-05,4.203277e-04,8.438046e-05,7.855790e-05,1.483019e-04,1.900653e-04,1.316133e-04,1.489770e-04,9.228425e-05,2.769014e-05,...,1.994943e-07,7.885630e-05,2.675717e-05,5.622593e-05,3.034654e-04,1.933133e-04,-5.571289e-10,5.282595e-05,6.038165e-05,8.894494e-05
AXIA3,1.412656e-04,8.438046e-05,1.117532e-03,1.547592e-04,3.265377e-04,5.079805e-04,3.436896e-04,4.179240e-04,3.421668e-04,1.423937e-04,...,-1.126173e-06,9.850124e-05,6.970688e-05,1.592786e-04,7.106890e-04,3.316526e-04,-1.332651e-09,2.015026e-04,2.093848e-04,2.033234e-04
AZZA3,8.976009e-05,7.855790e-05,1.547592e-04,5.470285e-04,1.948095e-04,2.671184e-04,1.829095e-04,2.436315e-04,1.736969e-04,6.234764e-06,...,4.430864e-07,9.388363e-05,1.009045e-04,8.778039e-05,3.419979e-04,2.174849e-04,-8.820832e-10,8.229385e-05,1.257443e-04,1.495670e-04
B3SA3,1.298149e-04,1.483019e-04,3.265377e-04,1.948095e-04,5.343569e-04,5.014044e-04,3.441961e-04,3.823077e-04,3.505617e-04,9.422759e-05,...,4.881455e-08,1.091902e-04,1.496593e-04,1.457659e-04,6.183703e-04,3.676249e-04,-5.476973e-10,1.560851e-04,1.687425e-04,2.014350e-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VALE3,1.929648e-04,1.933133e-04,3.316526e-04,2.174849e-04,3.676249e-04,5.378647e-04,3.631534e-04,4.718450e-04,3.100813e-04,2.227360e-04,...,1.645120e-06,1.128312e-04,1.845552e-04,1.690502e-04,1.218829e-03,1.803142e-03,6.797242e-11,2.982101e-04,2.220364e-04,4.206536e-04
VBBR3,-4.704233e-10,-5.571289e-10,-1.332651e-09,-8.820832e-10,-5.476973e-10,-5.129639e-10,-4.919491e-10,-7.214415e-10,-5.321234e-10,5.074780e-10,...,-9.700632e-12,7.952272e-11,-5.677994e-11,-2.927280e-10,-6.806679e-10,6.797242e-11,1.658036e-13,-1.211433e-10,-3.912379e-10,-6.866906e-10
VIVT3,1.160840e-04,5.282595e-05,2.015026e-04,8.229385e-05,1.560851e-04,3.176651e-04,1.921130e-04,1.992927e-04,2.073140e-04,1.012943e-04,...,1.145224e-06,1.416386e-04,8.894928e-05,1.410551e-04,3.351043e-04,2.982101e-04,-1.211433e-10,5.092660e-04,1.605200e-04,1.888615e-04
WEGE3,1.314712e-04,6.038165e-05,2.093848e-04,1.257443e-04,1.687425e-04,2.890841e-04,2.071932e-04,2.372811e-04,2.213850e-04,5.253340e-05,...,1.545415e-06,9.461188e-05,1.443303e-04,1.426024e-04,1.855514e-04,2.220364e-04,-3.912379e-10,1.605200e-04,4.237409e-04,1.517862e-04
YDUQ3,1.062520e-04,8.894494e-05,2.033234e-04,1.495670e-04,2.014350e-04,4.345806e-04,2.600972e-04,3.539687e-04,2.885884e-04,5.652035e-05,...,1.115604e-06,9.206746e-05,1.786873e-04,1.070036e-04,5.224731e-04,4.206536e-04,-6.866906e-10,1.888615e-04,1.517862e-04,1.158904e-03

In [20]:
exc_2016.cov()

,ABEV3,ALOS3,AXIA3,AZZA3,B3SA3,BBAS3,BBDC3,BBDC4,BBSE3,BEEF3,...,SUZB3,TAEE11,TOTS3,UGPA3,USIM5,VALE3,VBBR3,VIVT3,WEGE3,YDUQ3
ABEV3,1.857643e-04,3.882087e-05,1.412656e-04,8.976009e-05,1.298149e-04,1.648507e-04,1.258232e-04,1.299559e-04,1.516443e-04,3.599310e-05,...,3.078583e-07,6.104436e-05,1.038451e-04,1.093155e-04,8.645480e-05,1.929648e-04,-4.704233e-10,1.160840e-04,1.314712e-04,1.062520e-04
ALOS3,3.882087e-05,4.203277e-04,8.438046e-05,7.855790e-05,1.483019e-04,1.900653e-04,1.316133e-04,1.489770e-04,9.228425e-05,2.769014e-05,...,1.994943e-07,7.885630e-05,2.675717e-05,5.622593e-05,3.034654e-04,1.933133e-04,-5.571289e-10,5.282595e-05,6.038165e-05,8.894494e-05
AXIA3,1.412656e-04,8.438046e-05,1.117532e-03,1.547592e-04,3.265377e-04,5.079805e-04,3.436896e-04,4.179240e-04,3.421668e-04,1.423937e-04,...,-1.126173e-06,9.850124e-05,6.970688e-05,1.592786e-04,7.106890e-04,3.316526e-04,-1.332651e-09,2.015026e-04,2.093848e-04,2.033234e-04
AZZA3,8.976009e-05,7.855790e-05,1.547592e-04,5.470285e-04,1.948095e-04,2.671184e-04,1.829095e-04,2.436315e-04,1.736969e-04,6.234764e-06,...,4.430864e-07,9.388363e-05,1.009045e-04,8.778039e-05,3.419979e-04,2.174849e-04,-8.820832e-10,8.229385e-05,1.257443e-04,1.495670e-04
B3SA3,1.298149e-04,1.483019e-04,3.265377e-04,1.948095e-04,5.343569e-04,5.014044e-04,3.441961e-04,3.823077e-04,3.505617e-04,9.422759e-05,...,4.881455e-08,1.091902e-04,1.496593e-04,1.457659e-04,6.183703e-04,3.676249e-04,-5.476973e-10,1.560851e-04,1.687425e-04,2.014350e-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VALE3,1.929648e-04,1.933133e-04,3.316526e-04,2.174849e-04,3.676249e-04,5.378647e-04,3.631534e-04,4.718450e-04,3.100813e-04,2.227360e-04,...,1.645120e-06,1.128312e-04,1.845552e-04,1.690502e-04,1.218829e-03,1.803142e-03,6.797242e-11,2.982101e-04,2.220364e-04,4.206536e-04
VBBR3,-4.704233e-10,-5.571289e-10,-1.332651e-09,-8.820832e-10,-5.476973e-10,-5.129639e-10,-4.919491e-10,-7.214415e-10,-5.321234e-10,5.074780e-10,...,-9.700632e-12,7.952272e-11,-5.677994e-11,-2.927280e-10,-6.806679e-10,6.797242e-11,1.658036e-13,-1.211433e-10,-3.912379e-10,-6.866906e-10
VIVT3,1.160840e-04,5.282595e-05,2.015026e-04,8.229385e-05,1.560851e-04,3.176651e-04,1.921130e-04,1.992927e-04,2.073140e-04,1.012943e-04,...,1.145224e-06,1.416386e-04,8.894928e-05,1.410551e-04,3.351043e-04,2.982101e-04,-1.211433e-10,5.092660e-04,1.605200e-04,1.888615e-04
WEGE3,1.314712e-04,6.038165e-05,2.093848e-04,1.257443e-04,1.687425e-04,2.890841e-04,2.071932e-04,2.372811e-04,2.213850e-04,5.253340e-05,...,1.545415e-06,9.461188e-05,1.443303e-04,1.426024e-04,1.855514e-04,2.220364e-04,-3.912379e-10,1.605200e-04,4.237409e-04,1.517862e-04
YDUQ3,1.062520e-04,8.894494e-05,2.033234e-04,1.495670e-04,2.014350e-04,4.345806e-04,2.600972e-04,3.539687e-04,2.885884e-04,5.652035e-05,...,1.115604e-06,9.206746e-05,1.786873e-04,1.070036e-04,5.224731e-04,4.206536e-04,-6.866906e-10,1.888615e-04,1.517862e-04,1.158904e-03

#### Dados da Magic Formula (SCORE)

In [21]:


# y1 = []
# y2 = []
# for a in anos[:-1]:
#     y1.append(a)
# for a in anos[:-1]:
#     y2.append(a.split('-')[0])

# print("=-"*48)
# print("Anos totais: ",y)
# print("=-"*48)

dict_score_todos = []
dict_score = {}
for i, ativo in enumerate(df_ativos_2016.columns.tolist()):
        if ativo == lista_mf_check[i]['ativo']:
            for ano in anos:
                df_temp = lista_mf_check[i]['data'].query("endDate in @ano")
                score_anual = (0.5*df_temp['ROC'] + 0.5*df_temp['EY']).sum()
                dict_score[(ano, ativo)] = score_anual
                print("feito dict do ativo: ",ativo,ano,score_anual)
        else:
            print(f" ativo: {ativo}")
            print(f" ativo_mf: {lista_mf_check[i]['ativo']}")
df_scores = pd.Series(dict_score).unstack()  # index=anos, columns=ativos
df_scores = df_scores.replace([np.inf, -np.inf],0)    

dict_score_todos.append(df_scores)

feito dict do ativo:  ABEV3 2025-12-31 0.5075949601583762
feito dict do ativo:  ABEV3 2024-12-31 0.38261468462358406
feito dict do ativo:  ABEV3 2023-12-31 0.4707780476577104
feito dict do ativo:  ABEV3 2022-12-31 0.3698561983003272
feito dict do ativo:  ABEV3 2021-12-31 0.33762441702482754
feito dict do ativo:  ABEV3 2020-12-31 0.3419377467430017
feito dict do ativo:  ABEV3 2019-12-31 0.3554827706790753
feito dict do ativo:  ABEV3 2018-12-31 0.4588246122822893
feito dict do ativo:  ABEV3 2017-12-31 0.587594465523369
feito dict do ativo:  ABEV3 2016-12-31 0.6475658938442502
feito dict do ativo:  ABEV3 2015-12-31 0.5948621071274975
feito dict do ativo:  ALOS3 2025-12-31 0.39483852927400404
feito dict do ativo:  ALOS3 2024-12-31 0.3900179383466277
feito dict do ativo:  ALOS3 2023-12-31 1.655507111089378
feito dict do ativo:  ALOS3 2022-12-31 inf
feito dict do ativo:  ALOS3 2021-12-31 inf
feito dict do ativo:  ALOS3 2020-12-31 inf
feito dict do ativo:  ALOS3 2019-12-31 inf
feito dict do ativo:  ALOS3 2018-12-31 inf
feito dict do ativo:  ALOS3 2017-12-31 inf
feito dict do ativo:  ALOS3 2016-12-31 inf
feito dict do ativo:  ALOS3 2015-12-31 inf
feito dict do ativo:  AXIA3 2025-12-31 0.039962129224727354
feito dict do ativo:  AXIA3 2024-12-31 0.22092668246503305
feito dict do ativo:  AXIA3 2023-12-31 0.1557060662619637
feito dict do ativo:  AXIA3 2022-12-31 0.0863949979860275
feito dict do ativo:  AXIA3 2021-12-31 0.1864886904823606
feito dict do ativo:  AXIA3 2020-12-31 0.1208797499579457
feito dict do ativo:  AXIA3 2019-12-31 0.1232061008742997
feito dict do ativo:  AXIA3 2018-12-31 0.290077106731664
feito dict do ativo:  AXIA3 2017-12-31 0.10261123234047846
feito dict do ativo:  AXIA3 2016-12-31 0.43765344807392387
feito dict do ativo:  AXIA3 2015-12-31 -0.2803575070611428
feito dict do ativo:  AZZA3 2025-12-31 0.17218008546705044
feito dict do ativo:  AZZA3 2024-12-31 0.06218776601061185
feito dict do ativo:  AZZA3 2023-12-31 0.22449677141697774
feito dict do ativo:  AZZA3 2022-12-31 0.2272988550799676
feito dict do ativo:  AZZA3 2021-12-31 0.4720334772463487
feito dict do ativo:  AZZA3 2020-12-31 0.23108633624637676
feito dict do ativo:  AZZA3 2019-12-31 0.1592624048085601
feito dict do ativo:  AZZA3 2018-12-31 0.16795910877337916
feito dict do ativo:  AZZA3 2017-12-31 0.1766990358270806
feito dict do ativo:  AZZA3 2016-12-31 0.18205100122835866
feito dict do ativo:  AZZA3 2015-12-31 0.18898138992582925
feito dict do ativo:  B3SA3 2025-12-31 0.3871316068593503
feito dict do ativo:  B3SA3 2024-12-31 0.47648693738333525
feito dict do ativo:  B3SA3 2023-12-31 0.37210588171393993
feito dict do ativo:  B3SA3 2022-12-31 0.35712235330546893
feito dict do ativo:  B3SA3 2021-12-31 0.40195673910410157
feito dict do ativo:  B3SA3 2020-12-31 0.3684393689516793
feito dict do ativo:  B3SA3 2019-12-31 0.5921164504448382
feito dict do ativo:  B3SA3 2018-12-31 0.5826283083132008
feito dict do ativo:  B3SA3 2017-12-31 0.5163726248617743
feito dict do ativo:  B3SA3 2016-12-31 0.15937331695474855
feito dict do ativo:  B3SA3 2015-12-31 0.6576070804644214
feito dict do ativo:  BBAS3 2025-12-31 0.0
feito dict do ativo:  BBAS3 2024-12-31 0.0
feito dict do ativo:  BBAS3 2023-12-31 0.0
feito dict do ativo:  BBAS3 2022-12-31 0.0
feito dict do ativo:  BBAS3 2021-12-31 0.0
feito dict do ativo:  BBAS3 2020-12-31 0.0
feito dict do ativo:  BBAS3 2019-12-31 0.0
feito dict do ativo:  BBAS3 2018-12-31 0.0
feito dict do ativo:  BBAS3 2017-12-31 0.0
feito dict do ativo:  BBAS3 2016-12-31 0.0
feito dict do ativo:  BBAS3 2015-12-31 0.0
feito dict do ativo:  BBDC3 2025-12-31 0.0
feito dict do ativo:  BBDC3 2024-12-31 0.0
feito dict do ativo:  BBDC3 2023-12-31 0.0
feito dict do ativo:  BBDC3 2022-12-31 0.0
feito dict do ativo:  BBDC3 2021-12-31 0.0
feito dict do ativo:  BBDC3 2020-12-31 0.0
feito dict do ativo:  BBDC3 2019-12-31 0.0
feito dict do ativo:  BBDC3 2018-12-31 0.0
feito dict do ativo:  BBDC3 2017-12-31 0.0
feito dict do ativo:  BBDC3 2016-12-31 0.0
feito dict do ativo:  BBDC3 2015-12-31 0.0
feito dict do ativo:  BBDC4 2025-12-31 0.0
feito dict do ativo:  BBDC4 2024-12-31 0.0
feito dict do ativo:  BBDC4 2023-12-31 0.0
feito dict do ativo:  BBDC4 2022-12-31 0.0
feito dict do ativo:  BBDC4 2021-12-31 0.0
feito dict do ativo:  BBDC4 2020-12-31 0.0
feito dict do ativo:  BBDC4 2019-12-31 0.0
feito dict do ativo:  BBDC4 2018-12-31 0.0
feito dict do ativo:  BBDC4 2017-12-31 0.0
feito dict do ativo:  BBDC4 2016-12-31 0.0
feito dict do ativo:  BBDC4 2015-12-31 0.0
feito dict do ativo:  BBSE3 2025-12-31 2.0753745252427933
feito dict do ativo:  BBSE3 2024-12-31 3.0855741501961327
feito dict do ativo:  BBSE3 2023-12-31 9.861036597674278
feito dict do ativo:  BBSE3 2022-12-31 2.6253644354066994
feito dict do ativo:  BBSE3 2021-12-31 1.4398233272468384
feito dict do ativo:  BBSE3 2020-12-31 1.935120903212727
feito dict do ativo:  BBSE3 2019-12-31 6.092117050040411
feito dict do ativo:  BBSE3 2018-12-31 0.8400804469030312
feito dict do ativo:  BBSE3 2017-12-31 0.7624327120127663
feito dict do ativo:  BBSE3 2016-12-31 8.30092303025193
feito dict do ativo:  BBSE3 2015-12-31 -9.966454847066405
feito dict do ativo:  BEEF3 2025-12-31 0.22275440679253722
feito dict do ativo:  BEEF3 2024-12-31 0.13633540112736775
feito dict do ativo:  BEEF3 2023-12-31 0.14820141315943686
feito dict do ativo:  BEEF3 2022-12-31 0.2043372704006172
feito dict do ativo:  BEEF3 2021-12-31 0.17651429087779055
feito dict do ativo:  BEEF3 2020-12-31 0.19014773505291754
feito dict do ativo:  BEEF3 2019-12-31 0.18250741296224826
feito dict do ativo:  BEEF3 2018-12-31 0.10176736813008516
feito dict do ativo:  BEEF3 2017-12-31 0.1324959052603814
feito dict do ativo:  BEEF3 2016-12-31 0.16588602705558053
feito dict do ativo:  BEEF3 2015-12-31 0.18094207031617432
feito dict do ativo:  BPAC11 2025-12-31 0.0
feito dict do ativo:  BPAC11 2024-12-31 0.0
feito dict do ativo:  BPAC11 2023-12-31 0.0
feito dict do ativo:  BPAC11 2022-12-31 0.0
feito dict do ativo:  BPAC11 2021-12-31 0.0
feito dict do ativo:  BPAC11 2020-12-31 0.0
feito dict do ativo:  BPAC11 2019-12-31 0.0
feito dict do ativo:  BPAC11 2018-12-31 0.0
feito dict do ativo:  BPAC11 2017-12-31 0.0
feito dict do ativo:  BPAC11 2016-12-31 0.0
feito dict do ativo:  BPAC11 2015-12-31 0.0
feito dict do ativo:  BRAP4 2025-12-31 1.1115547745521173
feito dict do ativo:  BRAP4 2024-12-31 2.470400155061656
feito dict do ativo:  BRAP4 2023-12-31 4.9314635082254155
feito dict do ativo:  BRAP4 2022-12-31 27.885003709821877
feito dict do ativo:  BRAP4 2021-12-31 17.109073129045967
feito dict do ativo:  BRAP4 2020-12-31 2.081669631543931
feito dict do ativo:  BRAP4 2019-12-31 -0.9425256772583969
feito dict do ativo:  BRAP4 2018-12-31 6.11076669813114
feito dict do ativo:  BRAP4 2017-12-31 -1.2312475629507134
feito dict do ativo:  BRAP4 2016-12-31 0.5662464360829212
feito dict do ativo:  BRAP4 2015-12-31 -4.348975686122801
feito dict do ativo:  BRAV3 2025-12-31 0.09670670756210739
feito dict do ativo:  BRAV3 2024-12-31 0.10315509685417465
feito dict do ativo:  BRAV3 2023-12-31 0.13210103832562364
feito dict do ativo:  BRAV3 2022-12-31 0.0609329492365719
feito dict do ativo:  BRAV3 2021-12-31 0.11294971673935439
feito dict do ativo:  BRAV3 2020-12-31 -0.10698610540329315
feito dict do ativo:  BRAV3 2019-12-31 -0.024633228048453998
feito dict do ativo:  BRAV3 2018-12-31 inf
feito dict do ativo:  BRAV3 2017-12-31 inf
feito dict do ativo:  BRAV3 2016-12-31 inf
feito dict do ativo:  BRAV3 2015-12-31 -inf
feito dict do ativo:  BRKM5 2025-12-31 -0.043347576370339355
feito dict do ativo:  BRKM5 2024-12-31 -0.0176583349095655
feito dict do ativo:  BRKM5 2023-12-31 -0.04722649246317315
feito dict do ativo:  BRKM5 2022-12-31 0.07489015457393375
feito dict do ativo:  BRKM5 2021-12-31 0.3784709101685788
feito dict do ativo:  BRKM5 2020-12-31 -0.0013925977254297
feito dict do ativo:  BRKM5 2019-12-31 -0.00114130278796935
feito dict do ativo:  BRKM5 2018-12-31 0.2153183979479587
feito dict do ativo:  BRKM5 2017-12-31 0.25617875678497726
feito dict do ativo:  BRKM5 2016-12-31 0.20295425819644397
feito dict do ativo:  BRKM5 2015-12-31 0.17097534309555756
feito dict do ativo:  CMIG4 2025-12-31 0.8626841659439108
feito dict do ativo:  CMIG4 2024-12-31 2.844887848588837
feito dict do ativo:  CMIG4 2023-12-31 1.8729180458767898
feito dict do ativo:  CMIG4 2022-12-31 0.68426398729129
feito dict do ativo:  CMIG4 2021-12-31 0.825078050778421
feito dict do ativo:  CMIG4 2020-12-31 0.3386757696184143
feito dict do ativo:  CMIG4 2019-12-31 0.36473050381709654
feito dict do ativo:  CMIG4 2018-12-31 0.2068687712060877
feito dict do ativo:  CMIG4 2017-12-31 0.5469594898561008
feito dict do ativo:  CMIG4 2016-12-31 1.5017182660490214
feito dict do ativo:  CMIG4 2015-12-31 8.511375272326474
feito dict do ativo:  COGN3 2025-12-31 0.160382984661286
feito dict do ativo:  COGN3 2024-12-31 0.19175931014917658
feito dict do ativo:  COGN3 2023-12-31 0.0933006072765408
feito dict do ativo:  COGN3 2022-12-31 0.040444870179164996
feito dict do ativo:  COGN3 2021-12-31 0.0081185190259437
feito dict do ativo:  COGN3 2020-12-31 -0.2705394405693553
feito dict do ativo:  COGN3 2019-12-31 0.08212873205164929
feito dict do ativo:  COGN3 2018-12-31 0.14077940687357124
feito dict do ativo:  COGN3 2017-12-31 0.2392239869670402
feito dict do ativo:  COGN3 2016-12-31 0.33962787614040924
feito dict do ativo:  COGN3 2015-12-31 0.40836301686297805
feito dict do ativo:  CPFE3 2025-12-31 0.7379570414139054
feito dict do ativo:  CPFE3 2024-12-31 0.6858768201181811
feito dict do ativo:  CPFE3 2023-12-31 0.7118476207094178
feito dict do ativo:  CPFE3 2022-12-31 0.5808498528572436
feito dict do ativo:  CPFE3 2021-12-31 0.41195689348773773
feito dict do ativo:  CPFE3 2020-12-31 0.4113422671021893
feito dict do ativo:  CPFE3 2019-12-31 0.3137668380536196
feito dict do ativo:  CPFE3 2018-12-31 0.25214856456309465
feito dict do ativo:  CPFE3 2017-12-31 0.2670224277973613
feito dict do ativo:  CPFE3 2016-12-31 0.16447922084585945
feito dict do ativo:  CPFE3 2015-12-31 0.1513381079195136
feito dict do ativo:  CPLE3 2025-12-31 0.35789450256311467
feito dict do ativo:  CPLE3 2024-12-31 0.2291673869379505
feito dict do ativo:  CPLE3 2023-12-31 0.16517927908959856
feito dict do ativo:  CPLE3 2022-12-31 0.15987544414130034
feito dict do ativo:  CPLE3 2021-12-31 0.29282512146893763
feito dict do ativo:  CPLE3 2020-12-31 0.26529498938133717
feito dict do ativo:  CPLE3 2019-12-31 0.22799071840074864
feito dict do ativo:  CPLE3 2018-12-31 0.19267884943132818
feito dict do ativo:  CPLE3 2017-12-31 0.1949907888140957
feito dict do ativo:  CPLE3 2016-12-31 0.22440674056690169
feito dict do ativo:  CPLE3 2015-12-31 0.1927719936905758
feito dict do ativo:  CSAN3 2025-12-31 -0.0025293839862629
feito dict do ativo:  CSAN3 2024-12-31 0.0573015365516788
feito dict do ativo:  CSAN3 2023-12-31 0.21305091256424308
feito dict do ativo:  CSAN3 2022-12-31 0.14630662167698355
feito dict do ativo:  CSAN3 2021-12-31 0.16243843022901594
feito dict do ativo:  CSAN3 2020-12-31 0.22100376033628427
feito dict do ativo:  CSAN3 2019-12-31 0.39051932811624757
feito dict do ativo:  CSAN3 2018-12-31 0.42572784281725534
feito dict do ativo:  CSAN3 2017-12-31 0.5413177063043684
feito dict do ativo:  CSAN3 2016-12-31 0.5068078801098811
feito dict do ativo:  CSAN3 2015-12-31 0.5263275525639541
feito dict do ativo:  CSMG3 2025-12-31 0.5479194663048437
feito dict do ativo:  CSMG3 2024-12-31 0.5793886658138119
feito dict do ativo:  CSMG3 2023-12-31 0.5996375551384604
feito dict do ativo:  CSMG3 2022-12-31 0.47930950646770676
feito dict do ativo:  CSMG3 2021-12-31 0.31868783205967305
feito dict do ativo:  CSMG3 2020-12-31 0.4717908885237141
feito dict do ativo:  CSMG3 2019-12-31 0.4132221592182493
feito dict do ativo:  CSMG3 2018-12-31 0.29738858607048674
feito dict do ativo:  CSMG3 2017-12-31 0.3255230027013085
feito dict do ativo:  CSMG3 2016-12-31 0.6366174479328897
feito dict do ativo:  CSMG3 2015-12-31 0.3018761372504819
feito dict do ativo:  CSNA3 2025-12-31 0.10421314474457105
feito dict do ativo:  CSNA3 2024-12-31 0.08311858202002076
feito dict do ativo:  CSNA3 2023-12-31 0.1152115456072879
feito dict do ativo:  CSNA3 2022-12-31 0.19030181619044956
feito dict do ativo:  CSNA3 2021-12-31 0.5744687901856544
feito dict do ativo:  CSNA3 2020-12-31 0.1522132774564707
feito dict do ativo:  CSNA3 2019-12-31 0.12758828999431354
feito dict do ativo:  CSNA3 2018-12-31 0.28314013998003795
feito dict do ativo:  CSNA3 2017-12-31 0.1195325585865499
feito dict do ativo:  CSNA3 2016-12-31 0.0653118156720241
feito dict do ativo:  CSNA3 2015-12-31 0.17252612028428405
feito dict do ativo:  CXSE3 2025-12-31 2.772299921179611
feito dict do ativo:  CXSE3 2024-12-31 2.5775170465658714
feito dict do ativo:  CXSE3 2023-12-31 40.037099613108
feito dict do ativo:  CXSE3 2022-12-31 2.048093884925602
feito dict do ativo:  CXSE3 2021-12-31 1.311483773266576
feito dict do ativo:  CXSE3 2020-12-31 inf
feito dict do ativo:  CXSE3 2019-12-31 inf
feito dict do ativo:  CXSE3 2018-12-31 inf
feito dict do ativo:  CXSE3 2017-12-31 inf
feito dict do ativo:  CXSE3 2016-12-31 inf
feito dict do ativo:  CXSE3 2015-12-31 inf
feito dict do ativo:  CYRE3 2025-12-31 0.15699893346053145
feito dict do ativo:  CYRE3 2024-12-31 0.21225672190064665
feito dict do ativo:  CYRE3 2023-12-31 0.13923710809772735
feito dict do ativo:  CYRE3 2022-12-31 0.14325086689577265
feito dict do ativo:  CYRE3 2021-12-31 0.1736900316190976
feito dict do ativo:  CYRE3 2020-12-31 0.3873952300276515
feito dict do ativo:  CYRE3 2019-12-31 0.12388522797166604
feito dict do ativo:  CYRE3 2018-12-31 0.011443327860161251
feito dict do ativo:  CYRE3 2017-12-31 0.0037388193928721497
feito dict do ativo:  CYRE3 2016-12-31 0.047740370361733606
feito dict do ativo:  CYRE3 2015-12-31 0.1561925750552557
feito dict do ativo:  CYRE4 2025-12-31 0.15699893346053145
feito dict do ativo:  CYRE4 2024-12-31 0.21225672190064665
feito dict do ativo:  CYRE4 2023-12-31 0.13923710809772735
feito dict do ativo:  CYRE4 2022-12-31 0.14325086689577265
feito dict do ativo:  CYRE4 2021-12-31 0.1736900316190976
feito dict do ativo:  CYRE4 2020-12-31 0.3873952300276515
feito dict do ativo:  CYRE4 2019-12-31 0.12388522797166604
feito dict do ativo:  CYRE4 2018-12-31 0.011443327860161251
feito dict do ativo:  CYRE4 2017-12-31 0.0037388193928721497
feito dict do ativo:  CYRE4 2016-12-31 0.047740370361733606
feito dict do ativo:  CYRE4 2015-12-31 0.1561925750552557
feito dict do ativo:  DIRR3 2025-12-31 0.13924379506737972
feito dict do ativo:  DIRR3 2024-12-31 0.17588285608866405
feito dict do ativo:  DIRR3 2023-12-31 0.1288285553510129
feito dict do ativo:  DIRR3 2022-12-31 0.14278186924494204
feito dict do ativo:  DIRR3 2021-12-31 0.1153943474778473
feito dict do ativo:  DIRR3 2020-12-31 0.0886336841085626
feito dict do ativo:  DIRR3 2019-12-31 0.0856297976895462
feito dict do ativo:  DIRR3 2018-12-31 -0.016560063630435003
feito dict do ativo:  DIRR3 2017-12-31 -0.0731736560182017
feito dict do ativo:  DIRR3 2016-12-31 0.00172583002023155
feito dict do ativo:  DIRR3 2015-12-31 0.10226420399241795
feito dict do ativo:  EGIE3 2025-12-31 0.1515636884512122
feito dict do ativo:  EGIE3 2024-12-31 0.2318604152646736
feito dict do ativo:  EGIE3 2023-12-31 0.2326977742868507
feito dict do ativo:  EGIE3 2022-12-31 0.2549522938841564
feito dict do ativo:  EGIE3 2021-12-31 0.20452187085221518
feito dict do ativo:  EGIE3 2020-12-31 0.2287038984861624
feito dict do ativo:  EGIE3 2019-12-31 0.1914167335362545
feito dict do ativo:  EGIE3 2018-12-31 0.19525417446394
feito dict do ativo:  EGIE3 2017-12-31 0.22410823789263096
feito dict do ativo:  EGIE3 2016-12-31 0.19161797811614767
feito dict do ativo:  EGIE3 2015-12-31 inf
feito dict do ativo:  EMBJ3 2025-12-31 0.08790322762018729
feito dict do ativo:  EMBJ3 2024-12-31 0.10866436786702804
feito dict do ativo:  EMBJ3 2023-12-31 0.0660813094404554
feito dict do ativo:  EMBJ3 2022-12-31 -0.0254347561978699
feito dict do ativo:  EMBJ3 2021-12-31 0.0358962109384138
feito dict do ativo:  EMBJ3 2020-12-31 -0.0675349171217357
feito dict do ativo:  EMBJ3 2019-12-31 -0.05223143404972465
feito dict do ativo:  EMBJ3 2018-12-31 0.00459771020271305
feito dict do ativo:  EMBJ3 2017-12-31 0.05065194120107945
feito dict do ativo:  EMBJ3 2016-12-31 0.0388944667777467
feito dict do ativo:  EMBJ3 2015-12-31 0.04466140102486585
feito dict do ativo:  ENEV3 2025-12-31 0.07753649398038825
feito dict do ativo:  ENEV3 2024-12-31 0.05659396329661905
feito dict do ativo:  ENEV3 2023-12-31 0.07491636862725021
feito dict do ativo:  ENEV3 2022-12-31 0.039081243819630795
feito dict do ativo:  ENEV3 2021-12-31 0.0872476707476512
feito dict do ativo:  ENEV3 2020-12-31 0.06581649974501315
feito dict do ativo:  ENEV3 2019-12-31 0.11100104915802744
feito dict do ativo:  ENEV3 2018-12-31 0.1671082855331812
feito dict do ativo:  ENEV3 2017-12-31 0.1207768523930544
feito dict do ativo:  ENEV3 2016-12-31 0.09761025650010044
feito dict do ativo:  ENEV3 2015-12-31 inf
feito dict do ativo:  ENGI11 2025-12-31 0.32819112485823226
feito dict do ativo:  ENGI11 2024-12-31 0.48514361516406695
feito dict do ativo:  ENGI11 2023-12-31 0.660354555532051
feito dict do ativo:  ENGI11 2022-12-31 0.8685242631704135
feito dict do ativo:  ENGI11 2021-12-31 0.5723668912578656
feito dict do ativo:  ENGI11 2020-12-31 0.8491293999071269
feito dict do ativo:  ENGI11 2019-12-31 0.4575928608511293
feito dict do ativo:  ENGI11 2018-12-31 0.4014454389039089
feito dict do ativo:  ENGI11 2017-12-31 0.4162803072483684
feito dict do ativo:  ENGI11 2016-12-31 0.39020324361118947
feito dict do ativo:  ENGI11 2015-12-31 0.35024098821493865
feito dict do ativo:  EQTL3 2025-12-31 0.2957582891286056
feito dict do ativo:  EQTL3 2024-12-31 0.3255291576987439
feito dict do ativo:  EQTL3 2023-12-31 0.25391995102083303
feito dict do ativo:  EQTL3 2022-12-31 0.5906827974019332
feito dict do ativo:  EQTL3 2021-12-31 0.3274545431442362
feito dict do ativo:  EQTL3 2020-12-31 0.46115157220678576
feito dict do ativo:  EQTL3 2019-12-31 0.4657468984992479
feito dict do ativo:  EQTL3 2018-12-31 0.4254815586645191
feito dict do ativo:  EQTL3 2017-12-31 0.30842465089472826
feito dict do ativo:  EQTL3 2016-12-31 0.3385728923131457
feito dict do ativo:  EQTL3 2015-12-31 0.28649569902524197
feito dict do ativo:  FLRY3 2025-12-31 0.2742966610422349
feito dict do ativo:  FLRY3 2024-12-31 0.26239915701048616
feito dict do ativo:  FLRY3 2023-12-31 0.22496790674247905
feito dict do ativo:  FLRY3 2022-12-31 0.15719706548327955
feito dict do ativo:  FLRY3 2021-12-31 0.20663114684181264
feito dict do ativo:  FLRY3 2020-12-31 0.19088609494021086
feito dict do ativo:  FLRY3 2019-12-31 0.2201492605808751
feito dict do ativo:  FLRY3 2018-12-31 0.20667434773688814
feito dict do ativo:  FLRY3 2017-12-31 0.22264955307896295
feito dict do ativo:  FLRY3 2016-12-31 0.23644775204781293
feito dict do ativo:  FLRY3 2015-12-31 0.18421986413313474
feito dict do ativo:  GGBR4 2025-12-31 0.05505194264088265
feito dict do ativo:  GGBR4 2024-12-31 0.1137630136778814
feito dict do ativo:  GGBR4 2023-12-31 0.18164856321092104
feito dict do ativo:  GGBR4 2022-12-31 0.3102298625634518
feito dict do ativo:  GGBR4 2021-12-31 0.39330946897907054
feito dict do ativo:  GGBR4 2020-12-31 0.12085127115102484
feito dict do ativo:  GGBR4 2019-12-31 0.0828229964681506
feito dict do ativo:  GGBR4 2018-12-31 0.1213672476604337
feito dict do ativo:  GGBR4 2017-12-31 0.03207958808270445
feito dict do ativo:  GGBR4 2016-12-31 -0.046687999998541854
feito dict do ativo:  GGBR4 2015-12-31 -0.08673987952838826
feito dict do ativo:  GOAU4 2025-12-31 0.1088589010549457
feito dict do ativo:  GOAU4 2024-12-31 0.24831823867845634
feito dict do ativo:  GOAU4 2023-12-31 0.36490870551140014
feito dict do ativo:  GOAU4 2022-12-31 0.6166038899715056
feito dict do ativo:  GOAU4 2021-12-31 0.7863401063398895
feito dict do ativo:  GOAU4 2020-12-31 0.21028748828276456

In [22]:
dict_score_todos[0].loc['2016-12-31'].rank(axis=0, pct=True)

ABEV3    0.913043
ALOS3    0.217391
AXIA3    0.840580
AZZA3    0.652174
B3SA3    0.565217
           ...
VALE3    0.507246
VBBR3    0.217391
VIVT3    0.724638
WEGE3    0.521739
YDUQ3    0.217391
Name: 2016-12-31, Length: 69, dtype: float64

In [23]:
score_todos_anos = dict_score_todos[0].rank(axis=1,pct=True)

In [58]:
score_todos_anos

,ABEV3,ALOS3,AXIA3,AZZA3,B3SA3,BBAS3,BBDC3,BBDC4,BBSE3,BEEF3,...,SUZB3,TAEE11,TOTS3,UGPA3,USIM5,VALE3,VBBR3,VIVT3,WEGE3,YDUQ3
2015,0.898551,0.311594,0.072464,0.695652,0.913043,0.311594,0.311594,0.311594,0.014493,0.652174,...,0.536232,0.956522,0.797101,0.753623,0.057971,0.086957,0.311594,0.666667,0.550725,0.311594
2016,0.913043,0.217391,0.840580,0.652174,0.565217,0.217391,0.217391,0.217391,1.000000,0.623188,...,0.434783,0.942029,0.782609,0.666667,0.086957,0.507246,0.217391,0.724638,0.521739,0.217391
2017,0.927536,0.195652,0.507246,0.652174,0.869565,0.195652,0.195652,0.195652,0.971014,0.565217,...,0.579710,0.840580,0.608696,0.594203,0.405797,0.623188,0.195652,0.681159,0.521739,0.195652
2018,0.855072,0.166667,0.768116,0.565217,0.869565,0.166667,0.166667,0.166667,0.956522,0.405797,...,0.420290,0.884058,0.536232,0.333333,0.318841,0.594203,0.166667,0.739130,0.507246,0.166667
2019,0.840580,0.188406,0.521739,0.681159,0.942029,0.188406,0.188406,0.188406,1.000000,0.710145,...,0.289855,0.811594,0.507246,0.304348,0.318841,0.275362,0.188406,0.666667,0.594203,0.739130
2020,0.768116,0.159420,0.492754,0.724638,0.782609,0.159420,0.159420,0.159420,0.971014,0.652174,...,0.463768,0.956522,0.637681,0.318841,0.565217,0.579710,0.159420,0.536232,0.507246,0.260870
2021,0.710145,0.072464,0.536232,0.797101,0.753623,0.072464,0.072464,0.072464,0.971014,0.521739,...,0.550725,0.985507,0.347826,0.217391,0.811594,0.782609,0.362319,0.434783,0.463768,0.275362
2022,0.739130,0.101449,0.304348,0.637681,0.724638,0.101449,0.101449,0.101449,0.985507,0.608696,...,0.623188,0.826087,0.362319,0.594203,0.521739,0.695652,0.536232,0.420290,0.550725,0.391304
2023,0.811594,0.942029,0.463768,0.623188,0.782609,0.094203,0.094203,0.094203,0.985507,0.449275,...,0.333333,0.855072,0.391304,0.594203,0.159420,0.565217,0.739130,0.434783,0.579710,0.478261
2024,0.768116,0.782609,0.608696,0.202899,0.811594,0.094203,0.094203,0.094203,1.000000,0.376812,...,0.405797,0.942029,0.652174,0.681159,0.144928,0.507246,0.753623,0.391304,0.565217,0.536232
2025,0.855072,0.797101,0.188406,0.565217,0.782609,0.108696,0.108696,0.108696,0.971014,0.652174,...,0.260870,0.927536,0.710145,0.579710,0.014493,0.275362,0.405797,0.434783,0.637681,0.623188

In [24]:
index_novo = []
for indexx in score_todos_anos.index:
    novo = indexx.split('-')[0]
    index_novo.append(novo)
print(index_novo)

['2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

In [25]:
score_todos_anos.index=  index_novo

In [26]:
score_todos_anos

,ABEV3,ALOS3,AXIA3,AZZA3,B3SA3,BBAS3,BBDC3,BBDC4,BBSE3,BEEF3,...,SUZB3,TAEE11,TOTS3,UGPA3,USIM5,VALE3,VBBR3,VIVT3,WEGE3,YDUQ3
2015,0.898551,0.311594,0.072464,0.695652,0.913043,0.311594,0.311594,0.311594,0.014493,0.652174,...,0.536232,0.956522,0.797101,0.753623,0.057971,0.086957,0.311594,0.666667,0.550725,0.311594
2016,0.913043,0.217391,0.840580,0.652174,0.565217,0.217391,0.217391,0.217391,1.000000,0.623188,...,0.434783,0.942029,0.782609,0.666667,0.086957,0.507246,0.217391,0.724638,0.521739,0.217391
2017,0.927536,0.195652,0.507246,0.652174,0.869565,0.195652,0.195652,0.195652,0.971014,0.565217,...,0.579710,0.840580,0.608696,0.594203,0.405797,0.623188,0.195652,0.681159,0.521739,0.195652
2018,0.855072,0.166667,0.768116,0.565217,0.869565,0.166667,0.166667,0.166667,0.956522,0.405797,...,0.420290,0.884058,0.536232,0.333333,0.318841,0.594203,0.166667,0.739130,0.507246,0.166667
2019,0.840580,0.188406,0.521739,0.681159,0.942029,0.188406,0.188406,0.188406,1.000000,0.710145,...,0.289855,0.811594,0.507246,0.304348,0.318841,0.275362,0.188406,0.666667,0.594203,0.739130
2020,0.768116,0.159420,0.492754,0.724638,0.782609,0.159420,0.159420,0.159420,0.971014,0.652174,...,0.463768,0.956522,0.637681,0.318841,0.565217,0.579710,0.159420,0.536232,0.507246,0.260870
2021,0.710145,0.072464,0.536232,0.797101,0.753623,0.072464,0.072464,0.072464,0.971014,0.521739,...,0.550725,0.985507,0.347826,0.217391,0.811594,0.782609,0.362319,0.434783,0.463768,0.275362
2022,0.739130,0.101449,0.304348,0.637681,0.724638,0.101449,0.101449,0.101449,0.985507,0.608696,...,0.623188,0.826087,0.362319,0.594203,0.521739,0.695652,0.536232,0.420290,0.550725,0.391304
2023,0.811594,0.942029,0.463768,0.623188,0.782609,0.094203,0.094203,0.094203,0.985507,0.449275,...,0.333333,0.855072,0.391304,0.594203,0.159420,0.565217,0.739130,0.434783,0.579710,0.478261
2024,0.768116,0.782609,0.608696,0.202899,0.811594,0.094203,0.094203,0.094203,1.000000,0.376812,...,0.405797,0.942029,0.652174,0.681159,0.144928,0.507246,0.753623,0.391304,0.565217,0.536232
2025,0.855072,0.797101,0.188406,0.565217,0.782609,0.108696,0.108696,0.108696,0.971014,0.652174,...,0.260870,0.927536,0.710145,0.579710,0.014493,0.275362,0.405797,0.434783,0.637681,0.623188

In [27]:
score_todos_anos.iloc[1,0]

0.9130434782608695

## Hiperparâmetros

In [28]:
vb_cardinalidade_max = 40
vb_cardinalidade_min = 20
vb_peso_maximo = 0.20
vb_peso_minimo = 0.02
vb_theta = 0.30

### Fazendo otimização ano a ano e comparando com o proximo ano

In [130]:
anos = anos[::-1]

In [ ]:
y = []


for a in anos:
    y.append(a.split('-')[0])



print("=-"*48)
print("Anos totais: ",y)
print("=-"*48)

for an in anos:
    ano = an.split("-")[0]
    #deletar modelo
    if 'model' in locals():
        del model
        print('Modelo Antigo deletado \n Iniciando Novo')
    else:
        print("Nao consta model")
        pass

    print("-"*15)
    print("Começando Modelo do ano: ", ano)
    print("="*6)

    try:
        score_usado = score_todos_anos[score_todos_anos.index.isin([ano])]
        # print(score_usado)
        print("Score Atualizado")
        
        ano = int(an.split("-")[0])
        df_usado = f'df_ativos_{ano+1}'
        retorno_usado = pd.DataFrame(eval(df_usado))
        retorno_usado = retorno_usado[lista_ativos_finais]
        print("Retornos atualizados")
        print("-----")
    except Exception as e:
        print("ERRRRRRRRRRRROR")
        print(e)

    # if df_usado == 'df_ativos_2015':
    #     continue
    # else:
    print("# ------ CRIAÇÃO DO MODELO")
    print("## UTILIZANDO DADOS DE RETORNO DE: ",df_usado)
    print("## UTILIZANDO SCORE DO ANO DE: ",ano)

    model = pyo.ConcreteModel()

    #---------VARIÁVEIS-----------
    model.nome_ativos = pyo.Set(initialize = lista_ativos_finais)
    model.ativos = pyo.RangeSet(0, len(lista_ativos_finais)-1)
    model.dias = pyo.RangeSet(0, len(retorno_usado)-1)
    model.retornos_ativos = pyo.Param(model.dias, model.ativos, initialize=lambda model,dia, ativo: retorno_usado.iloc[dia, ativo])    
    model.theta = pyo.Param(initialize=vb_theta)
    model.score = pyo.Param(model.ativos, initialize=lambda model,a: score_usado.iloc[0,a])
    model.cardinalidade_valor_max = pyo.Param(initialize=vb_cardinalidade_max)
    model.cardinalidade_valor_min = pyo.Param(initialize=vb_cardinalidade_min)
    model.peso_maximo = pyo.Param(initialize=vb_peso_maximo)
    model.peso_minimo = pyo.Param(initialize=vb_peso_minimo)
    model.x = pyo.Var(model.ativos, bounds=(0,1))
    model.y = pyo.Var(model.ativos, within=pyo.Binary)
    model.excesso = pyo.Param(model.ativos , initialize = lambda model,a: exc_2016.mean().iloc[a])
    model.sigma = pyo.Param(model.ativos, model.ativos, initialize = lambda model,a,b: sigma_2016.iloc[a,b])
    model.s = pyo.Param(initialize = 0, mutable=True)
    model.r = pyo.Var(within=pyo.NonNegativeReals)
    
    print("+-="*30)

    ## OQ ESTÀ FALTANDO?
    ## FAZER O SIGMA PARA TODOS E EXCESSO PARA TODOS

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Anos totais:  ['2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Modelo Antigo deletado
 Iniciando Novo
---------------
Começando Modelo do ano:  2015
======
Score Atualizado
Retornos atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO DADOS DE RETORNO DE:  df_ativos_2016
## UTILIZANDO SCORE DO ANO DE:  2015
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
Modelo Antigo deletado
 Iniciando Novo
---------------
Começando Modelo do ano:  2016
======
Score Atualizado
Retornos atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO DADOS DE RETORNO DE:  df_ativos_2017
## UTILIZANDO SCORE DO ANO DE:  2016
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
Modelo Antigo deletado
 Iniciando Novo
---------------
Começando Modelo do ano:  2017
======
Score Atualizado
Retornos atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO DADOS DE RETORNO DE:  df_ativos_2018
## UTILIZANDO SCORE DO ANO DE:  2017
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
Modelo Antigo deletado
 Iniciando Novo
---------------
Começando Modelo do ano:  2018
======
Score Atualizado
Retornos atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO DADOS DE RETORNO DE:  df_ativos_2019
## UTILIZANDO SCORE DO ANO DE:  2018
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
Modelo Antigo deletado
 Iniciando Novo
---------------
Começando Modelo do ano:  2019
======
Score Atualizado
Retornos atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO DADOS DE RETORNO DE:  df_ativos_2020
## UTILIZANDO SCORE DO ANO DE:  2019
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
Modelo Antigo deletado
 Iniciando Novo
---------------
Começando Modelo do ano:  2020
======
Score Atualizado
Retornos atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO DADOS DE RETORNO DE:  df_ativos_2021
## UTILIZANDO SCORE DO ANO DE:  2020
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
Modelo Antigo deletado
 Iniciando Novo
---------------
Começando Modelo do ano:  2021
======
Score Atualizado
Retornos atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO DADOS DE RETORNO DE:  df_ativos_2022
## UTILIZANDO SCORE DO ANO DE:  2021
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
Modelo Antigo deletado
 Iniciando Novo
---------------
Começando Modelo do ano:  2022
======
Score Atualizado
Retornos atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO DADOS DE RETORNO DE:  df_ativos_2023
## UTILIZANDO SCORE DO ANO DE:  2022
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
Modelo Antigo deletado
 Iniciando Novo
---------------
Começando Modelo do ano:  2023
======
Score Atualizado
Retornos atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO DADOS DE RETORNO DE:  df_ativos_2024
## UTILIZANDO SCORE DO ANO DE:  2023
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
Modelo Antigo deletado
 Iniciando Novo
---------------
Começando Modelo do ano:  2024
======
Score Atualizado
Retornos atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO DADOS DE RETORNO DE:  df_ativos_2025
## UTILIZANDO SCORE DO ANO DE:  2024
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
Modelo Antigo deletado
 Iniciando Novo
---------------
Começando Modelo do ano:  2025
======
Score Atualizado
Retornos atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO DADOS DE RETORNO DE:  df_ativos_2026
## UTILIZANDO SCORE DO ANO DE:  2025
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=