In [1]:
import pandas as pd
import numpy as np
import random
import pyomo.environ as pyo
from pyomo.environ import *
from pyomo.environ import SolverFactory
import yfinance as yf
from pathlib import Path
import os
import matplotlib.pyplot as plt

In [2]:
anos = ['2025-12-31',
 '2024-12-31',
 '2023-12-31',
 '2022-12-31',
 '2021-12-31',
 '2020-12-31',
 '2019-12-31',
 '2018-12-31',
 '2017-12-31',
 '2016-12-31',
 '2015-12-31',
 ]

In [3]:
lista_macro = []

for filename in os.listdir(path='../../base_dados/brapi/macro'):
    
    # 2. Reconstruct the full absolute or relative path to the file
    full_path = os.path.join('../../base_dados/brapi/macro/',filename)
    
    # 3. Check if the current item is actually a file (and not a subfolder)
    # if os.path.isfile(full_path):
        
    #     # 4. Open and process the file safely
    #     with open(full_path, "r", encoding="utf-8") as file:
    #         content = file.read()
    #         print(f"--- Content of {filename} ---")
    #         print(pd.read_csv(full_path))
    dicio = {
        'macro':filename,
        'data':pd.read_csv(full_path)
    }

    lista_macro.append(dicio)

In [4]:
lista_macro[0]['data'].set_index('date', inplace=True)

In [5]:
lista_macro[0]['data'].describe().loc['std']['valor_anual']

np.float64(4.232295543007178)

In [6]:
selic_d = lista_macro[0]['data']

In [8]:
basedados_ativos = Path('../../base_dados/brapi/retornos/retornos.csv')
basedados_ibov = Path('../../base_dados/retorno_ibov_2015_2026.csv') 

lista_magic_formula = []

for filename in os.listdir(path='../../base_dados/brapi/magic_formula/'):
    
    # 2. Reconstruct the full absolute or relative path to the file
    full_path = os.path.join('../../base_dados/brapi/magic_formula/', filename)
    
    # 3. Check if the current item is actually a file (and not a subfolder)
    # if os.path.isfile(full_path):
        
    #     # 4. Open and process the file safely
    #     with open(full_path, "r", encoding="utf-8") as file:
    #         content = file.read()
    #         print(f"--- Content of {filename} ---")
    #         print(pd.read_csv(full_path))
    dicio = {
        'ativo':filename,
        'data':pd.read_csv(full_path)
    }

    lista_magic_formula.append(dicio)

df_ativos=pd.read_csv(basedados_ativos).set_index(['date']).fillna(0)

df_ibov=pd.read_csv(basedados_ibov).set_index(['Date']).fillna(0)

In [9]:
# lista_ativos=[]
# for ativo in df_ativos.columns.tolist():
#     lista_ativos.append(ativo.replace('.SA',''))
#     df_ativos.rename(columns={ativo:ativo.replace('.SA','')},inplace=True)

In [15]:
print(df_ativos.shape[0])
print(df_ibov.shape)

2863
(2849, 1)

In [12]:
print(f'tamanho mf original: ',len(lista_magic_formula))
lista_mf_check = []
lista_ativos_finais = []
for i in range(len(lista_magic_formula)):
    if lista_magic_formula[i]['ativo'] in df_ativos.columns.tolist():
        lista_ativos_finais.append(lista_magic_formula[i]['ativo'])
        dc = {
            'ativo':lista_magic_formula[i]['ativo'],
            'data':lista_magic_formula[i]['data']
        }
        lista_mf_check.append(dc)
    else:
        print(f"Nao está na lista: {lista_magic_formula[i]['ativo']}")
print(f'tamanho mf Final: ',len(lista_mf_check))

tamanho mf original:  78
tamanho mf Final:  78

In [13]:
lista_mf_check

[{'ativo': 'ABEV3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.903659  0.111531
  1            1  2024-12-31  0.624135  0.141094
  2            2  2023-12-31  0.840339  0.101218
  3            3  2022-12-31  0.646090  0.093623
  4            4  2021-12-31  0.585286  0.089962
  5            5  2020-12-31  0.598088  0.085787
  6            6  2019-12-31  0.637351  0.073615
  7            7  2018-12-31  0.824850  0.092799
  8            8  2017-12-31  1.105830  0.069359
  9            9  2016-12-31  1.198593  0.096538
  10          10  2015-12-31  1.084847  0.104877
  11          11  2014-12-31  1.081966  0.102054
  12          12  2013-12-31  0.892491  0.099119
  13          13  2012-12-31  0.762046  0.000204},
 {'ativo': 'ALOS3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.719754  0.069923
  1            1  2024-12-31  0.690710  0.089326
  2            2  2023-12-31  3.051214  0.259800
  3            3  2022-12-31  0.206836       NaN
  4            4  2021-12-31  0.456978       NaN
  5            5  2020-12-31  0.220283       NaN
  6            6  2019-12-31  0.193321       NaN
  7            7  2018-12-31  6.024537       NaN
  8            8  2017-12-31  1.949780       NaN
  9            9  2016-12-31  4.287691       NaN
  10          10  2015-12-31  3.291680       NaN
  11          11  2014-12-31  1.977544       NaN
  12          12  2013-12-31  2.104842       NaN
  13          13  2012-12-31  0.897487       NaN},
 {'ativo': 'ANIM3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.350509  0.160620
  1            1  2024-12-31  0.316663  0.146507
  2            2  2023-12-31  0.307917  0.078360
  3            3  2022-12-31  0.152021  0.056628
  4            4  2021-12-31  0.132547  0.030824
  5            5  2020-12-31  0.044681  0.025628
  6            6  2019-12-31  0.118241  0.053328
  7            7  2018-12-31  0.080797  0.045801
  8            8  2017-12-31  0.198252  0.086136
  9            9  2016-12-31  0.144083  0.076533
  10          10  2015-12-31  0.230685  0.127343
  11          11  2014-12-31  0.428206  0.144494
  12          12  2013-12-31  0.071255  0.146635
  13          13  2012-12-31  0.346405       NaN},
 {'ativo': 'AXIA3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.064941  0.014983
  1            1  2024-12-31  0.319325  0.122528
  2            2  2023-12-31  0.242834  0.068578
  3            3  2022-12-31  0.133297  0.039493
  4            4  2021-12-31  0.265099  0.107879
  5            5  2020-12-31  0.167610  0.074150
  6            6  2019-12-31  0.174593  0.071820
  7            7  2018-12-31  0.428382  0.151772
  8            8  2017-12-31  0.160349  0.044873
  9            9  2016-12-31  0.719660  0.155647
  10          10  2015-12-31 -0.406177 -0.154538
  11          11  2014-12-31 -0.046108 -0.026978
  12          12  2013-12-31 -0.119544 -0.106080
  13          13  2012-12-31 -0.130519 -0.113419},
 {'ativo': 'AZZA3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.215762  0.128598
  1            1  2024-12-31  0.082977  0.041399
  2            2  2023-12-31  0.369151  0.079842
  3            3  2022-12-31  0.382122  0.072475
  4            4  2021-12-31  0.881259  0.062808
  5            5  2020-12-31  0.094982  0.367190
  6            6  2019-12-31  0.272046  0.046478
  7            7  2018-12-31  0.285784  0.050134
  8            8  2017-12-31  0.306746  0.046652
  9            9  2016-12-31  0.262059  0.102043
  10          10  2015-12-31  0.261149  0.116814
  11          11  2014-12-31  0.287171  0.098323
  12          12  2013-12-31  0.310794  0.090454
  13          13  2012-12-31  0.286662  0.059698},
 {'ativo': 'B3SA3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.713721  0.060542
  1            1  2024-12-31  0.878188  0.074786
  2            2  2023-12-31  0.694163  0.050049
  3            3  2022-12-31  0.637924  0.076321
  4            4  2021-12-31  0.699233  0.104680
  5            5  2020-12-31  0.680557  0.056322
  6            6  2019-12-31  1.041395  0.142838
  7            7  2018-12-31  1.019145  0.146111
  8            8  2017-12-31  0.936325  0.096421
  9            9  2016-12-31  0.130038  0.188709
  10          10  2015-12-31  0.326941  0.988273
  11          11  2014-12-31  1.094273  0.233499
  12          12  2013-12-31  0.741219  0.348422
  13          13  2012-12-31  0.648707  0.265084},
 {'ativo': 'BBAS3',
  'data':     Unnamed: 0     endDate  ROC  EY
  0            0  2025-12-31  NaN NaN
  1            1  2024-12-31  NaN NaN
  2            2  2023-12-31  NaN NaN
  3            3  2022-12-31  NaN NaN
  4            4  2021-12-31  NaN NaN
  5            5  2020-12-31  NaN NaN
  6            6  2019-12-31  NaN NaN
  7            7  2018-12-31  NaN NaN
  8            8  2017-12-31  NaN NaN
  9            9  2016-12-31  NaN NaN
  10          10  2015-12-31  NaN NaN
  11          11  2014-12-31  NaN NaN
  12          12  2013-12-31  NaN NaN
  13          13  2012-12-31  NaN NaN},
 {'ativo': 'BBDC3',
  'data':     Unnamed: 0     endDate  ROC  EY
  0            0  2025-12-31  NaN NaN
  1            1  2024-12-31  NaN NaN
  2            2  2023-12-31  NaN NaN
  3            3  2022-12-31  NaN NaN
  4            4  2021-12-31  NaN NaN
  5            5  2020-12-31  NaN NaN
  6            6  2019-12-31  NaN NaN
  7            7  2018-12-31  NaN NaN
  8            8  2017-12-31  NaN NaN
  9            9  2016-12-31  NaN NaN
  10          10  2015-12-31  NaN NaN
  11          11  2014-12-31  NaN NaN
  12          12  2013-12-31  NaN NaN
  13          13  2012-12-31  NaN NaN},
 {'ativo': 'BBDC4',
  'data':     Unnamed: 0     endDate  ROC  EY
  0            0  2025-12-31  NaN NaN
  1            1  2024-12-31  NaN NaN
  2            2  2023-12-31  NaN NaN
  3            3  2022-12-31  NaN NaN
  4            4  2021-12-31  NaN NaN
  5            5  2020-12-31  NaN NaN
  6            6  2019-12-31  NaN NaN
  7            7  2018-12-31  NaN NaN
  8            8  2017-12-31  NaN NaN
  9            9  2016-12-31  NaN NaN
  10          10  2015-12-31  NaN NaN
  11          11  2014-12-31  NaN NaN
  12          12  2013-12-31  NaN NaN
  13          13  2012-12-31  NaN NaN},
 {'ativo': 'BBSE3',
  'data':     Unnamed: 0     endDate        ROC        EY
  0            0  2025-12-31   3.983830  0.166919
  1            1  2024-12-31   5.994063  0.177086
  2            2  2023-12-31  19.545107  0.176966
  3            3  2022-12-31   5.164468  0.086261
  4            4  2021-12-31   2.753881  0.125766
  5            5  2020-12-31   3.789294  0.080948
  6            6  2019-12-31  12.013021  0.171213
  7            7  2018-12-31   1.580919  0.099242
  8            8  2017-12-31   1.416078  0.108787
  9            9  2016-12-31  16.503715  0.098131
  10          10  2015-12-31 -20.061500  0.128590
  11          11  2014-12-31   1.271809  0.097588
  12          12  2013-12-31   1.403861  0.105026
  13          13  2012-12-31   0.000000       NaN},
 {'ativo': 'BEEF3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.240157  0.205351
  1            1  2024-12-31  0.145643  0.127028
  2            2  2023-12-31  0.145585  0.150818
  3            3  2022-12-31  0.240123  0.168552
  4            4  2021-12-31  0.183205  0.169824
  5            5  2020-12-31  0.199017  0.181278
  6            6  2019-12-31  0.233035  0.131980
  7            7  2018-12-31  0.117628  0.085907
  8            8  2017-12-31  0.143344  0.121648
  9            9  2016-12-31  0.176402  0.155370
  10          10  2015-12-31  0.226887  0.134997
  11          11  2014-12-31  0.144555  0.136146
  12          12  2013-12-31  0.163722  0.134071
  13          13  2012-12-31  0.169980  0.139286},
 {'ativo': 'BPAC11',
  'data':     Unnamed: 0     endDate  ROC  EY
  0            0  2025-12-31  NaN NaN
  1            1  2024-12-31  NaN NaN
  2            2  2023-12-31  NaN NaN
  3            3  2022-12-31  NaN NaN
  4            4  2021-12-31  NaN NaN
  5            5  2020-12-31  NaN NaN
  6            6  2019-12-31  NaN NaN
  7            7  2018-12-31  NaN NaN
  8            8  2017-12-31  NaN NaN
  9            9  2016-12-31  NaN NaN
  10          10  2015-12-31  NaN NaN
  11          11  2014-12-31  NaN NaN
  12          12  2013-12-31  NaN NaN
  13          13  2012-12-31  NaN NaN},
 {'ativo': 'BRAP4',
  'data':     Unnamed: 0     endDate        ROC        EY
  0            0  2025-12-31   2.162672  0.060438
  1            1  2024-12-31   4.723258  0.217542
  2            2  2023-12-31   9.610382  0.252545
  3            3  2022-12-31  55.274992  0.495016
  4            4  2021-12-31  32.760607  1.457539
  5            5  2020-12-31   3.841907  0.321432
  6            6  2019-12-31  -1.730019 -0.155033
  7            7  2018-12-31  11.545886  0.675647
  8            8  2017-12-31  -3.804793  1.342298
  9            9  2016-12-31   0.494947  0.637546
  10          10  2015-12-31  -7.205282 -1.492670
  11          11  2014-12-31  -0.216593  0.027943
  12          12  2013-12-31   0.018078  0.007128
  13          13  2012-12-31  -4.440988  0.189836},
 {'ativo': 'BRAV3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.115289  0.078124
  1            1  2024-12-31  0.134226  0.072084
  2            2  2023-12-31  0.186759  0.077443
  3            3  2022-12-31  0.093234  0.028632
  4            4  2021-12-31  0.134119  0.091781
  5            5  2020-12-31 -0.170792 -0.043180
  6            6  2019-12-31 -0.047091 -0.002175
  7            7  2018-12-31  0.152746       NaN
  8            8  2017-12-31  0.126629       NaN
  9            9  2016-12-31  0.057557       NaN
  10          10  2015-12-31 -0.095170       NaN
  11          11  2014-12-31  0.042049       NaN
  12          12  2013-12-31  0.058873       NaN
  13          13  2012-12-31  0.022440       NaN},
 {'ativo': 'BRKM5',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31 -0.057016 -0.029679
  1            1  2024-12-31 -0.020397 -0.014920
  2            2  2023-12-31 -0.050605 -0.043848
  3            3  2022-12-31  0.082173  0.067607
  4            4  2021-12-31  0.481351  0.275591
  5            5  2020-12-31 -0.001611 -0.001175
  6            6  2019-12-31 -0.001344 -0.000939
  7            7  2018-12-31  0.276543  0.154093
  8            8  2017-12-31  0.327055  0.185303
  9            9  2016-12-31  0.263859  0.142050
  10          10  2015-12-31  0.202776  0.139175
  11          11  2014-12-31  0.120259  0.101037
  12          12  2013-12-31  0.102175  0.081121
  13          13  2012-12-31  0.072533  0.062476},
 {'ativo': 'CMIG4',
  'data':     Unnamed: 0     endDate        ROC        EY
  0            0  2025-12-31   1.604456  0.120912
  1            1  2024-12-31   5.482017  0.207758
  2            2  2023-12-31   3.557296  0.188540
  3            3  2022-12-31   1.217974  0.150554
  4            4  2021-12-31   1.485031  0.165125
  5            5  2020-12-31   0.575826  0.101526
  6            6  2019-12-31   0.665097  0.064364
  7            7  2018-12-31   0.353323  0.060415
  8            8  2017-12-31   1.001925  0.091994
  9            9  2016-12-31   2.944315  0.059122
  10          10  2015-12-31  16.859418  0.163333
  11          11  2014-12-31   2.825974  0.173080
  12          12  2013-12-31   0.664545  0.187823
  13          13  2012-12-31   0.628747  0.110785},
 {'ativo': 'COGN3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.241949  0.078817
  1            1  2024-12-31  0.249333  0.134186
  2            2  2023-12-31  0.143974  0.042627
  3            3  2022-12-31  0.060067  0.020822
  4            4  2021-12-31  0.011072  0.005165
  5            5  2020-12-31 -0.387455 -0.153624
  6            6  2019-12-31  0.134106  0.030151
  7            7  2018-12-31  0.227030  0.054529
  8            8  2017-12-31  0.411082  0.067366
  9            9  2016-12-31  0.581904  0.097352
  10          10  2015-12-31  0.715407  0.101319
  11          11  2014-12-31  0.540251  0.047363
  12          12  2013-12-31  0.676364  0.213405
  13          13  2012-12-31  0.446927  0.117799},
 {'ativo': 'CPFE3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  1.362020  0.113894
  1            1  2024-12-31  1.212344  0.159409
  2            2  2023-12-31  1.255742  0.167953
  3            3  2022-12-31  0.937332  0.224368
  4            4  2021-12-31  0.650196  0.173718
  5            5  2020-12-31  0.623290  0.199395
  6            6  2019-12-31  0.503561  0.123973
  7            7  2018-12-31  0.387088  0.117210
  8            8  2017-12-31  0.417318  0.116727
  9            9  2016-12-31  0.234727  0.094231
  10          10  2015-12-31  0.203091  0.099585
  11          11  2014-12-31  0.243522  0.105820
  12          12  2013-12-31  0.247181  0.134955
  13          13  2012-12-31  0.275765  0.112416},
 {'ativo': 'CPLE3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.633406  0.082383
  1            1  2024-12-31  0.362358  0.095977
  2            2  2023-12-31  0.242567  0.087791
  3            3  2022-12-31  0.238252  0.081499
  4            4  2021-12-31  0.407867  0.177783
  5            5  2020-12-31  0.378119  0.152471
  6            6  2019-12-31  0.242533  0.213449
  7            7  2018-12-31  0.221192  0.164166
  8            8  2017-12-31  0.227290  0.162692
  9            9  2016-12-31  0.266116  0.182698
  10          10  2015-12-31  0.176132  0.209412
  11          11  2014-12-31  0.180619  0.206957
  12          12  2013-12-31  0.131622  0.205823
  13          13  2012-12-31  0.102899  0.235921},
 {'ativo': 'CSAN3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31 -0.003221 -0.001837
  1            1  2024-12-31  0.074639  0.039964
  2            2  2023-12-31  0.293982  0.132119
  3            3  2022-12-31  0.207619  0.084994
  4            4  2021-12-31  0.218889  0.105988
  5            5  2020-12-31  0.390649  0.051359
  6            6  2019-12-31  0.580379  0.200660
  7            7  2018-12-31  0.672507  0.178949
  8            8  2017-12-31  0.895553  0.187082
  9            9  2016-12-31  0.804935  0.208681
  10          10  2015-12-31  0.913121  0.139534
  11          11  2014-12-31  1.220118  0.109110
  12          12  2013-12-31  0.578900  0.084973
  13          13  2013-03-31  0.172102  0.085881},
 {'ativo': 'CSMG3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.819077  0.276762
  1            1  2024-12-31  0.807507  0.351270
  2            2  2023-12-31  0.778743  0.420532
  3            3  2022-12-31  0.630463  0.328156
  4            4  2021-12-31  0.398285  0.239091
  5            5  2020-12-31  0.599193  0.344388
  6            6  2019-12-31  0.498940  0.327504
  7            7  2018-12-31  0.420680  0.174097
  8            8  2017-12-31  0.431622  0.219424
  9            9  2016-12-31  1.093258  0.179977
  10          10  2015-12-31  0.531788  0.071964
  11          11  2014-12-31  1.632656  0.143535
  12          12  2013-12-31  1.834066  0.183586
  13          13  2012-12-31  1.306207  0.201944},
 {'ativo': 'CSNA3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.133148  0.075279
  1            1  2024-12-31  0.094689  0.071548
  2            2  2023-12-31  0.144124  0.086299
  3            3  2022-12-31  0.221442  0.159161
  4            4  2021-12-31  0.642640  0.506298
  5            5  2020-12-31  0.201378  0.103049
  6            6  2019-12-31  0.170229  0.084948
  7            7  2018-12-31  0.373014  0.193266
  8            8  2017-12-31  0.155607  0.083458
  9            9  2016-12-31  0.077558  0.053066
  10          10  2015-12-31  0.178682  0.166370
  11          11  2014-12-31  0.111841  0.078246
  12          12  2013-12-31  0.121159  0.078153
  13          13  2012-12-31  0.018270  0.021391},
 {'ativo': 'CVCB3',
  'data':     Unnamed: 0     endDate         ROC        EY
  0            0  2025-12-31   -0.506518  0.200681
  1            1  2024-12-31   -0.420804  0.090624
  2            2  2023-12-31    1.532260 -0.058859
  3            3  2022-12-31    0.034879 -0.023566
  4            4  2021-12-31    1.461406 -0.127747
  5            5  2020-12-31  134.654544 -0.261431
  6            6  2019-12-31    1.801281  0.050787
  7            7  2018-12-31    0.538576  0.088520
  8            8  2017-12-31    0.669332  0.107404
  9            9  2016-12-31    1.413645  0.223261
  10          10  2015-12-31    1.188374  0.335704
  11          11  2014-12-31    1.730626  0.400070
  12          12  2013-12-31    2.346995  0.306580
  13          13  2012-12-31    1.240952       NaN},
 {'ativo': 'CXSE3',
  'data':     Unnamed: 0     endDate        ROC        EY
  0            0  2025-12-31   5.444059  0.100541
  1            1  2024-12-31   5.039275  0.115759
  2            2  2023-12-31  79.945533  0.128667
  3            3  2022-12-31   3.909279  0.186909
  4            4  2021-12-31   2.494263  0.128704
  5            5  2020-12-31   3.745947       NaN
  6            6  2019-12-31   2.788075       NaN
  7            7  2018-12-31   3.177800       NaN
  8            8  2017-12-31   3.804848       NaN
  9            9  2016-12-31   3.696039       NaN
  10          10  2015-12-31  15.785824       NaN},
 {'ativo': 'CYRE3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.197256  0.116742
  1            1  2024-12-31  0.232447  0.192066
  2            2  2023-12-31  0.174204  0.104270
  3            3  2022-12-31  0.163248  0.123254
  4            4  2021-12-31  0.192460  0.154920
  5            5  2020-12-31  0.547699  0.227092
  6            6  2019-12-31  0.181189  0.066582
  7            7  2018-12-31  0.012172  0.010715
  8            8  2017-12-31  0.003738  0.003739
  9            9  2016-12-31  0.041770  0.053711
  10          10  2015-12-31  0.121427  0.190958
  11          11  2014-12-31  0.201924  0.189694
  12          12  2013-12-31  0.202062  0.158204
  13          13  2012-12-31  0.163917  0.140426},
 {'ativo': 'DIRR3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  0.210397  0.068090
  1            1  2024-12-31  0.229911  0.121855
  2            2  2023-12-31  0.159399  0.098259
  3            3  2022-12-31  0.187800  0.097764
  4            4  2021-12-31  0.131322  0.099467
  5            5  2020-12-31  0.101366  0.075901
  6            6  2019-12-31  0.100591  0.070669
  7            7  2018-12-31 -0.019841 -0.013280
  8            8  2017-12-31 -0.077348 -0.069000
  9            9  2016-12-31  0.001613  0.001839
  10          10  2015-12-31  0.088083  0.116446
  11          11  2014-12-31  0.123577  0.181963
  12          12  2013-12-31  0.143568  0.231289
  13          13  2012-12-31  0.126376  0.208104},
 {'ativo': 'ECOR3',
  'data':     Unnamed: 0     endDate       ROC        EY
  0            0  2025-12-31  1.540767  0.129799
  1            1  2024-12-31 -2.037011  0.154040
  2            2  2023-12-31  8.121280  0.121620
  3            3  2022-12-31 -1.831045  0.097680
  4            4  2021-12-31 -1.489404  0.101378
  5            5  2020-12-31 -2.580222  0.056664
  6            6  2019-12-31 -0.700526  0.048462
  7            7  2018-12-31  0.738529  0.107988
  8            8  2017-12-31  1.289815  0.117873
  9            9  2016-12-31  6.991145  0.094071
  10          10  2015-12-31  3.623429  0.133514
  11          11  2014-12-31  7.390354  0.136787
  12          12  2013-12-31  1.525591  0.121588
  13          13  2012-12-31  2.044897  0.115934},
 {'ativo': 'EGIE3',

In [16]:
df_ativos = df_ativos[df_ativos.index.isin(df_ibov.index)]
print(df_ativos.shape)

(2847, 78)

In [17]:
df_ibov = df_ibov[df_ibov.index.isin(df_ativos[df_ativos.index.isin(df_ibov.index)].index)]
print(df_ibov.shape)

(2847, 1)

In [18]:
df_ativos = df_ativos.filter(lista_ativos_finais)
print(len(df_ativos))

2847

In [19]:
#ativos
df_ativos_2015 = df_ativos[df_ativos.index.str.startswith('2015')]
df_ativos_2016 = df_ativos[df_ativos.index.str.startswith('2016')]
df_ativos_2017 = df_ativos[df_ativos.index.str.startswith('2017')]
df_ativos_2018 = df_ativos[df_ativos.index.str.startswith('2018')]
df_ativos_2019 = df_ativos[df_ativos.index.str.startswith('2019')]
df_ativos_2020 = df_ativos[df_ativos.index.str.startswith('2020')]
df_ativos_2021 = df_ativos[df_ativos.index.str.startswith('2021')]
df_ativos_2022 = df_ativos[df_ativos.index.str.startswith('2022')]
df_ativos_2023 = df_ativos[df_ativos.index.str.startswith('2023')]
df_ativos_2024 = df_ativos[df_ativos.index.str.startswith('2024')]
df_ativos_2025 = df_ativos[df_ativos.index.str.startswith('2025')]
df_ativos_2026 = df_ativos[df_ativos.index.str.startswith('2026')]

#ibov
df_ibov_2015 = df_ibov[df_ibov.index.str.startswith('2015')]
df_ibov_2016 = df_ibov[df_ibov.index.str.startswith('2016')]
df_ibov_2017 = df_ibov[df_ibov.index.str.startswith('2017')]
df_ibov_2018 = df_ibov[df_ibov.index.str.startswith('2018')]
df_ibov_2019 = df_ibov[df_ibov.index.str.startswith('2019')]
df_ibov_2020 = df_ibov[df_ibov.index.str.startswith('2020')]
df_ibov_2021 = df_ibov[df_ibov.index.str.startswith('2021')]
df_ibov_2022 = df_ibov[df_ibov.index.str.startswith('2022')]
df_ibov_2023 = df_ibov[df_ibov.index.str.startswith('2023')]
df_ibov_2024 = df_ibov[df_ibov.index.str.startswith('2024')]
df_ibov_2025 = df_ibov[df_ibov.index.str.startswith('2025')]
df_ibov_2026 = df_ibov[df_ibov.index.str.startswith('2026')]

In [20]:
selic_d_2016 = selic_d[selic_d.index.isin(df_ativos_2016.index)]
selic_d_2016['valor_diario'] = selic_d_2016['valor_diario']/100

In [21]:
df_ativos_2016

,ABEV3,ALOS3,ANIM3,AXIA3,AZZA3,B3SA3,BBAS3,BBDC3,BBDC4,BBSE3,...,TAEE11,TEND3,TOTS3,UGPA3,USIM5,VALE3,VBBR3,VIVT3,WEGE3,YDUQ3
date,,,,,,,,,,,,,,,,,,,,,
2016-01-04,-0.035857,0.0,-0.061592,-0.057285,-0.059519,-0.040421,-0.033928,-0.014629,-0.014515,-0.061646,...,-0.035836,0.0,-0.010953,-0.048801,-0.058083,-0.026085,0.0,-0.102648,-0.020728,0.0
2016-01-05,0.015689,0.0,-0.103491,0.022078,0.007087,0.038272,0.003523,0.007793,0.003637,0.063950,...,-0.015476,0.0,-0.004887,0.022957,-0.082191,-0.013400,0.0,0.001649,0.048486,0.0
2016-01-06,-0.009722,0.0,-0.043048,-0.018001,-0.014584,-0.000918,0.000000,-0.017706,-0.014186,-0.007825,...,0.003148,0.0,0.024886,-0.007139,-0.089551,-0.073484,0.0,0.001634,-0.022793,0.0
2016-01-07,-0.026577,0.0,0.008977,-0.049544,0.031124,-0.041487,-0.023790,-0.032033,-0.020222,-0.039423,...,-0.033222,0.0,-0.026207,-0.040240,-0.057385,-0.059489,0.0,-0.000324,-0.028658,0.0
2016-01-08,0.013059,0.0,-0.076707,-0.027028,0.013859,0.012497,0.000000,-0.002064,-0.019568,0.019005,...,0.042802,0.0,0.002299,0.016059,0.026059,-0.033909,0.0,-0.047958,-0.004820,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-12-23,0.011374,0.0,0.012770,0.015452,0.002058,0.028773,0.028466,0.023968,0.020928,0.005536,...,-0.007260,0.0,0.000426,-0.001213,-0.002512,-0.007483,0.0,0.012328,0.026989,0.0
2016-12-26,0.011255,0.0,-0.005930,0.020596,-0.014373,0.008878,0.015694,0.020484,0.018309,0.002934,...,-0.015609,0.0,0.002086,0.001519,0.012655,0.031760,0.0,0.007919,-0.008767,0.0
2016-12-27,-0.004325,0.0,0.020128,-0.017107,-0.000415,0.013874,0.007006,0.002505,-0.009704,-0.015366,...,0.005943,0.0,0.001671,0.005453,0.024994,-0.005000,0.0,-0.001398,0.016312,0.0
2016-12-28,0.007446,0.0,0.013171,0.014724,0.037512,0.024840,0.012432,0.023245,0.035947,0.040132,...,0.012312,0.0,0.007097,0.013262,-0.007309,0.031705,0.0,-0.003658,0.002668,0.0
2016-12-29,0.010471,0.0,-0.015886,0.003081,0.006834,0.000000,0.014437,0.018164,0.016469,0.011080,...,0.009257,0.0,-0.004141,0.017993,0.007363,-0.037481,0.0,0.027671,0.033346,0.0

## EXCESSO DOS ANOS e SIGMA (MAtriz de covariancia)

##### EXCESSO PARA TODOS

In [22]:
dict_sigma = {}
dict_excesso = {}
for an in anos:
    ano = an.split("-")[0]
    if ano == '2015':
        pass
    else:
        try:
            print(f"=============== \n EXCESSO {ano}\n ============")
            print("Atualização, Ano: ",ano)
            df = f'df_ativos_{ano}'
            df_f = pd.DataFrame(eval(df))
            slc = selic_d[selic_d.index.isin(df_f.index)]
            slc['valor_diario'] = slc['valor_diario']/100

            print(f"Tamanho DF de {ano}: ", len(df_f))
            print(f"Tamanho Selic: ", len(slc['valor_diario']))
            ano = int(ano)
            dict_excesso[ano] = df_f.sub(slc['valor_diario'],axis=0)
            print("tamanho final do Excesso: ",len(dict_excesso[ano]))

            print(f"============\n SIGMA {ano}\n===========")            
            dict_sigma[ano] = dict_excesso[ano].cov()
            print('Tamanho final do SIGMA: ',len(dict_sigma[ano]))

        except Exception as e:
            print(e)
            print("ERror")

===============
 EXCESSO 2025
 ============
Atualização, Ano:  2025
Tamanho DF de 2025:  250
Tamanho Selic:  250
tamanho final do Excesso:  250
============
 SIGMA 2025
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2024
 ============
Atualização, Ano:  2024
Tamanho DF de 2024:  251
Tamanho Selic:  251
tamanho final do Excesso:  251
============
 SIGMA 2024
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2023
 ============
Atualização, Ano:  2023
Tamanho DF de 2023:  248
Tamanho Selic:  248
tamanho final do Excesso:  248
============
 SIGMA 2023
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2022
 ============
Atualização, Ano:  2022
Tamanho DF de 2022:  250
Tamanho Selic:  250
tamanho final do Excesso:  250
============
 SIGMA 2022
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2021
 ============
Atualização, Ano:  2021
Tamanho DF de 2021:  247
Tamanho Selic:  247
tamanho final do Excesso:  247
============
 SIGMA 2021
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2020
 ============
Atualização, Ano:  2020
Tamanho DF de 2020:  248
Tamanho Selic:  248
tamanho final do Excesso:  248
============
 SIGMA 2020
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2019
 ============
Atualização, Ano:  2019
Tamanho DF de 2019:  248
Tamanho Selic:  248
tamanho final do Excesso:  248
============
 SIGMA 2019
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2018
 ============
Atualização, Ano:  2018
Tamanho DF de 2018:  245
Tamanho Selic:  245
tamanho final do Excesso:  245
============
 SIGMA 2018
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2017
 ============
Atualização, Ano:  2017
Tamanho DF de 2017:  246
Tamanho Selic:  246
tamanho final do Excesso:  246
============
 SIGMA 2017
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2016
 ============
Atualização, Ano:  2016
Tamanho DF de 2016:  249
Tamanho Selic:  249
tamanho final do Excesso:  249
============
 SIGMA 2016
===========
Tamanho final do SIGMA:  78

In [23]:
exc_2016 = df_ativos_2016.sub(selic_d_2016['valor_diario'], axis=0)
sharpe_2016 = exc_2016.mean() / df_ativos_2016.std()   # Series: index=ticker

#### Dados da Magic Formula (SCORE)

In [24]:


# y1 = []
# y2 = []
# for a in anos[:-1]:
#     y1.append(a)
# for a in anos[:-1]:
#     y2.append(a.split('-')[0])

# print("=-"*48)
# print("Anos totais: ",y)
# print("=-"*48)

dict_score_todos = []
dict_score = {}
for i, ativo in enumerate(df_ativos_2016.columns.tolist()):
        if ativo == lista_mf_check[i]['ativo']:
            for ano in anos:
                df_temp = lista_mf_check[i]['data'].query("endDate in @ano")
                score_anual = (0.5*df_temp['ROC'] + 0.5*df_temp['EY']).sum()
                dict_score[(ano, ativo)] = score_anual
                print("feito dict do ativo: ",ativo,ano,score_anual)
        else:
            print(f" ativo: {ativo}")
            print(f" ativo_mf: {lista_mf_check[i]['ativo']}")
df_scores = pd.Series(dict_score).unstack()  # index=anos, columns=ativos
df_scores = df_scores.replace([np.inf, -np.inf],0)    

dict_score_todos.append(df_scores)

feito dict do ativo:  ABEV3 2025-12-31 0.5075949601583762
feito dict do ativo:  ABEV3 2024-12-31 0.38261468462358406
feito dict do ativo:  ABEV3 2023-12-31 0.4707780476577104
feito dict do ativo:  ABEV3 2022-12-31 0.3698561983003272
feito dict do ativo:  ABEV3 2021-12-31 0.33762441702482754
feito dict do ativo:  ABEV3 2020-12-31 0.3419377467430017
feito dict do ativo:  ABEV3 2019-12-31 0.3554827706790753
feito dict do ativo:  ABEV3 2018-12-31 0.4588246122822893
feito dict do ativo:  ABEV3 2017-12-31 0.587594465523369
feito dict do ativo:  ABEV3 2016-12-31 0.6475658938442502
feito dict do ativo:  ABEV3 2015-12-31 0.5948621071274975
feito dict do ativo:  ALOS3 2025-12-31 0.39483852927400404
feito dict do ativo:  ALOS3 2024-12-31 0.3900179383466277
feito dict do ativo:  ALOS3 2023-12-31 1.655507111089378
feito dict do ativo:  ALOS3 2022-12-31 0.0
feito dict do ativo:  ALOS3 2021-12-31 0.0
feito dict do ativo:  ALOS3 2020-12-31 0.0
feito dict do ativo:  ALOS3 2019-12-31 0.0
feito dict do ativo:  ALOS3 2018-12-31 0.0
feito dict do ativo:  ALOS3 2017-12-31 0.0
feito dict do ativo:  ALOS3 2016-12-31 0.0
feito dict do ativo:  ALOS3 2015-12-31 0.0
feito dict do ativo:  ANIM3 2025-12-31 0.25556441820558945
feito dict do ativo:  ANIM3 2024-12-31 0.2315847506268863
feito dict do ativo:  ANIM3 2023-12-31 0.19313851144755478
feito dict do ativo:  ANIM3 2022-12-31 0.10432490005158955
feito dict do ativo:  ANIM3 2021-12-31 0.08168585984839365
feito dict do ativo:  ANIM3 2020-12-31 0.03515403521780015
feito dict do ativo:  ANIM3 2019-12-31 0.0857844752210383
feito dict do ativo:  ANIM3 2018-12-31 0.06329913189703734
feito dict do ativo:  ANIM3 2017-12-31 0.14219407565774464
feito dict do ativo:  ANIM3 2016-12-31 0.11030780677083571
feito dict do ativo:  ANIM3 2015-12-31 0.1790137437211763
feito dict do ativo:  AXIA3 2025-12-31 0.039962129224727354
feito dict do ativo:  AXIA3 2024-12-31 0.22092668246503305
feito dict do ativo:  AXIA3 2023-12-31 0.1557060662619637
feito dict do ativo:  AXIA3 2022-12-31 0.0863949979860275
feito dict do ativo:  AXIA3 2021-12-31 0.1864886904823606
feito dict do ativo:  AXIA3 2020-12-31 0.1208797499579457
feito dict do ativo:  AXIA3 2019-12-31 0.1232061008742997
feito dict do ativo:  AXIA3 2018-12-31 0.290077106731664
feito dict do ativo:  AXIA3 2017-12-31 0.10261123234047846
feito dict do ativo:  AXIA3 2016-12-31 0.43765344807392387
feito dict do ativo:  AXIA3 2015-12-31 -0.2803575070611428
feito dict do ativo:  AZZA3 2025-12-31 0.17218008546705044
feito dict do ativo:  AZZA3 2024-12-31 0.06218776601061185
feito dict do ativo:  AZZA3 2023-12-31 0.22449677141697774
feito dict do ativo:  AZZA3 2022-12-31 0.2272988550799676
feito dict do ativo:  AZZA3 2021-12-31 0.4720334772463487
feito dict do ativo:  AZZA3 2020-12-31 0.23108633624637676
feito dict do ativo:  AZZA3 2019-12-31 0.1592624048085601
feito dict do ativo:  AZZA3 2018-12-31 0.16795910877337916
feito dict do ativo:  AZZA3 2017-12-31 0.1766990358270806
feito dict do ativo:  AZZA3 2016-12-31 0.18205100122835866
feito dict do ativo:  AZZA3 2015-12-31 0.18898138992582925
feito dict do ativo:  B3SA3 2025-12-31 0.3871316068593503
feito dict do ativo:  B3SA3 2024-12-31 0.47648693738333525
feito dict do ativo:  B3SA3 2023-12-31 0.37210588171393993
feito dict do ativo:  B3SA3 2022-12-31 0.35712235330546893
feito dict do ativo:  B3SA3 2021-12-31 0.40195673910410157
feito dict do ativo:  B3SA3 2020-12-31 0.3684393689516793
feito dict do ativo:  B3SA3 2019-12-31 0.5921164504448382
feito dict do ativo:  B3SA3 2018-12-31 0.5826283083132008
feito dict do ativo:  B3SA3 2017-12-31 0.5163726248617743
feito dict do ativo:  B3SA3 2016-12-31 0.15937331695474855
feito dict do ativo:  B3SA3 2015-12-31 0.6576070804644214
feito dict do ativo:  BBAS3 2025-12-31 0.0
feito dict do ativo:  BBAS3 2024-12-31 0.0
feito dict do ativo:  BBAS3 2023-12-31 0.0
feito dict do ativo:  BBAS3 2022-12-31 0.0
feito dict do ativo:  BBAS3 2021-12-31 0.0
feito dict do ativo:  BBAS3 2020-12-31 0.0
feito dict do ativo:  BBAS3 2019-12-31 0.0
feito dict do ativo:  BBAS3 2018-12-31 0.0
feito dict do ativo:  BBAS3 2017-12-31 0.0
feito dict do ativo:  BBAS3 2016-12-31 0.0
feito dict do ativo:  BBAS3 2015-12-31 0.0
feito dict do ativo:  BBDC3 2025-12-31 0.0
feito dict do ativo:  BBDC3 2024-12-31 0.0
feito dict do ativo:  BBDC3 2023-12-31 0.0
feito dict do ativo:  BBDC3 2022-12-31 0.0
feito dict do ativo:  BBDC3 2021-12-31 0.0
feito dict do ativo:  BBDC3 2020-12-31 0.0
feito dict do ativo:  BBDC3 2019-12-31 0.0
feito dict do ativo:  BBDC3 2018-12-31 0.0
feito dict do ativo:  BBDC3 2017-12-31 0.0
feito dict do ativo:  BBDC3 2016-12-31 0.0
feito dict do ativo:  BBDC3 2015-12-31 0.0
feito dict do ativo:  BBDC4 2025-12-31 0.0
feito dict do ativo:  BBDC4 2024-12-31 0.0
feito dict do ativo:  BBDC4 2023-12-31 0.0
feito dict do ativo:  BBDC4 2022-12-31 0.0
feito dict do ativo:  BBDC4 2021-12-31 0.0
feito dict do ativo:  BBDC4 2020-12-31 0.0
feito dict do ativo:  BBDC4 2019-12-31 0.0
feito dict do ativo:  BBDC4 2018-12-31 0.0
feito dict do ativo:  BBDC4 2017-12-31 0.0
feito dict do ativo:  BBDC4 2016-12-31 0.0
feito dict do ativo:  BBDC4 2015-12-31 0.0
feito dict do ativo:  BBSE3 2025-12-31 2.0753745252427933
feito dict do ativo:  BBSE3 2024-12-31 3.0855741501961327
feito dict do ativo:  BBSE3 2023-12-31 9.861036597674278
feito dict do ativo:  BBSE3 2022-12-31 2.6253644354066994
feito dict do ativo:  BBSE3 2021-12-31 1.4398233272468384
feito dict do ativo:  BBSE3 2020-12-31 1.935120903212727
feito dict do ativo:  BBSE3 2019-12-31 6.092117050040411
feito dict do ativo:  BBSE3 2018-12-31 0.8400804469030312
feito dict do ativo:  BBSE3 2017-12-31 0.7624327120127663
feito dict do ativo:  BBSE3 2016-12-31 8.30092303025193
feito dict do ativo:  BBSE3 2015-12-31 -9.966454847066405
feito dict do ativo:  BEEF3 2025-12-31 0.22275440679253722
feito dict do ativo:  BEEF3 2024-12-31 0.13633540112736775
feito dict do ativo:  BEEF3 2023-12-31 0.14820141315943686
feito dict do ativo:  BEEF3 2022-12-31 0.2043372704006172
feito dict do ativo:  BEEF3 2021-12-31 0.17651429087779055
feito dict do ativo:  BEEF3 2020-12-31 0.19014773505291754
feito dict do ativo:  BEEF3 2019-12-31 0.18250741296224826
feito dict do ativo:  BEEF3 2018-12-31 0.10176736813008516
feito dict do ativo:  BEEF3 2017-12-31 0.1324959052603814
feito dict do ativo:  BEEF3 2016-12-31 0.16588602705558053
feito dict do ativo:  BEEF3 2015-12-31 0.18094207031617432
feito dict do ativo:  BPAC11 2025-12-31 0.0
feito dict do ativo:  BPAC11 2024-12-31 0.0
feito dict do ativo:  BPAC11 2023-12-31 0.0
feito dict do ativo:  BPAC11 2022-12-31 0.0
feito dict do ativo:  BPAC11 2021-12-31 0.0
feito dict do ativo:  BPAC11 2020-12-31 0.0
feito dict do ativo:  BPAC11 2019-12-31 0.0
feito dict do ativo:  BPAC11 2018-12-31 0.0
feito dict do ativo:  BPAC11 2017-12-31 0.0
feito dict do ativo:  BPAC11 2016-12-31 0.0
feito dict do ativo:  BPAC11 2015-12-31 0.0
feito dict do ativo:  BRAP4 2025-12-31 1.1115547745521173
feito dict do ativo:  BRAP4 2024-12-31 2.470400155061656
feito dict do ativo:  BRAP4 2023-12-31 4.9314635082254155
feito dict do ativo:  BRAP4 2022-12-31 27.885003709821877
feito dict do ativo:  BRAP4 2021-12-31 17.109073129045967
feito dict do ativo:  BRAP4 2020-12-31 2.081669631543931
feito dict do ativo:  BRAP4 2019-12-31 -0.9425256772583969
feito dict do ativo:  BRAP4 2018-12-31 6.11076669813114
feito dict do ativo:  BRAP4 2017-12-31 -1.2312475629507134
feito dict do ativo:  BRAP4 2016-12-31 0.5662464360829212
feito dict do ativo:  BRAP4 2015-12-31 -4.348975686122801
feito dict do ativo:  BRAV3 2025-12-31 0.09670670756210739
feito dict do ativo:  BRAV3 2024-12-31 0.10315509685417465
feito dict do ativo:  BRAV3 2023-12-31 0.13210103832562364
feito dict do ativo:  BRAV3 2022-12-31 0.0609329492365719
feito dict do ativo:  BRAV3 2021-12-31 0.11294971673935439
feito dict do ativo:  BRAV3 2020-12-31 -0.10698610540329315
feito dict do ativo:  BRAV3 2019-12-31 -0.024633228048453998
feito dict do ativo:  BRAV3 2018-12-31 0.0
feito dict do ativo:  BRAV3 2017-12-31 0.0
feito dict do ativo:  BRAV3 2016-12-31 0.0
feito dict do ativo:  BRAV3 2015-12-31 0.0
feito dict do ativo:  BRKM5 2025-12-31 -0.043347576370339355
feito dict do ativo:  BRKM5 2024-12-31 -0.0176583349095655
feito dict do ativo:  BRKM5 2023-12-31 -0.04722649246317315
feito dict do ativo:  BRKM5 2022-12-31 0.07489015457393375
feito dict do ativo:  BRKM5 2021-12-31 0.3784709101685788
feito dict do ativo:  BRKM5 2020-12-31 -0.0013925977254297
feito dict do ativo:  BRKM5 2019-12-31 -0.00114130278796935
feito dict do ativo:  BRKM5 2018-12-31 0.2153183979479587
feito dict do ativo:  BRKM5 2017-12-31 0.25617875678497726
feito dict do ativo:  BRKM5 2016-12-31 0.20295425819644397
feito dict do ativo:  BRKM5 2015-12-31 0.17097534309555756
feito dict do ativo:  CMIG4 2025-12-31 0.8626841659439108
feito dict do ativo:  CMIG4 2024-12-31 2.844887848588837
feito dict do ativo:  CMIG4 2023-12-31 1.8729180458767898
feito dict do ativo:  CMIG4 2022-12-31 0.68426398729129
feito dict do ativo:  CMIG4 2021-12-31 0.825078050778421
feito dict do ativo:  CMIG4 2020-12-31 0.3386757696184143
feito dict do ativo:  CMIG4 2019-12-31 0.36473050381709654
feito dict do ativo:  CMIG4 2018-12-31 0.2068687712060877
feito dict do ativo:  CMIG4 2017-12-31 0.5469594898561008
feito dict do ativo:  CMIG4 2016-12-31 1.5017182660490214
feito dict do ativo:  CMIG4 2015-12-31 8.511375272326474
feito dict do ativo:  COGN3 2025-12-31 0.160382984661286
feito dict do ativo:  COGN3 2024-12-31 0.19175931014917658
feito dict do ativo:  COGN3 2023-12-31 0.0933006072765408
feito dict do ativo:  COGN3 2022-12-31 0.040444870179164996
feito dict do ativo:  COGN3 2021-12-31 0.0081185190259437
feito dict do ativo:  COGN3 2020-12-31 -0.2705394405693553
feito dict do ativo:  COGN3 2019-12-31 0.08212873205164929
feito dict do ativo:  COGN3 2018-12-31 0.14077940687357124
feito dict do ativo:  COGN3 2017-12-31 0.2392239869670402
feito dict do ativo:  COGN3 2016-12-31 0.33962787614040924
feito dict do ativo:  COGN3 2015-12-31 0.40836301686297805
feito dict do ativo:  CPFE3 2025-12-31 0.7379570414139054
feito dict do ativo:  CPFE3 2024-12-31 0.6858768201181811
feito dict do ativo:  CPFE3 2023-12-31 0.7118476207094178
feito dict do ativo:  CPFE3 2022-12-31 0.5808498528572436
feito dict do ativo:  CPFE3 2021-12-31 0.41195689348773773
feito dict do ativo:  CPFE3 2020-12-31 0.4113422671021893
feito dict do ativo:  CPFE3 2019-12-31 0.3137668380536196
feito dict do ativo:  CPFE3 2018-12-31 0.25214856456309465
feito dict do ativo:  CPFE3 2017-12-31 0.2670224277973613
feito dict do ativo:  CPFE3 2016-12-31 0.16447922084585945
feito dict do ativo:  CPFE3 2015-12-31 0.1513381079195136
feito dict do ativo:  CPLE3 2025-12-31 0.35789450256311467
feito dict do ativo:  CPLE3 2024-12-31 0.2291673869379505
feito dict do ativo:  CPLE3 2023-12-31 0.16517927908959856
feito dict do ativo:  CPLE3 2022-12-31 0.15987544414130034
feito dict do ativo:  CPLE3 2021-12-31 0.29282512146893763
feito dict do ativo:  CPLE3 2020-12-31 0.26529498938133717
feito dict do ativo:  CPLE3 2019-12-31 0.22799071840074864
feito dict do ativo:  CPLE3 2018-12-31 0.19267884943132818
feito dict do ativo:  CPLE3 2017-12-31 0.1949907888140957
feito dict do ativo:  CPLE3 2016-12-31 0.22440674056690169
feito dict do ativo:  CPLE3 2015-12-31 0.1927719936905758
feito dict do ativo:  CSAN3 2025-12-31 -0.0025293839862629
feito dict do ativo:  CSAN3 2024-12-31 0.0573015365516788
feito dict do ativo:  CSAN3 2023-12-31 0.21305091256424308
feito dict do ativo:  CSAN3 2022-12-31 0.14630662167698355
feito dict do ativo:  CSAN3 2021-12-31 0.16243843022901594
feito dict do ativo:  CSAN3 2020-12-31 0.22100376033628427
feito dict do ativo:  CSAN3 2019-12-31 0.39051932811624757
feito dict do ativo:  CSAN3 2018-12-31 0.42572784281725534
feito dict do ativo:  CSAN3 2017-12-31 0.5413177063043684
feito dict do ativo:  CSAN3 2016-12-31 0.5068078801098811
feito dict do ativo:  CSAN3 2015-12-31 0.5263275525639541
feito dict do ativo:  CSMG3 2025-12-31 0.5479194663048437
feito dict do ativo:  CSMG3 2024-12-31 0.5793886658138119
feito dict do ativo:  CSMG3 2023-12-31 0.5996375551384604
feito dict do ativo:  CSMG3 2022-12-31 0.47930950646770676
feito dict do ativo:  CSMG3 2021-12-31 0.31868783205967305
feito dict do ativo:  CSMG3 2020-12-31 0.4717908885237141
feito dict do ativo:  CSMG3 2019-12-31 0.4132221592182493
feito dict do ativo:  CSMG3 2018-12-31 0.29738858607048674
feito dict do ativo:  CSMG3 2017-12-31 0.3255230027013085
feito dict do ativo:  CSMG3 2016-12-31 0.6366174479328897
feito dict do ativo:  CSMG3 2015-12-31 0.3018761372504819
feito dict do ativo:  CSNA3 2025-12-31 0.10421314474457105
feito dict do ativo:  CSNA3 2024-12-31 0.08311858202002076
feito dict do ativo:  CSNA3 2023-12-31 0.1152115456072879
feito dict do ativo:  CSNA3 2022-12-31 0.19030181619044956
feito dict do ativo:  CSNA3 2021-12-31 0.5744687901856544
feito dict do ativo:  CSNA3 2020-12-31 0.1522132774564707
feito dict do ativo:  CSNA3 2019-12-31 0.12758828999431354
feito dict do ativo:  CSNA3 2018-12-31 0.28314013998003795
feito dict do ativo:  CSNA3 2017-12-31 0.1195325585865499
feito dict do ativo:  CSNA3 2016-12-31 0.0653118156720241
feito dict do ativo:  CSNA3 2015-12-31 0.17252612028428405
feito dict do ativo:  CVCB3 2025-12-31 -0.1529183670567973
feito dict do ativo:  CVCB3 2024-12-31 -0.16508983905276875
feito dict do ativo:  CVCB3 2023-12-31 0.7367005376552359
feito dict do ativo:  CVCB3 2022-12-31 0.0056565594801244005
feito dict do ativo:  CVCB3 2021-12-31 0.6668295804326098
feito dict do ativo:  CVCB3 2020-12-31 67.19655614275372
feito dict do ativo:  CVCB3 2019-12-31 0.9260341406524867
feito dict do ativo:  CVCB3 2018-12-31 0.3135478478054663
feito dict do ativo:  CVCB3 2017-12-31 0.38836828510497734
feito dict do ativo:  CVCB3 2016-12-31 0.8184530406197279
feito dict do ativo:  CVCB3 2015-12-31 0.7620389883713105
feito dict do ativo:  CXSE3 2025-12-31 2.772299921179611
feito dict do ativo:  CXSE3 2024-12-31 2.5775170465658714
feito dict do ativo:  CXSE3 2023-12-31 40.037099613108
feito dict do ativo:  CXSE3 2022-12-31 2.048093884925602
feito dict do ativo:  CXSE3 2021-12-31 1.311483773266576
feito dict do ativo:  CXSE3 2020-12-31 0.0
feito dict do ativo:  CXSE3 2019-12-31 0.0
feito dict do ativo:  CXSE3 2018-12-31 0.0
feito dict do ativo:  CXSE3 2017-12-31 0.0
feito dict do ativo:  CXSE3 2016-12-31 0.0
feito dict do ativo:  CXSE3 2015-12-31 0.0
feito dict do ativo:  CYRE3 2025-12-31 0.15699893346053145
feito dict do ativo:  CYRE3 2024-12-31 0.21225672190064665
feito dict do ativo:  CYRE3 2023-12-31 0.13923710809772735
feito dict do ativo:  CYRE3 2022-12-31 0.14325086689577265
feito dict do ativo:  CYRE3 2021-12-31 0.1736900316190976
feito dict do ativo:  CYRE3 2020-12-31 0.3873952300276515
feito dict do ativo:  CYRE3 2019-12-31 0.12388522797166604
feito dict do ativo:  CYRE3 2018-12-31 0.011443327860161251
feito dict do ativo:  CYRE3 2017-12-31 0.0037388193928721497
feito dict do ativo:  CYRE3 2016-12-31 0.047740370361733606
feito dict do ativo:  CYRE3 2015-12-31 0.1561925750552557
feito dict do ativo:  DIRR3 2025-12-31 0.13924379506737972
feito dict do ativo:  DIRR3 2024-12-31 0.17588285608866405
feito dict do ativo:  DIRR3 2023-12-31 0.1288285553510129
feito dict do ativo:  DIRR3 2022-12-31 0.14278186924494204
feito dict do ativo:  DIRR3 2021-12-31 0.1153943474778473
feito dict do ativo:  DIRR3 2020-12-31 0.0886336841085626
feito dict do ativo:  DIRR3 2019-12-31 0.0856297976895462
feito dict do ativo:  DIRR3 2018-12-31 -0.016560063630435003
feito dict do ativo:  DIRR3 2017-12-31 -0.0731736560182017
feito dict do ativo:  DIRR3 2016-12-31 0.00172583002023155
feito dict do ativo:  DIRR3 2015-12-31 0.10226420399241795
feito dict do ativo:  ECOR3 2025-12-31 0.8352830945049519
feito dict do ativo:  ECOR3 2024-12-31 -0.9414852374675213
feito dict do ativo:  ECOR3 2023-12-31 4.121450096560701
feito dict do ativo:  ECOR3 2022-12-31 -0.8666825387976875
feito dict do ativo:  ECOR3 2021-12-31 -0.6940130009974979
feito dict do ativo:  ECOR3 2020-12-31 -1.2617791059088466
feito dict do ativo:  ECOR3 2019-12-31 -0.326032056926091
feito dict do ativo:  ECOR3 2018-12-31 0.4232582546317755
feito dict do ativo:  ECOR3 2017-12-31 0.7038440695804218
feito dict do ativo:  ECOR3 2016-12-31 3.54260755813794
feito dict do ativo:  ECOR3 2015-12-31 1.878471340145306
feito dict do ativo:  EGIE3 2025-12-31 0.1515636884512122
feito dict do ativo:  EGIE3 2024-12-31 0.2318604152646736
feito dict do ativo:  EGIE3 2023-12-31 0.2326977742868507
feito dict do ativo:  EGIE3 2022-12-31 0.2549522938841564
feito dict do ativo:  EGIE3 2021-12-31 0.20452187085221518
feito dict do ativo:  EGIE3 2020-12-31 0.2287038984861624
feito dict do ativo:  EGIE3 2019-12-31 0.1914167335362545
feito dict do ativo:  EGIE3 2018-12-31 0.19525417446394
feito dict do ativo:  EGIE3 2017-12-31 0.22410823789263096
feito dict do ativo:  EGIE3 2016-12-31 0.19161797811614767
feito dict do ativo:  EGIE3 2015-12-31 0.0
feito dict do ativo:  EMBJ3 2025-12-31 0.08790322762018729
feito dict do ativo:  EMBJ3 2024-12-31 0.10866436786702804
feito dict do ativo:  EMBJ3 2023-12-31 0.0660813094404554
feito dict do ativo:  EMBJ3 2022-12-31 -0.0254347561978699
feito dict do ativo:  EMBJ3 2021-12-31 0.0358962109384138
feito dict do ativo:  EMBJ3 2020-12-31 -0.0675349171217357
feito dict do ativo:  EMBJ3 2019-12-31 -0.05223143404972465
feito dict do ativo:  EMBJ3 2018-12-31 0.00459771020271305
feito dict do ativo:  EMBJ3 2017-12-31 0.05065194120107945
feito dict do ativo:  EMBJ3 2016-12-31 0.0388944667777467
feito dict do ativo:  EMBJ3 2015-12-31 0.04466140102486585
feito dict do ativo:  ENEV3 2025-12-31 0.07753649398038825
feito dict do ativo:  ENEV3 2024-12-31 0.05659396329661905
feito dict do ativo:  ENEV3 2023-12-31 0.07491636862725021
feito dict do ativo:  ENEV3 2022-12-31 0.039081243819630795
feito dict do ativo:  ENEV3 2021-12-31 0.0872476707476512
feito dict do ativo:  ENEV3 2020-12-31 0.06581649974501315
feito dict do ativo:  ENEV3 2019-12-31 0.11100104915802744
feito dict do ativo:  ENEV3 2018-12-31 0.1671082855331812
feito dict do ativo:  ENEV3 2017-12-31 0.1207768523930544
feito dict do ativo:  ENEV3 2016-12-31 0.09761025650010044
feito dict do ativo:  ENEV3 2015-12-31 0.0
feito dict do ativo:  ENGI11 2025-12-31 0.32819112485823226
feito dict do ativo:  ENGI11 2024-12-31 0.48514361516406695
feito dict do ativo:  ENGI11 2023-12-31 0.660354555532051
feito dict do ativo:  ENGI11 2022-12-31 0.8685242631704135
feito dict do ativo:  ENGI11 2021-12-31 0.5723668912578656
feito dict do ativo:  ENGI11 2020-12-31 0.8491293999071269
feito dict do ativo:  ENGI11 2019-12-31 0.4575928608511293
feito dict do ativo:  ENGI11 2018-12-31 0.4014454389039089
feito dict do ativo:  ENGI11 2017-12-31 0.4162803072483684
feito dict do ativo:  ENGI11 2016-12-31 0.39020324361118947
feito dict do ativo:  ENGI11 2015-12-31 0.35024098821493865
feito dict do ativo:  EQTL3 2025-12-31 0.2957582891286056
feito dict do ativo:  EQTL3 2024-12-31 0.3255291576987439
feito dict do ativo:  EQTL3 2023-12-31 0.25391995102083303
feito dict do ativo:  EQTL3 2022-12-31 0.5906827974019332
feito dict do ativo:  EQTL3 2021-12-31 0.3274545431442362
feito dict do ativo:  EQTL3 2020-12-31 0.46115157220678576
feito dict do ativo:  EQTL3 2019-12-31 0.4657468984992479
feito dict do ativo:  EQTL3 2018-12-31 0.4254815586645191
feito dict do ativo:  EQTL3 2017-12-31 0.30842465089472826
feito dict do ativo:  EQTL3 2016-12-31 0.3385728923131457
feito dict do ativo:  EQTL3 2015-12-31 0.28649569902524197
feito dict do ativo:  EZTC3 2025-12-31 0.1287255040303249
feito dict do ativo:  EZTC3 2024-12-31 0.14876338488092128
feito dict do ativo:  EZTC3 2023-12-31 0.0809668383420163
feito dict do ativo:  EZTC3 2022-12-31 0.13540297947818136
feito dict do ativo:  EZTC3 2021-12-31 0.1637927315487179
feito dict do ativo:  EZTC3 2020-12-31 0.10267570168542796

In [25]:
dict_score_todos[0].loc['2016-12-31'].rank(axis=0, pct=True)

ABEV3    0.897436
ALOS3    0.243590
ANIM3    0.538462
AXIA3    0.833333
AZZA3    0.666667
           ...
VALE3    0.551282
VBBR3    0.243590
VIVT3    0.730769
WEGE3    0.576923
YDUQ3    0.243590
Name: 2016-12-31, Length: 78, dtype: float64

In [26]:
score_todos_anos = dict_score_todos[0].rank(axis=1,pct=True)

In [27]:
score_todos_anos

,ABEV3,ALOS3,ANIM3,AXIA3,AZZA3,B3SA3,BBAS3,BBDC3,BBDC4,BBSE3,...,TAEE11,TEND3,TOTS3,UGPA3,USIM5,VALE3,VBBR3,VIVT3,WEGE3,YDUQ3
2015-12-31,0.884615,0.307692,0.641026,0.064103,0.692308,0.897436,0.307692,0.307692,0.307692,0.012821,...,0.948718,0.307692,0.769231,0.730769,0.051282,0.076923,0.307692,0.666667,0.564103,0.307692
2016-12-31,0.897436,0.243590,0.538462,0.833333,0.666667,0.602564,0.243590,0.243590,0.243590,1.000000,...,0.923077,0.243590,0.782051,0.679487,0.089744,0.551282,0.243590,0.730769,0.576923,0.243590
2017-12-31,0.910256,0.185897,0.551282,0.461538,0.628205,0.858974,0.185897,0.185897,0.185897,0.961538,...,0.820513,0.602564,0.576923,0.564103,0.371795,0.589744,0.185897,0.666667,0.474359,0.185897
2018-12-31,0.871795,0.173077,0.320513,0.756410,0.576923,0.884615,0.173077,0.173077,0.173077,0.961538,...,0.897436,0.538462,0.551282,0.346154,0.333333,0.602564,0.173077,0.730769,0.512821,0.173077
2019-12-31,0.833333,0.198718,0.448718,0.551282,0.679487,0.923077,0.198718,0.198718,0.198718,1.000000,...,0.807692,0.525641,0.512821,0.320513,0.333333,0.294872,0.198718,0.666667,0.602564,0.730769
2020-12-31,0.782051,0.179487,0.269231,0.525641,0.730769,0.794872,0.179487,0.179487,0.179487,0.961538,...,0.935897,0.500000,0.641026,0.358974,0.589744,0.602564,0.179487,0.564103,0.538462,0.307692
2021-12-31,0.717949,0.102564,0.269231,0.538462,0.794872,0.756410,0.102564,0.102564,0.102564,0.974359,...,0.987179,0.025641,0.384615,0.243590,0.807692,0.782051,0.410256,0.448718,0.487179,0.320513
2022-12-31,0.756410,0.115385,0.371795,0.307692,0.666667,0.743590,0.115385,0.115385,0.115385,0.987179,...,0.833333,0.025641,0.384615,0.615385,0.538462,0.717949,0.551282,0.448718,0.564103,0.410256
2023-12-31,0.794872,0.935897,0.538462,0.448718,0.628205,0.769231,0.096154,0.096154,0.096154,0.987179,...,0.833333,0.166667,0.384615,0.589744,0.179487,0.564103,0.730769,0.423077,0.576923,0.461538
2024-12-31,0.782051,0.794872,0.641026,0.615385,0.217949,0.820513,0.108974,0.108974,0.108974,1.000000,...,0.948718,0.435897,0.679487,0.705128,0.166667,0.538462,0.769231,0.371795,0.589744,0.564103
2025-12-31,0.846154,0.794872,0.705128,0.192308,0.551282,0.782051,0.108974,0.108974,0.108974,0.974359,...,0.935897,0.525641,0.692308,0.576923,0.025641,0.282051,0.397436,0.423077,0.628205,0.615385

In [28]:
index_novo = []
for indexx in score_todos_anos.index:
    novo = indexx.split('-')[0]
    index_novo.append(novo)
print(index_novo)

['2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

In [29]:
score_todos_anos.index=  index_novo

In [30]:
score_todos_anos

,ABEV3,ALOS3,ANIM3,AXIA3,AZZA3,B3SA3,BBAS3,BBDC3,BBDC4,BBSE3,...,TAEE11,TEND3,TOTS3,UGPA3,USIM5,VALE3,VBBR3,VIVT3,WEGE3,YDUQ3
2015,0.884615,0.307692,0.641026,0.064103,0.692308,0.897436,0.307692,0.307692,0.307692,0.012821,...,0.948718,0.307692,0.769231,0.730769,0.051282,0.076923,0.307692,0.666667,0.564103,0.307692
2016,0.897436,0.243590,0.538462,0.833333,0.666667,0.602564,0.243590,0.243590,0.243590,1.000000,...,0.923077,0.243590,0.782051,0.679487,0.089744,0.551282,0.243590,0.730769,0.576923,0.243590
2017,0.910256,0.185897,0.551282,0.461538,0.628205,0.858974,0.185897,0.185897,0.185897,0.961538,...,0.820513,0.602564,0.576923,0.564103,0.371795,0.589744,0.185897,0.666667,0.474359,0.185897
2018,0.871795,0.173077,0.320513,0.756410,0.576923,0.884615,0.173077,0.173077,0.173077,0.961538,...,0.897436,0.538462,0.551282,0.346154,0.333333,0.602564,0.173077,0.730769,0.512821,0.173077
2019,0.833333,0.198718,0.448718,0.551282,0.679487,0.923077,0.198718,0.198718,0.198718,1.000000,...,0.807692,0.525641,0.512821,0.320513,0.333333,0.294872,0.198718,0.666667,0.602564,0.730769
2020,0.782051,0.179487,0.269231,0.525641,0.730769,0.794872,0.179487,0.179487,0.179487,0.961538,...,0.935897,0.500000,0.641026,0.358974,0.589744,0.602564,0.179487,0.564103,0.538462,0.307692
2021,0.717949,0.102564,0.269231,0.538462,0.794872,0.756410,0.102564,0.102564,0.102564,0.974359,...,0.987179,0.025641,0.384615,0.243590,0.807692,0.782051,0.410256,0.448718,0.487179,0.320513
2022,0.756410,0.115385,0.371795,0.307692,0.666667,0.743590,0.115385,0.115385,0.115385,0.987179,...,0.833333,0.025641,0.384615,0.615385,0.538462,0.717949,0.551282,0.448718,0.564103,0.410256
2023,0.794872,0.935897,0.538462,0.448718,0.628205,0.769231,0.096154,0.096154,0.096154,0.987179,...,0.833333,0.166667,0.384615,0.589744,0.179487,0.564103,0.730769,0.423077,0.576923,0.461538
2024,0.782051,0.794872,0.641026,0.615385,0.217949,0.820513,0.108974,0.108974,0.108974,1.000000,...,0.948718,0.435897,0.679487,0.705128,0.166667,0.538462,0.769231,0.371795,0.589744,0.564103
2025,0.846154,0.794872,0.705128,0.192308,0.551282,0.782051,0.108974,0.108974,0.108974,0.974359,...,0.935897,0.525641,0.692308,0.576923,0.025641,0.282051,0.397436,0.423077,0.628205,0.615385

## Hiperparâmetros

In [31]:
vb_cardinalidade_max = 20
vb_cardinalidade_min = 20
vb_peso_maximo = 0.15
vb_peso_minimo = 0.02
vb_theta = 0.30

### Fazendo otimização ano a ano e comparando com o proximo ano

In [36]:
anos = anos[::-1]
print(anos)

['2015-12-31', '2016-12-31', '2017-12-31', '2018-12-31', '2019-12-31', '2020-12-31', '2021-12-31', '2022-12-31', '2023-12-31', '2024-12-31', '2025-12-31']

In [38]:
from pydoc import text


y = []

carteiras_anuais = {}

melhor_pesos = None
historico = []
carteiras_criadas = []
for a in anos:
    y.append(a.split('-')[0])



print("=-"*48)
print("Anos totais: ",y)
print("=-"*48)

for an in anos:
    ano = an.split("-")[0]
    print("COMEÇANDO ANO NOVO: ",ano)
    #deletar modelo
    if 'model' in locals():
        del model
        print('Modelo Antigo deletado \n Iniciando Novo')
    else:
        print("Nao consta model")
        pass

    print("-"*15)
    print("Começando Modelo do ano: ", ano)
    print("="*6)

    try:
        score_usado = score_todos_anos[score_todos_anos.index.isin([ano])]
        # print(score_usado)
        print("Score Atualizado")
        

        ano_um = int(ano)+1
        df_usado = f'df_ativos_{ano_um}'
        retorno_usado = pd.DataFrame(eval(df_usado))
        retorno_usado = retorno_usado[lista_ativos_finais]
        print("Retornos atualizados")

        excesso_usado = dict_excesso[ano_um]
        print("Excessos Atualizados")
        
        sigma_usado = dict_sigma[ano_um]
        print("Sigmas Atualizados")
        
        print("-----")
    except Exception as e:
        print("ERRRRRRRRRRRROR")
        print(e)

    # if df_usado == 'df_ativos_2015':
    #     continue
    # else:
    print("# ------ CRIAÇÃO DO MODELO")
    print("## UTILIZANDO SCORE DO ANO DE: ",ano)
    print("## UTILIZANDO DADOS DE RETORNO DE: ",df_usado)
    print("## UTILIZANDO EXCESSO DO ANO DE: ",ano_um)
    print("## UTILIZANDO SIGMAS DO ANO DE: ",ano_um)

    model = pyo.ConcreteModel()

    #---------VARIÁVEIS-----------
    model.nome_ativos = pyo.Set(initialize = lista_ativos_finais)
    model.ativos = pyo.RangeSet(0, len(lista_ativos_finais)-1)
    model.dias = pyo.RangeSet(0, len(retorno_usado)-1)
    model.retornos_ativos = pyo.Param(model.dias, model.ativos, initialize=lambda model,dia, ativo: retorno_usado.iloc[dia, ativo])    
    model.theta = pyo.Param(initialize=vb_theta)
    model.score = pyo.Param(model.ativos, initialize=lambda model,a: score_usado.iloc[0,a])
    model.cardinalidade_valor_max = pyo.Param(initialize=vb_cardinalidade_max)
    model.cardinalidade_valor_min = pyo.Param(initialize=vb_cardinalidade_min)
    model.peso_maximo = pyo.Param(initialize=vb_peso_maximo)
    model.peso_minimo = pyo.Param(initialize=vb_peso_minimo)
    model.x = pyo.Var(model.ativos, bounds=(0,1))
    model.y = pyo.Var(model.ativos, within=pyo.Binary)
    model.excesso = pyo.Param( model.ativos , initialize = lambda model,a: excesso_usado.mean().iloc[a])
    model.sigma = pyo.Param(model.ativos, model.ativos, initialize = lambda model,a,b: sigma_usado.iloc[a,b])
    model.s = pyo.Param(initialize = 2, mutable=True)
    model.r = pyo.Var(within=pyo.NonNegativeReals)
    
    #-------------------------------------- FUNÇÕES

    #=============================
    # Função Objetivo
    #=============================

    def func_objetivo_1(model):
        retorno_esperado = model.theta * sum(
            model.retornos_ativos[dia, a] * model.x[a] for a in model.ativos for dia in model.dias
        )
        # retorno_esperado = model.theta * model.r
        # A dúvida de qual retorno usar (Retorno BRUTO ou Excesso (retorno - selic))

        score_total = (1 - model.theta) * sum(
            model.x[a] * model.score[a] for a in model.ativos
        )
        return retorno_esperado + score_total
    model.obj1 = pyo.Objective(rule=func_objetivo_1, sense=pyo.maximize)

    #=============================
    # RESTRIÇÕES
    #=============================

    def def_r(model):
        return model.r == sum(model.excesso[a]*model.x[a]for a in model.ativos)
    model.const_def_r = pyo.Constraint(rule=def_r)

    ## modelos de Programação de Cone de Segunda Ordem (SOCP) 
    ## e Programação Quadrática com Restrições (QCP)
    def cone(model):
        return model.r**2 >= model.s**2 * sum(model.x[a]*model.sigma[a,b]*model.x[b] for a in model.ativos for b in model.ativos)
    model.constr_cone = pyo.Constraint(rule=cone)

    #REstricao 1 x só ativa se y = 1
    def restr_vinculo_x_y(model, a):
        return model.x[a] <= model.y[a]
    model.const_restr_vinculo_x_y = pyo.Constraint(model.ativos, rule=restr_vinculo_x_y)

    #peso maximo por acao
    def rule_peso_maximo(model, a):
        # return model.x[a] <= 1/model.cardinalidade_valor
        return model.x[a] <= model.peso_maximo
    model.const_peso_maximo = pyo.Constraint(model.ativos, rule=rule_peso_maximo)

    #peso minimo por acao
    def rule_peso_minimo(model, a):
        return model.x[a] >= model.peso_minimo * model.y[a]  # se y=1, então x >= 0.05
    model.const_peso_minimo = pyo.Constraint(model.ativos, rule=rule_peso_minimo)

    #Restrição 2 soma peso 1
    def soma_peso_1(model):
        return sum(model.x[a] for a in model.ativos) == 1
    model.const_soma_peso_1 = pyo.Constraint(rule=soma_peso_1)


    def cardinalidade_min(model):
        return sum(
            model.y[a] for a in model.ativos
            ) >= model.cardinalidade_valor_min
    model.const_cardinalidade_total_min = pyo.Constraint(rule=cardinalidade_min)

    def cardinalidade_max(model):
        return sum(
            model.y[a] for a in model.ativos
            ) <= model.cardinalidade_valor_max
    model.const_cardinalidade_total_max = pyo.Constraint(rule=cardinalidade_max)


    # NOTEBOOOK
    # opt = SolverFactory('cplex', executable='C:\\CPLEX_Studio2211\\cplex\\bin\\x64_win64\\cplex.exe')

    # PC
    opt = SolverFactory('cplex', executable='C:\\Program Files\\IBM\\ILOG\\CPLEX_Studio_Community222\\cplex\\bin\\x64_win64\\cplex.exe')

    s_lo = 0.01        # <-- o Sharpe DIÁRIO 
    s_hi = 1   # teto: 2x o melhor ativo individual
    tol  = 0.001
    print("MODEL.S.VALUE => ",model.s.value)
    melhor_pesos = None
    historico = []
    carteiras_criadas = []
    # print(f"Valor a ser batido com S_LO: {s_lo} e S_HI: {s_hi} ... Diferença: {s_hi-s_lo}")
    print(f"Começando o WHILE do ano {ano}")
    while s_hi - s_lo > tol:
        s_a_ser_usado = 0.5 * (s_lo + s_hi)
        # print(s_a_ser_usado)
        model.s.value = s_a_ser_usado
        print("="*18)
        # print("Objetivo: (É o S lá da restrição de sharpe): ",s_a_ser_usado)
        res = opt.solve(model, load_solutions=False, tee=False)
        tc = res.solver.termination_condition
        print(f"Modelo Resolveu....Condição: ",tc)
        if tc == pyo.TerminationCondition.optimal:
            model.solutions.load_from(res)
            melhor_pesos = {a: pyo.value(model.x[a]) for a in model.ativos}
            # print({x:i for x,i in melhor_pesos.items() if i>0})
            s_lo = model.s.value
            print(f"Valor encontrado para o Sharpe: ",s_lo)
            # print(f"Valor FO: ",pyo.value(model.obj1))
            # print(f"Atualização de Valores para próxima rodagem: TC {tc} com S_LO: {s_lo} e S_HI: {s_hi} ... Diferença: {s_hi-s_lo}")
            # print("="*28)
            # for x,i in melhor_pesos.items():
            #     if i>0:

            #         dc = {
            #         'ativos_selecionados':melhor_pesos,
            #         'sharpe':pyo.value(model.s),
            #             }
            historico.append((s_a_ser_usado, 'viavel'))
            # carteiras_criadas.append(dc)
        elif tc in (pyo.TerminationCondition.infeasible,
                    pyo.TerminationCondition.infeasibleOrUnbounded):
            s_hi = s_a_ser_usado
            print(f"Atualização do S_HI : {s_hi}")
            print("="*28)

            historico.append((s_a_ser_usado, 'inviavel'))
        else:
            print(f'status inesperado em s={s_a_ser_usado:.4f}: {tc}')
            pass
    print("SAIU DO WHILE")
    print(f'Sharpe máximo (diário) ≈ {s_a_ser_usado:.4f}  |  anualizado ≈ {s_a_ser_usado*np.sqrt(252):.2f}')
    # print(historico)
    carteiras_anuais[int(ano)] = {
        'pesos':  melhor_pesos,
        'sharpe_anual': s_lo*np.sqrt(252),
    }
    print(f"{ano} -> {melhor_pesos}")
    print("+-="*30)
    if 'model' in locals():
        del model
        print('DELETADO DPS DO WHILE')
    else:
        print("Nao consta model")
        pass

    ## OQ ESTÀ FALTANDO?
    ## FAZER O SIGMA PARA TODOS

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Anos totais:  ['2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
COMEÇANDO ANO NOVO:  2015
Modelo Antigo deletado
 Iniciando Novo
---------------
Começando Modelo do ano:  2015
======
Score Atualizado
Retornos atualizados
Excessos Atualizados
Sigmas Atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO SCORE DO ANO DE:  2015
## UTILIZANDO DADOS DE RETORNO DE:  df_ativos_2016
## UTILIZANDO EXCESSO DO ANO DE:  2016
## UTILIZANDO SIGMAS DO ANO DE:  2016
MODEL.S.VALUE =>  2
Começando o WHILE do ano 2015
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.505
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.2575
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.38125
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.31937499999999996
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.2884375
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.27296875
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.280703125
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.2845703125
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.28263671874999996
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.28166992187499995
============================
SAIU DO WHILE
Sharpe máximo (diário) ≈ 0.2817  |  anualizado ≈ 4.47
2015 -> {0: 0.0, 1: 0.020000010405344763, 2: 0.0, 3: 0.10898229009347347, 4: 0.0, 5: 0.0, 6: 0.0, 7: 0.0, 8: 0.0, 9: 0.0, 10: 0.0, 11: 0.0, 12: 0.020000007412741116, 13: 0.0, 14: 0.0, 15: 0.0, 16: 0.0, 17: 0.020000037388439012, 18: 0.0, 19: 0.0, 20: 0.09782814079935771, 21: 0.0, 22: 0.0, 23: 0.02, 24: 0.0, 25: 0.0, 26: 0.0, 27: 0.0, 28: 0.0, 29: 0.0, 30: 0.10798867112242323, 31: 0.0, 32: 0.0, 33: 0.14999999543572304, 34: 0.0, 35: 0.0, 36: 0.0, 37: 0.02, 38: 0.02, 39: 0.0, 40: 0.0, 41: 0.0, 42: 0.0, 43: 0.0, 44: 0.0, 45: 0.0, 46: 0.02, 47: 0.10520092266857674, 48: 0.0, 49: 0.02, 50: 0.0, 51: 0.0, 52: 0.0, 53: 0.0, 54: 0.020000010823238434, 55: 0.0, 56: 0.0, 57: 0.14999989893711208, 58: 0.0, 59: 0.0, 60: 0.0, 61: 0.0, 62: 0.0, 63: 0.0, 64: 0.0, 65: 0.02, 66: 0.020000010137187583, 67: 0.0, 68: 0.0, 69: 0.02, 70: 0.0, 71: 0.0, 72: 0.0, 73: 0.0, 74: 0.02, 75: 0.0, 76: 0.0, 77: 0.020000010407959855}
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
DELETADO DPS DO WHILE
COMEÇANDO ANO NOVO:  2016
Nao consta model
---------------
Começando Modelo do ano:  2016
======
Score Atualizado
Retornos atualizados
Excessos Atualizados
Sigmas Atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO SCORE DO ANO DE:  2016
## UTILIZANDO DADOS DE RETORNO DE:  df_ativos_2017
## UTILIZANDO EXCESSO DO ANO DE:  2017
## UTILIZANDO SIGMAS DO ANO DE:  2017
MODEL.S.VALUE =>  2
Começando o WHILE do ano 2016
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.505
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.2575
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.38125
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.31937499999999996
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.35031249999999997
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.33484375
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.327109375
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.3232421875
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.32130859375
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.322275390625
SAIU DO WHILE
Sharpe máximo (diário) ≈ 0.3223  |  anualizado ≈ 5.12
2016 -> {0: 0.0, 1: 0.0, 2: 0.06754428034093454, 3: 1.052145323650744e-09, 4: 0.031608010846826746, 5: 6.851445051348125e-09, 6: 1.209168333051941e-09, 7: 1.7414970067749388e-09, 8: 2.017835915023981e-09, 9: 2.252297384326278e-09, 10: 7.235366044921168e-09, 11: 3.300147805784562e-09, 12: 0.0, 13: 0.019999948079157375, 14: 8.351180265403422e-09, 15: 1.0634435801206588e-09, 16: 3.2505155203562195e-09, 17: 2.6442939452729116e-09, 18: 2.2865016026287155e-09, 19: 2.1655072845541456e-09, 20: 5.07194840715367e-09, 21: 7.711406810236624e-10, 22: 0.08189000679144562, 23: 0.019999948079157375, 24: 1.752277417037879e-09, 25: 1.6184864035419017e-09, 26: 3.960358819063915e-09, 27: 4.6371165711395844e-09, 28: 1.7847115027813367e-07, 29: 0.0, 30: 0.02000002619991728, 31: 9.005833305698346e-09, 32: 5.309468134044078e-09, 33: 0.04833983489834474, 34: 1.7038470927151454e-09, 35: 1.3522013652091166e-09, 36: 3.9872441498144285e-08, 37: 0.019999948079157375, 38: 0.11043650244873764, 39: 8.337340489195724e-09, 40: 4.197640224821944e-09, 41: 4.422324032214694e-09, 42: 2.8259774385272657e-09, 43: 1.7073725276955966e-09, 44: 3.505751304696052e-09, 45: 5.1122047648823826e-09, 46: 0.019999948079157375, 47: 0.0, 48: 1.400143184423565e-09, 49: 2.641426686115561e-09, 50: 4.680515801278718e-09, 51: 2.4346090272768475e-09, 52: 1.339734151042325e-09, 53: 1.3179837484631296e-09, 54: 5.3501354573326005e-09, 55: 0.149999977925695, 56: 0.02000000392701874, 57: 0.019999992470579292, 58: 4.290424139767543e-09, 59: 2.892085509798182e-09, 60: 0.06504190071744884, 61: 1.4720347689439537e-09, 62: 1.539809267412637e-08, 63: 3.008195563041231e-09, 64: 0.11428050046663966, 65: 0.019999948079157375, 66: 3.4473355379505734e-09, 67: 0.11085882730125977, 68: 8.453230374940875e-09, 69: 5.237563314442344e-09, 70: 8.583949677941763e-08, 71: 4.972149833377169e-09, 72: 4.991974273653317e-09, 73: 1.895438293376485e-08, 74: 0.019999948079157375, 75: 1.622735416638698e-08, 76: 0.020000003240238318, 77: 0.019999948079157375}
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
DELETADO DPS DO WHILE
COMEÇANDO ANO NOVO:  2017
Nao consta model
---------------
Começando Modelo do ano:  2017
======
Score Atualizado
Retornos atualizados
Excessos Atualizados
Sigmas Atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO SCORE DO ANO DE:  2017
## UTILIZANDO DADOS DE RETORNO DE:  df_ativos_2018
## UTILIZANDO EXCESSO DO ANO DE:  2018
## UTILIZANDO SIGMAS DO ANO DE:  2018
MODEL.S.VALUE =>  2
Começando o WHILE do ano 2017
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.505
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.2575
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.38125
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.31937499999999996
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.2884375
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.27296875
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.280703125
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.2768359375
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.27490234375
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.275869140625
SAIU DO WHILE
Sharpe máximo (diário) ≈ 0.2759  |  anualizado ≈ 4.38
2017 -> {0: 0.0, 1: 0.020000314383101545, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0, 6: 0.0, 7: 0.0, 8: 0.0, 9: 0.0, 10: 0.0, 11: 0.0, 12: 0.0, 13: 0.020191687387314163, 14: 0.0, 15: 0.03344578141839684, 16: 0.0, 17: 0.06535774641868049, 18: 0.02000000086749556, 19: 0.0, 20: 0.0, 21: 0.0, 22: 0.0, 23: 0.020054432793189, 24: 0.0, 25: 0.020000000931435537, 26: 0.0, 27: 0.0, 28: 0.0, 29: 0.0, 30: 0.0, 31: 0.0, 32: 0.0, 33: 0.0, 34: 0.0, 35: 0.0, 36: 0.0, 37: 0.14009800406013267, 38: 0.15000000020509485, 39: 0.02000000104706877, 40: 0.0, 41: 0.0, 42: 0.0, 43: 0.0, 44: 0.0, 45: 0.0, 46: 0.11207141897629488, 47: 0.030586252476815887, 48: 0.0, 49: 0.0, 50: 0.0, 51: 0.0, 52: 0.0, 53: 0.0, 54: 0.0, 55: 0.02000000021202875, 56: 0.0, 57: 0.0, 58: 0.0, 59: 0.0, 60: 0.0, 61: 0.0, 62: 0.0, 63: 0.0, 64: 0.020000002793287047, 65: 0.14988050375499945, 66: 0.0, 67: 0.057248555089518344, 68: 0.040825629285401524, 69: 0.020000000408633513, 70: 0.0, 71: 0.0, 72: 0.0, 73: 0.0, 74: 0.02023936139235428, 75: 0.0, 76: 0.0, 77: 0.02000030624275224}
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
DELETADO DPS DO WHILE
COMEÇANDO ANO NOVO:  2018
Nao consta model
---------------
Começando Modelo do ano:  2018
======
Score Atualizado
Retornos atualizados
Excessos Atualizados
Sigmas Atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO SCORE DO ANO DE:  2018
## UTILIZANDO DADOS DE RETORNO DE:  df_ativos_2019
## UTILIZANDO EXCESSO DO ANO DE:  2019
## UTILIZANDO SIGMAS DO ANO DE:  2019
MODEL.S.VALUE =>  2
Começando o WHILE do ano 2018
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.505
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.2575
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.38125
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.31937499999999996
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.35031249999999997
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.36578124999999995
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.37351562499999996
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.3696484375
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.37158203125
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.372548828125
============================
SAIU DO WHILE
Sharpe máximo (diário) ≈ 0.3725  |  anualizado ≈ 5.91
2018 -> {0: 2.07855586224253e-09, 1: 0.01999999920876054, 2: 4.8749545940360876e-09, 3: 7.114959420159002e-10, 4: 1.2322016761082074e-09, 5: 1.2316069537242766e-09, 6: 7.811677958277453e-10, 7: 8.48837180915114e-10, 8: 8.572772340187772e-10, 9: 4.240330524705061e-09, 10: 0.08024281229354593, 11: 0.02444012883705715, 12: 2.0042494996746325e-09, 13: 2.7001160209876926e-09, 14: 5.061372728471078e-10, 15: 6.017998906264175e-10, 16: 7.257903669312869e-10, 17: 4.170583827211638e-09, 18: 0.1211296578889841, 19: 0.020000000883095212, 20: 7.877106580197708e-10, 21: 0.020000000993876114, 22: 4.2285323033884e-10, 23: 0.01999999920876054, 24: 1.3195329072828155e-09, 25: 9.460935214948382e-09, 26: 3.6970232581821297e-09, 27: 4.029323487222672e-09, 28: 1.0667816881409873e-09, 29: 0.1499999985647406, 30: 1.2066397677688953e-08, 31: 4.727750830182604e-09, 32: 4.375970995859423e-09, 33: 3.079119896831881e-09, 34: 1.0787836046881933e-09, 35: 9.042442612119586e-10, 36: 1.710220016672365e-09, 37: 0.01999999920876054, 38: 0.01999989459587163, 39: 6.539962695591535e-09, 40: 1.8164792547911557e-09, 41: 1.367109609396469e-09, 42: 1.1366185277673138e-09, 43: 0.10926704208389394, 44: 1.5594195969568686e-09, 45: 1.021091652795015e-09, 46: 0.01999999920876054, 47: 2.8052741925911338e-09, 48: 0.0, 49: 2.765374239251493e-09, 50: 1.4796022490906477e-09, 51: 1.280870973137032e-09, 52: 1.0661959629075602e-09, 53: 1.0665280492837373e-09, 54: 1.0070140312497491e-09, 55: 0.06329171170520394, 56: 0.02000000083703851, 57: 0.061628617803942354, 58: 6.29975332318245e-09, 59: 1.2927721925910398e-09, 60: 1.67546321269829e-09, 61: 1.003168139532709e-09, 62: 3.612128163362761e-09, 63: 2.202241647788142e-09, 64: 1.189938569521431e-09, 65: 0.01999999920876054, 66: 6.50249480005169e-09, 67: 0.0, 68: 4.815118772922738e-09, 69: 2.99671572276403e-08, 70: 0.1499999929090424, 71: 5.30558218850602e-10, 72: 5.573790396262403e-10, 73: 1.3209472289924112e-09, 74: 0.01999999920876054, 75: 5.093305735272959e-09, 76: 0.020000000913001893, 77: 0.019999990979110836}
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
DELETADO DPS DO WHILE
COMEÇANDO ANO NOVO:  2019
Nao consta model
---------------
Começando Modelo do ano:  2019
======
Score Atualizado
Retornos atualizados
Excessos Atualizados
Sigmas Atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO SCORE DO ANO DE:  2019
## UTILIZANDO DADOS DE RETORNO DE:  df_ativos_2020
## UTILIZANDO EXCESSO DO ANO DE:  2020
## UTILIZANDO SIGMAS DO ANO DE:  2020
MODEL.S.VALUE =>  2
Começando o WHILE do ano 2019
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.505
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.2575
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.13375
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.07187500000000001
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.1028125
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.11828125
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.110546875
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.1144140625
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.11248046875
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.113447265625
SAIU DO WHILE
Sharpe máximo (diário) ≈ 0.1134  |  anualizado ≈ 1.80
2019 -> {0: 0.0, 1: 0.020000110027041332, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.020000093524033397, 6: 0.0, 7: 0.0, 8: 0.0, 9: 0.0, 10: 0.0, 11: 0.0, 12: 0.020000124261793126, 13: 0.0, 14: 0.0, 15: 0.0, 16: 0.0, 17: 0.0, 18: 0.0, 19: 0.0, 20: 0.0, 21: 0.1499998471319956, 22: 0.0, 23: 0.02, 24: 0.0, 25: 0.0, 26: 0.0, 27: 0.0, 28: 0.0, 29: 0.020000046498157294, 30: 0.0, 31: 0.0, 32: 0.0, 33: 0.0, 34: 0.0, 35: 0.0, 36: 0.0, 37: 0.02, 38: 0.0, 39: 0.13116107427202003, 40: 0.0, 41: 0.0, 42: 0.0, 43: 0.0, 44: 0.02000010426116427, 45: 0.0, 46: 0.022591263069270718, 47: 0.1277454147063479, 48: 0.0, 49: 0.0, 50: 0.0, 51: 0.0, 52: 0.0, 53: 0.0, 54: 0.0, 55: 0.05896053869463508, 56: 0.0, 57: 0.0, 58: 0.0, 59: 0.0, 60: 0.0, 61: 0.0, 62: 0.0, 63: 0.0, 64: 0.02000003854239404, 65: 0.02, 66: 0.0, 67: 0.09954116036744695, 68: 0.020000172623653497, 69: 0.0, 70: 0.0, 71: 0.0, 72: 0.0, 73: 0.020000066670368088, 74: 0.02, 75: 0.020000035939791078, 76: 0.14999997673508902, 77: 0.0}
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
DELETADO DPS DO WHILE
COMEÇANDO ANO NOVO:  2020
Nao consta model
---------------
Começando Modelo do ano:  2020
======
Score Atualizado
Retornos atualizados
Excessos Atualizados
Sigmas Atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO SCORE DO ANO DE:  2020
## UTILIZANDO DADOS DE RETORNO DE:  df_ativos_2021
## UTILIZANDO EXCESSO DO ANO DE:  2021
## UTILIZANDO SIGMAS DO ANO DE:  2021
MODEL.S.VALUE =>  2
Começando o WHILE do ano 2020
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.505
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.2575
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.13375
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.195625
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.1646875
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.14921875
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.156953125
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.1608203125
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.16275390625
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.16178710937500002
SAIU DO WHILE
Sharpe máximo (diário) ≈ 0.1618  |  anualizado ≈ 2.57
2020 -> {0: 0.0, 1: 0.05275808112772498, 2: 0.0, 3: 0.0, 4: 0.020000009164585004, 5: 0.0, 6: 0.0, 7: 0.0, 8: 0.0, 9: 0.0, 10: 0.020000009255213492, 11: 0.0, 12: 0.021389465461820988, 13: 0.0, 14: 0.14999999765673513, 15: 0.0, 16: 0.0, 17: 6.15315204559561e-08, 18: 0.020000012437618796, 19: 0.020000008295857026, 20: 0.0, 21: 0.0, 22: 0.0, 23: 0.0, 24: 0.0, 25: 0.0, 26: 0.0, 27: 0.0, 28: 0.14999999390945729, 29: 0.0, 30: 0.0, 31: 1.0206529163145739e-07, 32: 0.0, 33: 0.0, 34: 0.019999810001757573, 35: 0.01999994316838743, 36: 0.0, 37: 0.0, 38: 0.0, 39: 0.020000010275978235, 40: 0.0, 41: 0.0, 42: 0.0, 43: 0.0, 44: 0.0, 45: 0.0, 46: 0.0, 47: 0.0, 48: 0.0, 49: 0.0, 50: 0.0, 51: 0.0, 52: 0.02000001308663384, 53: 7.173064728261818e-08, 54: 0.0, 55: 0.0200000123243046, 56: 0.0, 57: 5.6987526192319706e-08, 58: 0.0, 59: 0.0, 60: 0.0, 61: 0.0, 62: 0.0, 63: 0.0, 64: 0.1499999911835478, 65: 0.0, 66: 0.020000007590960225, 67: 0.020000025092187037, 68: 0.14999997830591436, 69: 0.0, 70: 0.0, 71: 0.0, 72: 0.0, 73: 0.020000007412352, 74: 0.02000001366674522, 75: 0.06585233613425787, 76: 0.0, 77: 0.0}
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
DELETADO DPS DO WHILE
COMEÇANDO ANO NOVO:  2021
Nao consta model
---------------
Começando Modelo do ano:  2021
======
Score Atualizado
Retornos atualizados
Excessos Atualizados
Sigmas Atualizados
-----
# ------ CRIAÇÃO DO MODELO
## UTILIZANDO SCORE DO ANO DE:  2021
## UTILIZANDO DADOS DE RETORNO DE:  df_ativos_2022
## UTILIZANDO EXCESSO DO ANO DE:  2022
## UTILIZANDO SIGMAS DO ANO DE:  2022
MODEL.S.VALUE =>  2
Começando o WHILE do ano 2021
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.505
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.2575
============================
==================
Modelo Resolveu....Condição:  optimal
Valor encontrado para o Sharpe:  0.13375
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.195625
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.1646875
============================
==================
Modelo Resolveu....Condição:  infeasible
Atualização do S_HI : 0.14921875
============================
==================
Modelo Resolveu....Condição:  optimal

In [40]:
ra = range(0,len(lista_ativos_finais))

for an in anos:
    an = int(an.split('-')[0])
    print(an)
    print([0 if carteiras_anuais[an]['pesos'][a] <0.02 else carteiras_anuais[an]['pesos'][a] for a in ra])

2015
[0, 0.020000010405344763, 0, 0.10898229009347347, 0, 0, 0, 0, 0, 0, 0, 0, 0.020000007412741116, 0, 0, 0, 0, 0.020000037388439012, 0, 0, 0.09782814079935771, 0, 0, 0.02, 0, 0, 0, 0, 0, 0, 0.10798867112242323, 0, 0, 0.14999999543572304, 0, 0, 0, 0.02, 0.02, 0, 0, 0, 0, 0, 0, 0, 0.02, 0.10520092266857674, 0, 0.02, 0, 0, 0, 0, 0.020000010823238434, 0, 0, 0.14999989893711208, 0, 0, 0, 0, 0, 0, 0, 0.02, 0.020000010137187583, 0, 0, 0.02, 0, 0, 0, 0, 0.02, 0, 0, 0.020000010407959855]
2016
[0, 0, 0.06754428034093454, 0, 0.031608010846826746, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.08189000679144562, 0, 0, 0, 0, 0, 0, 0, 0.02000002619991728, 0, 0, 0.04833983489834474, 0, 0, 0, 0, 0.11043650244873764, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.149999977925695, 0.02000000392701874, 0, 0, 0, 0.06504190071744884, 0, 0, 0, 0.11428050046663966, 0, 0, 0.11085882730125977, 0, 0, 0, 0, 0, 0, 0, 0, 0.020000003240238318, 0]
2017
[0, 0.020000314383101545, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.020191687387314163, 0, 0.03344578141839684, 0, 0.06535774641868049, 0.02000000086749556, 0, 0, 0, 0, 0.020054432793189, 0, 0.020000000931435537, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.14009800406013267, 0.15000000020509485, 0.02000000104706877, 0, 0, 0, 0, 0, 0, 0.11207141897629488, 0.030586252476815887, 0, 0, 0, 0, 0, 0, 0, 0.02000000021202875, 0, 0, 0, 0, 0, 0, 0, 0, 0.020000002793287047, 0.14988050375499945, 0, 0.057248555089518344, 0.040825629285401524, 0.020000000408633513, 0, 0, 0, 0, 0.02023936139235428, 0, 0, 0.02000030624275224]
2018
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.08024281229354593, 0.02444012883705715, 0, 0, 0, 0, 0, 0, 0.1211296578889841, 0.020000000883095212, 0, 0.020000000993876114, 0, 0, 0, 0, 0, 0, 0, 0.1499999985647406, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.10926704208389394, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.06329171170520394, 0.02000000083703851, 0.061628617803942354, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1499999929090424, 0, 0, 0, 0, 0, 0.020000000913001893, 0]
2019
[0, 0.020000110027041332, 0, 0, 0, 0.020000093524033397, 0, 0, 0, 0, 0, 0, 0.020000124261793126, 0, 0, 0, 0, 0, 0, 0, 0, 0.1499998471319956, 0, 0.02, 0, 0, 0, 0, 0, 0.020000046498157294, 0, 0, 0, 0, 0, 0, 0, 0.02, 0, 0.13116107427202003, 0, 0, 0, 0, 0.02000010426116427, 0, 0.022591263069270718, 0.1277454147063479, 0, 0, 0, 0, 0, 0, 0, 0.05896053869463508, 0, 0, 0, 0, 0, 0, 0, 0, 0.02000003854239404, 0.02, 0, 0.09954116036744695, 0.020000172623653497, 0, 0, 0, 0, 0.020000066670368088, 0.02, 0.020000035939791078, 0.14999997673508902, 0]
2020
[0, 0.05275808112772498, 0, 0, 0.020000009164585004, 0, 0, 0, 0, 0, 0.020000009255213492, 0, 0.021389465461820988, 0, 0.14999999765673513, 0, 0, 0, 0.020000012437618796, 0.020000008295857026, 0, 0, 0, 0, 0, 0, 0, 0, 0.14999999390945729, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.020000010275978235, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.02000001308663384, 0, 0, 0.0200000123243046, 0, 0, 0, 0, 0, 0, 0, 0, 0.1499999911835478, 0, 0.020000007590960225, 0.020000025092187037, 0.14999997830591436, 0, 0, 0, 0, 0.020000007412352, 0.02000001366674522, 0.06585233613425787, 0, 0]
2021
[0, 0.1499937695469466, 0, 0.020000016114562303, 0, 0, 0.020000020562379053, 0, 0, 0.14999999586820942, 0.021210307290587822, 0, 0.06047981216851504, 0, 0, 0, 0, 0.03580284679445016, 0.020000086168721724, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.020000032392455572, 0, 0, 0, 0.020000015714710908, 0.14999998948288004, 0, 0, 0, 0, 0.020000030747952133, 0.020000022002825715, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.029651094077282315, 0.02000021131220602, 0, 0.11076424283297664, 0.02000001639232965, 0, 0, 0, 0, 0, 0, 0.07209676839909869, 0, 0, 0, 0, 0.020000723441485162, 0, 0, 0, 0, 0.020000019195710553, 0, 0, 0, 0]
2022
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.14999999750203222, 0, 0, 0.020000001053539142, 0, 0.09461806323251407, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.02720724856041323, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.020000001103381914, 0.09633378707827366, 0.12495997029953879, 0, 0, 0, 0, 0, 0, 0, 0.14999998894123373, 0, 0, 0, 0, 0.031095030457899422, 0, 0.02000006194087503, 0, 0.08578581986787391, 0, 0, 0, 0.020000001005549575, 0, 0]
2023
[0.02000000897878519, 0, 0, 0, 0, 0, 0, 0, 0, 0.04295762627587239, 0, 0, 0, 0, 0, 0.13476355269516008, 0, 0.020000010164933874, 0, 0, 0.02000003653987929, 0, 0, 0.020000080799396514, 0, 0.02000001532728897, 0, 0, 0.14999999457054483, 0, 0, 0, 0, 0, 0, 0.020000008396179072, 0, 0, 0, 0, 0, 0, 0, 0, 0.020000014741798505, 0, 0, 0, 0, 0, 0, 0, 0.09227941389562275, 0.020000085167260387, 0.020000016063278527, 0, 0.14999986029548432, 0, 0, 0, 0, 0, 0.020000017679510814, 0.02000001746944462, 0.020000010008220742, 0, 0, 0.020000053135242737, 0.020000010295818688, 0, 0, 0, 0, 0, 0, 0, 0.14999919189288466, 0]
2024
[0.02000001168636071, 0, 0, 0.02000002971971519, 0, 0, 0, 0, 0, 0, 0, 0, 0.02000004868978271, 0, 0, 0, 0.09969124015187011, 0.14999999555725152, 0.02000001176923606, 0, 0.14999999793572427, 0, 0, 0.020000012425923717, 0, 0, 0, 0, 0.06220537053998024, 0.028019571142237347, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.04220733556897688, 0, 0.06154445476395498, 0, 0, 0.03633212954254383, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.02000004155588671, 0, 0, 0, 0, 0, 0.020000037442507716, 0, 0, 0, 0, 0, 0.020000042688825426, 0.020000007348831107, 0.020000031461457013, 0, 0, 0.1499996070620315, 0, 0, 0, 0]
2025
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.020000044596125154, 0, 0, 0, 0.09167729675894075, 0.14999999681815623, 0.020000003436037566, 0, 0.14999999854185117, 0, 0, 0, 0, 0, 0, 0, 0.06072731686459645, 0.02992730862397971, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.04579400133289584, 0, 0.06833594014726034, 0, 0, 0.03398743989802408, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.020000004163701436, 0, 0, 0, 0, 0, 0.020000001192358164, 0, 0, 0, 0, 0, 0.02000000462577578, 0.02000000178907783, 0, 0, 0, 0.149550548259983, 0, 0.020000004201115907, 0, 0]

In [41]:
data = []
for carteira in carteiras_anuais:
    # print(carteiras_anuais[carteira])
    # print(len(carteiras_anuais[carteira]['pesos']))
    # print(len(lista_ativos_finais))
    # print(len(ra))
    final = pd.DataFrame({
        'peso_ativo': [carteiras_anuais[carteira]['pesos'][a] for a in ra],
        'ativado': [0 if carteiras_anuais[carteira]['pesos'][a] < vb_peso_minimo else 1 for a in ra],
    }, index=lista_ativos_finais)
    # print(len(final))
    df_final = final[final['ativado']!=0]
    data.append(df_final)

In [42]:
np.round(data[0].sort_values(by='peso_ativo', ascending=False)['peso_ativo'],4)

FLRY3     0.1500
RADL3     0.1500
AXIA3     0.1090
ENGI11    0.1080
MGLU3     0.1052
CSMG3     0.0978
CPFE3     0.0200
POMO4     0.0200
YDUQ3     0.0200
ALOS3     0.0200
SMTO3     0.0200
BRAP4     0.0200
MDNE3     0.0200
IRBR3     0.0200
IGTI11    0.0200
CXSE3     0.0200
SMFT3     0.0200
MOVI3     0.0200
TEND3     0.0200
VBBR3     0.0200
Name: peso_ativo, dtype: float64