In [9]:
import os
from brapi import Brapi
from dotenv import load_dotenv
import pandas as pd
import requests
import json

from pathlib import Path

In [10]:
lista_df = []
for filename in os.listdir('estatistica'):
    
    # 2. Reconstruct the full absolute or relative path to the file
    try:
        full_path_balanco = os.path.join('balanco', filename)
        full_path_dre = os.path.join('dre', filename)
        full_path_estatistica = os.path.join('estatistica', filename)

        df_balanco = pd.read_csv(full_path_balanco)
        df_dre = pd.read_csv(full_path_dre)
        df_estatistica = pd.read_csv(full_path_estatistica)

        df_merge = df_balanco.merge(df_dre, on='endDate').merge(df_estatistica, on='endDate').copy()

        df_merge['capital_investido'] = df_merge['totalCurrentAssets'].fillna(0) - df_merge['currentLiabilities'].fillna(0) + df_merge['propertyPlantEquipment'].fillna(0)
        df_merge['ROC'] = df_merge['ebit'] / df_merge['capital_investido']
        df_merge['EY']  = df_merge['ebit'] / df_merge['enterpriseValue']


        dicio_merge = {
            'ativo':filename,
            'data':df_merge
        }
        lista_df.append(dicio_merge)
    except Exception as e:
        print(e)
        continue

In [11]:
lista_df[1]['data'][['endDate','capital_investido','ROC','EY']]

       endDate  capital_investido       ROC        EY
0   2025-12-31         2138731000  0.719754  0.069923
1   2024-12-31         2103782000  0.690710  0.089326
2   2023-12-31         1773955000  3.051214  0.259800
3   2022-12-31         2270216000  0.206836       NaN
4   2021-12-31         1072388000  0.456978       NaN
5   2020-12-31         1453741000  0.220283       NaN
6   2019-12-31         1314123000  0.193321       NaN
7   2018-12-31           93002000  6.024537       NaN
8   2017-12-31          196117000  1.949780       NaN
9   2016-12-31           90128000  4.287691       NaN
10  2015-12-31          101824000  3.291680       NaN
11  2014-12-31          213573990  1.977544       NaN
12  2013-12-31          260276990  2.104842       NaN
13  2012-12-31          464253000  0.897487       NaN

In [ ]:

lista_final = []
retirar_ativos = []
for i in range(len(lista_df)):
    if len(lista_df[i]['data'][['endDate','capital_investido','ROC','EY']]) >= 10:
        ativo = lista_df[i]['ativo']
        data_f = lista_df[i]['data'][['endDate','ROC','EY']]
        data_f.to_csv(f'magic_formula/{ativo}')
        dc = {
            'ativo':lista_df[i]['ativo'],
            'data':data_f
        }
        lista_final.append(dc)
    else:
        try:
            # path_remove = os.path.join('magic_formula', lista_df[i]['ativo'])
            # os.remove(path_remove)
            retirar_ativos.append(lista_df[i]['ativo'])
            print(f'{lista_df[i]['ativo']} - Tamanho: {len(lista_df[i]['data'][['endDate','capital_investido','ROC','EY']])}')
            print('ATIVO ESCLUIDO da MF: ',lista_df[i]['ativo'])
        except:
            print('erro ao excluir')
            continue

KeyError: "['capital_investido'] not in index"

In [13]:
lista_final[40]['data']

       endDate       ROC        EY
0   2025-12-31  1.481279  0.109960
1   2024-12-31  1.428273  0.150846
2   2023-12-31  1.149959  0.122361
3   2022-12-31  1.856104  0.168722
4   2021-12-31  1.705117  0.145406
5   2020-12-31  0.976362  0.070193
6   2019-12-31  1.470966  0.088545
7   2018-12-31  1.363037  0.097670
8   2017-12-31  1.395387  0.101918
9   2016-12-31  1.261343  0.140772
10  2015-12-31  1.281334  0.201630
11  2014-12-31  1.297428  0.145540
12  2013-12-31  1.049870  0.123554
13  2012-12-31 -0.315779 -0.154744

In [17]:
lista_df = []

for filename in os.listdir('magic_formula'):
    
    # 2. Reconstruct the full absolute or relative path to the file
    full_path = os.path.join('magic_formula', filename)
    
    # 3. Check if the current item is actually a file (and not a subfolder)
    # if os.path.isfile(full_path):
        
    #     # 4. Open and process the file safely
    #     with open(full_path, "r", encoding="utf-8") as file:
    #         content = file.read()
    #         print(f"--- Content of {filename} ---")
    #         print(pd.read_csv(full_path))
    dicio = {
        'ativo':filename,
        'data':pd.read_csv(full_path)
    }

    lista_df.append(dicio)

In [18]:
len(lista_df)

78