In [1]:
import os
from brapi import Brapi
from dotenv import load_dotenv
import pandas as pd
import requests
import json

from pathlib import Path

In [90]:
lista_df = []
for filename in os.listdir('estatistica'):
    
    # 2. Reconstruct the full absolute or relative path to the file
    try:
        full_path_balanco = os.path.join('balanco', filename)
        full_path_dre = os.path.join('dre', filename)
        full_path_estatistica = os.path.join('estatistica', filename)

        df_balanco = pd.read_csv(full_path_balanco)
        df_dre = pd.read_csv(full_path_dre)
        df_estatistica = pd.read_csv(full_path_estatistica)

        df_merge = df_balanco.merge(df_dre, on='endDate').merge(df_estatistica, on='endDate').copy()

        df_merge['capital_investido'] = df_merge['totalCurrentAssets'].fillna(0) - df_merge['currentLiabilities'].fillna(0) + df_merge['propertyPlantEquipment'].fillna(0)
        df_merge['ROC'] = df_merge['ebit'] / df_merge['capital_investido']
        df_merge['EY']  = df_merge['ebit'] / df_merge['enterpriseValue'].fillna(0)


        dicio_merge = {
            'ativo':filename,
            'data':df_merge
        }
        lista_df.append(dicio_merge)
    except Exception as e:
        print(e)
        continue

[Errno 2] No such file or directory: 'balanco\\AXIA6'

In [102]:
lista_df[1]['data'][['endDate','capital_investido','ROC','EY']]

       endDate  capital_investido       ROC        EY
0   2025-12-31         2138731000  0.719754  0.069923
1   2024-12-31         2103782000  0.690710  0.089326
2   2023-12-31         1773955000  3.051214  0.259800
3   2022-12-31         2270216000  0.206836       inf
4   2021-12-31         1072388000  0.456978       inf
5   2020-12-31         1453741000  0.220283       inf
6   2019-12-31         1314123000  0.193321       inf
7   2018-12-31           93002000  6.024537       inf
8   2017-12-31          196117000  1.949780       inf
9   2016-12-31           90128000  4.287691       inf
10  2015-12-31          101824000  3.291680       inf
11  2014-12-31          213573990  1.977544       inf
12  2013-12-31          260276990  2.104842       inf
13  2012-12-31          464253000  0.897487       inf

In [118]:

lista_final = []

for i in range(len(lista_df)):
    if len(lista_df[i]['data'][['endDate','capital_investido','ROC','EY']]) >= 10:
        ativo = lista_df[i]['ativo']
        data_f = lista_df[i]['data'][['endDate','ROC','EY']]
        data_f.to_csv(f'magic_formula/{ativo}')
        dc = {
            'ativo':lista_df[i]['ativo'],
            'data':data_f
        }
        lista_final.append(dc)
    else:
        print(f'{lista_df[i]['ativo']} - Tamanho: {len(lista_df[i]['data'][['endDate','capital_investido','ROC','EY']])}')

ASAI3 - Tamanho: 7
AURE3 - Tamanho: 5
CEAB3 - Tamanho: 8
CMIN3 - Tamanho: 7
CURY3 - Tamanho: 7
HAPV3 - Tamanho: 9
NATU3 - Tamanho: 6
RAIZ4 - Tamanho: 6
RDOR3 - Tamanho: 8
RECV3 - Tamanho: 6
TIMS3 - Tamanho: 8
VAMO3 - Tamanho: 8
VIVA3 - Tamanho: 7

In [119]:
lista_final[40]['data']

       endDate       ROC        EY
0   2025-12-31  0.183894  0.130503
1   2024-12-31  0.128215  0.104287
2   2023-12-31  0.089037  0.062451
3   2022-12-31  0.122505  0.085720
4   2021-12-31  0.073225  0.045606
5   2020-12-31  0.120388  0.030817
6   2019-12-31  0.276640  0.047595
7   2018-12-31  0.395459  0.055862
8   2017-12-31  0.287640  0.058088
9   2016-12-31  0.346876  0.077440
10  2015-12-31  0.316594  0.106852
11  2014-12-31  0.289963  0.324803
12  2013-12-31  0.305080  0.318888
13  2012-12-31  0.345668  0.278422

In [120]:
lista_df = []

for filename in os.listdir('magic_formula'):
    
    # 2. Reconstruct the full absolute or relative path to the file
    full_path = os.path.join('magic_formula', filename)
    
    # 3. Check if the current item is actually a file (and not a subfolder)
    # if os.path.isfile(full_path):
        
    #     # 4. Open and process the file safely
    #     with open(full_path, "r", encoding="utf-8") as file:
    #         content = file.read()
    #         print(f"--- Content of {filename} ---")
    #         print(pd.read_csv(full_path))
    dicio = {
        'ativo':filename,
        'data':pd.read_csv(full_path)
    }

    lista_df.append(dicio)