In [ ]:
import pandas as pd

retornos = pd.DataFrame({
    'PETR4': [ 1.0, -2.0,  3.0,  0.0,  2.0],
    'VALE3': [ 2.0, -1.0,  1.0,  1.0,  2.0],
})
cov = retornos.cov()         
arr = cov.to_numpy()
n = len(cov)

sigma = {(a, b): arr[a, b]    
         for a in range(n)
         for b in range(n)}

In [4]:
retornos

   PETR4  VALE3
0    1.0    2.0
1   -2.0   -1.0
2    3.0    1.0
3    0.0    1.0
4    2.0    2.0

In [3]:
arr

array([[3.7 , 1.75],
       [1.75, 1.5 ]])

In [5]:
cov

       PETR4  VALE3
PETR4   3.70   1.75
VALE3   1.75   1.50

In [2]:
sigma

{(0, 0): np.float64(3.7),
 (0, 1): np.float64(1.75),
 (1, 0): np.float64(1.75),
 (1, 1): np.float64(1.5)}