In [ ]:
import pandas as pd
import numpy as np
import random
import pyomo.environ as pyo
from pyomo.environ import *
from pyomo.environ import SolverFactory
import yfinance as yf
from pathlib import Path
import os
import matplotlib.pyplot as plt

In [2]:
anos = ['2025-12-31',
 '2024-12-31',
 '2023-12-31',
 '2022-12-31',
 '2021-12-31',
 '2020-12-31',
 '2019-12-31',
 '2018-12-31',
 '2017-12-31',
 '2016-12-31',
 '2015-12-31',
 ]

In [ ]:
basedados_ativos = Path('../../base_dados/brapi/retornos/retornos.csv')
basedados_ibov = Path('../../base_dados/retorno_ibov_2015_2026.csv') 

lista_piotroski = []

for filename in os.listdir(path='../../base_dados/brapi/piotroski/'):
    
    # 2. Reconstruct the full absolute or relative path to the file
    full_path = os.path.join('../../base_dados/brapi/piotroski/', filename)
    
    # 3. Check if the current item is actually a file (and not a subfolder)
    # if os.path.isfile(full_path):
        
    #     # 4. Open and process the file safely
    #     with open(full_path, "r", encoding="utf-8") as file:
    #         content = file.read()
    #         print(f"--- Content of {filename} ---")
    #         print(pd.read_csv(full_path))
    dicio = {
        'ativo':filename,
        'data':pd.read_csv(full_path)
    }

    lista_piotroski.append(dicio)

df_ativos=pd.read_csv(basedados_ativos).set_index(['date']).fillna(0)

df_ibov=pd.read_csv(basedados_ibov).set_index(['Date']).fillna(0)

In [4]:
print(df_ativos.shape[0])
print(df_ibov.shape)

2863
(2849, 1)

In [5]:
print(f'tamanho mf original: ',len(lista_magic_formula))
lista_mf_check = []
lista_ativos_finais = []
for i in range(len(lista_magic_formula)):
    if lista_magic_formula[i]['ativo'] in df_ativos.columns.tolist():
        lista_ativos_finais.append(lista_magic_formula[i]['ativo'])
        dc = {
            'ativo':lista_magic_formula[i]['ativo'],
            'data':lista_magic_formula[i]['data']
        }
        lista_mf_check.append(dc)
    else:
        print(f"Nao está na lista: {lista_magic_formula[i]['ativo']}")
print(f'tamanho mf Final: ',len(lista_mf_check))

tamanho mf original:  78
tamanho mf Final:  78

In [6]:
df_ativos = df_ativos[df_ativos.index.isin(df_ibov.index)]
print(df_ativos.shape)

(2847, 78)

In [7]:
df_ibov = df_ibov[df_ibov.index.isin(df_ativos[df_ativos.index.isin(df_ibov.index)].index)]
print(df_ibov.shape)

(2847, 1)

In [8]:
df_ativos = df_ativos.filter(lista_ativos_finais)
print(len(df_ativos))

2847

In [46]:
df_ativos.loc['2017-04-01':'2018-03-31']

,ABEV3,ALOS3,ANIM3,AXIA3,AZZA3,B3SA3,BBAS3,BBDC3,BBDC4,BBSE3,...,TAEE11,TEND3,TOTS3,UGPA3,USIM5,VALE3,VBBR3,VIVT3,WEGE3,YDUQ3
date,,,,,,,,,,,,,,,,,,,,,
2017-04-03,-0.013157,0.0,-0.029856,0.005851,-0.007331,0.008289,0.002962,0.010607,0.004942,0.000344,...,0.008717,0.000000,0.010819,0.004468,-0.015768,-0.009399,0.0,0.044875,0.005166,0.0
2017-04-04,0.006109,0.0,0.000000,-0.005236,-0.005456,0.012342,0.003832,0.007637,0.007654,0.001369,...,0.000860,0.000000,0.005340,-0.002362,-0.013715,0.038630,0.0,-0.015987,0.008014,0.0
2017-04-05,-0.012694,0.0,0.000000,-0.035650,0.013558,-0.010657,-0.017055,-0.026365,-0.020446,-0.016756,...,-0.008199,0.000000,-0.003545,-0.003344,-0.046423,-0.039150,0.0,0.003304,-0.005686,0.0
2017-04-06,0.005593,0.0,-0.003850,-0.032124,-0.033760,-0.016954,-0.023337,-0.009129,-0.010589,-0.002781,...,-0.016534,0.000000,0.000000,-0.000561,-0.041360,-0.018340,0.0,0.007685,-0.001130,0.0
2017-04-07,0.003893,0.0,0.016212,-0.013146,0.042189,0.016195,-0.004292,0.000636,0.002202,0.010110,...,-0.005753,0.000000,-0.005692,0.002100,0.020326,0.008304,0.0,-0.013618,-0.026277,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-03-23,-0.003747,0.0,0.005483,-0.008432,-0.003800,-0.021169,-0.006986,0.012115,0.006808,0.030014,...,0.028063,-0.011853,-0.001371,-0.010996,-0.012626,-0.007870,0.0,-0.000480,-0.008191,0.0
2018-03-26,0.003344,0.0,-0.029959,0.074128,0.018871,0.009035,0.006794,0.009577,0.005714,-0.014573,...,0.005746,0.021202,-0.002758,0.001878,0.006394,0.009614,0.0,0.013707,-0.015148,0.0
2018-03-27,-0.006666,0.0,-0.043321,-0.025494,-0.026008,-0.002723,-0.024828,-0.020814,-0.012143,-0.001031,...,0.013337,0.007051,0.000347,0.002594,-0.019059,-0.027141,0.0,0.025863,-0.017686,0.0
2018-03-28,-0.000837,0.0,0.010475,-0.047810,0.014160,0.019934,-0.003219,0.009688,0.006541,0.006542,...,0.002347,-0.004281,-0.007252,0.013513,-0.011101,0.016640,0.0,-0.010175,0.008550,0.0
2018-03-29,0.010493,0.0,0.050213,-0.005212,0.008380,0.022599,0.017615,0.025047,0.026502,0.001025,...,0.018755,0.029294,0.002085,0.005957,0.021520,0.016130,0.0,0.032706,0.009374,0.0

In [47]:
# #ativos
# df_ativos_2015 = df_ativos[df_ativos.index.str.startswith('2015')]
# df_ativos_2016 = df_ativos[df_ativos.index.str.startswith('2016')]
# df_ativos_2017 = df_ativos[df_ativos.index.str.startswith('2017')]
# df_ativos_2018 = df_ativos[df_ativos.index.str.startswith('2018')]
# df_ativos_2019 = df_ativos[df_ativos.index.str.startswith('2019')]
# df_ativos_2020 = df_ativos[df_ativos.index.str.startswith('2020')]
# df_ativos_2021 = df_ativos[df_ativos.index.str.startswith('2021')]
# df_ativos_2022 = df_ativos[df_ativos.index.str.startswith('2022')]
# df_ativos_2023 = df_ativos[df_ativos.index.str.startswith('2023')]
# df_ativos_2024 = df_ativos[df_ativos.index.str.startswith('2024')]
# df_ativos_2025 = df_ativos[df_ativos.index.str.startswith('2025')]
# df_ativos_2026 = df_ativos[df_ativos.index.str.startswith('2026')]
df_ativos_2015 = df_ativos.loc['2015-04-01':'2016-03-31']
df_ativos_2016 = df_ativos.loc['2016-04-01':'2017-03-31']
df_ativos_2017 = df_ativos.loc['2017-04-01':'2018-03-31']
df_ativos_2018 = df_ativos.loc['2018-04-01':'2019-03-31']
df_ativos_2019 = df_ativos.loc['2019-04-01':'2020-03-31']
df_ativos_2020 = df_ativos.loc['2020-04-01':'2021-03-31']
df_ativos_2021 = df_ativos.loc['2021-04-01':'2022-03-31']
df_ativos_2022 = df_ativos.loc['2022-04-01':'2023-03-31']
df_ativos_2023 = df_ativos.loc['2023-04-01':'2024-03-31']   
df_ativos_2024 = df_ativos.loc['2024-04-01':'2025-03-31']
df_ativos_2025 = df_ativos.loc['2025-04-01':'2026-03-31']
# df_ativos_2026 = df_ativos.loc['2026-04-01':'2027-03-31']

df_ativos_2015.to_csv('retornos_ativos/df_ativos_2015.csv')
df_ativos_2016.to_csv('retornos_ativos/df_ativos_2016.csv')
df_ativos_2017.to_csv('retornos_ativos/df_ativos_2017.csv')
df_ativos_2018.to_csv('retornos_ativos/df_ativos_2018.csv')
df_ativos_2019.to_csv('retornos_ativos/df_ativos_2019.csv')
df_ativos_2020.to_csv('retornos_ativos/df_ativos_2020.csv')
df_ativos_2021.to_csv('retornos_ativos/df_ativos_2021.csv')
df_ativos_2022.to_csv('retornos_ativos/df_ativos_2022.csv')
df_ativos_2023.to_csv('retornos_ativos/df_ativos_2023.csv')
df_ativos_2024.to_csv('retornos_ativos/df_ativos_2024.csv')
df_ativos_2025.to_csv('retornos_ativos/df_ativos_2025.csv')
# df_ativos_2026.to_csv('retornos_ativos/df_ativos_2026.csv')

#ibov
# df_ibov_2015 = df_ibov[df_ibov.index.str.startswith('2015')]
# df_ibov_2016 = df_ibov[df_ibov.index.str.startswith('2016')]
# df_ibov_2017 = df_ibov[df_ibov.index.str.startswith('2017')]
# df_ibov_2018 = df_ibov[df_ibov.index.str.startswith('2018')]
# df_ibov_2019 = df_ibov[df_ibov.index.str.startswith('2019')]
# df_ibov_2020 = df_ibov[df_ibov.index.str.startswith('2020')]
# df_ibov_2021 = df_ibov[df_ibov.index.str.startswith('2021')]
# df_ibov_2022 = df_ibov[df_ibov.index.str.startswith('2022')]
# df_ibov_2023 = df_ibov[df_ibov.index.str.startswith('2023')]
# df_ibov_2024 = df_ibov[df_ibov.index.str.startswith('2024')]
# df_ibov_2025 = df_ibov[df_ibov.index.str.startswith('2025')]
# df_ibov_2026 = df_ibov[df_ibov.index.str.startswith('2026')]

df_ibov_2015 = df_ibov.loc['2015-04-01':'2016-03-31']
df_ibov_2016 = df_ibov.loc['2016-04-01':'2017-03-31']
df_ibov_2017 = df_ibov.loc['2017-04-01':'2018-03-31']
df_ibov_2018 = df_ibov.loc['2018-04-01':'2019-03-31']
df_ibov_2019 = df_ibov.loc['2019-04-01':'2020-03-31']
df_ibov_2020 = df_ibov.loc['2020-04-01':'2021-03-31']
df_ibov_2021 = df_ibov.loc['2021-04-01':'2022-03-31']
df_ibov_2022 = df_ibov.loc['2022-04-01':'2023-03-31']
df_ibov_2023 = df_ibov.loc['2023-04-01':'2024-03-31']
df_ibov_2024 = df_ibov.loc['2024-04-01':'2025-03-31']
df_ibov_2025 = df_ibov.loc['2025-04-01':'2026-03-31']
# df_ibov_2026 = df_ibov.loc['2026-04-01':'2027-03-31']



df_ibov_2015.to_csv('retornos_ibov/df_ibov_2015.csv')
df_ibov_2016.to_csv('retornos_ibov/df_ibov_2016.csv')
df_ibov_2017.to_csv('retornos_ibov/df_ibov_2017.csv')
df_ibov_2018.to_csv('retornos_ibov/df_ibov_2018.csv')
df_ibov_2019.to_csv('retornos_ibov/df_ibov_2019.csv')
df_ibov_2020.to_csv('retornos_ibov/df_ibov_2020.csv')
df_ibov_2021.to_csv('retornos_ibov/df_ibov_2021.csv')
df_ibov_2022.to_csv('retornos_ibov/df_ibov_2022.csv')
df_ibov_2023.to_csv('retornos_ibov/df_ibov_2023.csv')
df_ibov_2024.to_csv('retornos_ibov/df_ibov_2024.csv')
df_ibov_2025.to_csv('retornos_ibov/df_ibov_2025.csv')
# df_ibov_2026.to_csv('retornos_ibov/df_ibov_2026.csv')

## EXCESSO DOS ANOS e SIGMA (MAtriz de covariancia)

##### EXCESSO PARA TODOS

In [18]:
lista_macro = []

for filename in os.listdir(path='../../base_dados/brapi/macro'):
    
    # 2. Reconstruct the full absolute or relative path to the file
    full_path = os.path.join('../../base_dados/brapi/macro/',filename)
    
    # 3. Check if the current item is actually a file (and not a subfolder)
    # if os.path.isfile(full_path):
        
    #     # 4. Open and process the file safely
    #     with open(full_path, "r", encoding="utf-8") as file:
    #         content = file.read()
    #         print(f"--- Content of {filename} ---")
    #         print(pd.read_csv(full_path))
    dicio = {
        'macro':filename,
        'data':pd.read_csv(full_path)
    }

    lista_macro.append(dicio)
lista_macro[0]['data'].set_index('date', inplace=True)
selic_d = lista_macro[0]['data']
selic_d.to_csv('selic/selic_diario.csv')

In [11]:
dict_sigma = {}
dict_excesso = {}
for an in anos:
    ano = an.split("-")[0]
    if ano == '2015':
        pass
    else:
        try:
            print(f"=============== \n EXCESSO {ano}\n ============")
            print("Atualização, Ano: ",ano)
            df = f'df_ativos_{ano}'
            df_f = pd.DataFrame(eval(df))
            slc = selic_d[selic_d.index.isin(df_f.index)]
            slc['valor_diario'] = slc['valor_diario']/100

            print(f"Tamanho DF de {ano}: ", len(df_f))
            print(f"Tamanho Selic: ", len(slc['valor_diario']))
            ano = int(ano)
            dict_excesso[ano] = df_f.sub(slc['valor_diario'],axis=0)
            print("tamanho final do Excesso: ",len(dict_excesso[ano]))

            print(f"============\n SIGMA {ano}\n===========")            
            dict_sigma[ano] = dict_excesso[ano].cov()
            print('Tamanho final do SIGMA: ',len(dict_sigma[ano]))

        except Exception as e:
            print(e)
            print("ERror")

===============
 EXCESSO 2025
 ============
Atualização, Ano:  2025
Tamanho DF de 2025:  250
Tamanho Selic:  250
tamanho final do Excesso:  250
============
 SIGMA 2025
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2024
 ============
Atualização, Ano:  2024
Tamanho DF de 2024:  251
Tamanho Selic:  251
tamanho final do Excesso:  251
============
 SIGMA 2024
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2023
 ============
Atualização, Ano:  2023
Tamanho DF de 2023:  248
Tamanho Selic:  248
tamanho final do Excesso:  248
============
 SIGMA 2023
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2022
 ============
Atualização, Ano:  2022
Tamanho DF de 2022:  250
Tamanho Selic:  250
tamanho final do Excesso:  250
============
 SIGMA 2022
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2021
 ============
Atualização, Ano:  2021
Tamanho DF de 2021:  247
Tamanho Selic:  247
tamanho final do Excesso:  247
============
 SIGMA 2021
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2020
 ============
Atualização, Ano:  2020
Tamanho DF de 2020:  248
Tamanho Selic:  248
tamanho final do Excesso:  248
============
 SIGMA 2020
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2019
 ============
Atualização, Ano:  2019
Tamanho DF de 2019:  248
Tamanho Selic:  248
tamanho final do Excesso:  248
============
 SIGMA 2019
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2018
 ============
Atualização, Ano:  2018
Tamanho DF de 2018:  245
Tamanho Selic:  245
tamanho final do Excesso:  245
============
 SIGMA 2018
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2017
 ============
Atualização, Ano:  2017
Tamanho DF de 2017:  246
Tamanho Selic:  246
tamanho final do Excesso:  246
============
 SIGMA 2017
===========
Tamanho final do SIGMA:  78
===============
 EXCESSO 2016
 ============
Atualização, Ano:  2016
Tamanho DF de 2016:  249
Tamanho Selic:  249
tamanho final do Excesso:  249
============
 SIGMA 2016
===========
Tamanho final do SIGMA:  78

### Dados da Magic Formula (SCORE)

In [12]:


# y1 = []
# y2 = []
# for a in anos[:-1]:
#     y1.append(a)
# for a in anos[:-1]:
#     y2.append(a.split('-')[0])

# print("=-"*48)
# print("Anos totais: ",y)
# print("=-"*48)

dict_score_todos = []
dict_score = {}
for i, ativo in enumerate(df_ativos_2016.columns.tolist()):
        if ativo == lista_mf_check[i]['ativo']:
            for ano in anos:
                df_temp = lista_mf_check[i]['data'].query("endDate in @ano")
                score_anual = (0.5*df_temp['ROC'] + 0.5*df_temp['EY']).sum()
                dict_score[(ano, ativo)] = score_anual
                print("feito dict do ativo: ",ativo,ano,score_anual)
        else:
            print(f" ativo: {ativo}")
            print(f" ativo_mf: {lista_mf_check[i]['ativo']}")
df_scores = pd.Series(dict_score).unstack()  # index=anos, columns=ativos
df_scores = df_scores.replace([np.inf, -np.inf],0)    

dict_score_todos.append(df_scores)

feito dict do ativo:  ABEV3 2025-12-31 0.5075949601583762
feito dict do ativo:  ABEV3 2024-12-31 0.38261468462358406
feito dict do ativo:  ABEV3 2023-12-31 0.4707780476577104
feito dict do ativo:  ABEV3 2022-12-31 0.3698561983003272
feito dict do ativo:  ABEV3 2021-12-31 0.33762441702482754
feito dict do ativo:  ABEV3 2020-12-31 0.3419377467430017
feito dict do ativo:  ABEV3 2019-12-31 0.3554827706790753
feito dict do ativo:  ABEV3 2018-12-31 0.4588246122822893
feito dict do ativo:  ABEV3 2017-12-31 0.587594465523369
feito dict do ativo:  ABEV3 2016-12-31 0.6475658938442502
feito dict do ativo:  ABEV3 2015-12-31 0.5948621071274975
feito dict do ativo:  ALOS3 2025-12-31 0.39483852927400404
feito dict do ativo:  ALOS3 2024-12-31 0.3900179383466277
feito dict do ativo:  ALOS3 2023-12-31 1.655507111089378
feito dict do ativo:  ALOS3 2022-12-31 0.0
feito dict do ativo:  ALOS3 2021-12-31 0.0
feito dict do ativo:  ALOS3 2020-12-31 0.0
feito dict do ativo:  ALOS3 2019-12-31 0.0
feito dict do ativo:  ALOS3 2018-12-31 0.0
feito dict do ativo:  ALOS3 2017-12-31 0.0
feito dict do ativo:  ALOS3 2016-12-31 0.0
feito dict do ativo:  ALOS3 2015-12-31 0.0
feito dict do ativo:  ANIM3 2025-12-31 0.25556441820558945
feito dict do ativo:  ANIM3 2024-12-31 0.2315847506268863
feito dict do ativo:  ANIM3 2023-12-31 0.19313851144755478
feito dict do ativo:  ANIM3 2022-12-31 0.10432490005158955
feito dict do ativo:  ANIM3 2021-12-31 0.08168585984839365
feito dict do ativo:  ANIM3 2020-12-31 0.03515403521780015
feito dict do ativo:  ANIM3 2019-12-31 0.0857844752210383
feito dict do ativo:  ANIM3 2018-12-31 0.06329913189703734
feito dict do ativo:  ANIM3 2017-12-31 0.14219407565774464
feito dict do ativo:  ANIM3 2016-12-31 0.11030780677083571
feito dict do ativo:  ANIM3 2015-12-31 0.1790137437211763
feito dict do ativo:  AXIA3 2025-12-31 0.039962129224727354
feito dict do ativo:  AXIA3 2024-12-31 0.22092668246503305
feito dict do ativo:  AXIA3 2023-12-31 0.1557060662619637
feito dict do ativo:  AXIA3 2022-12-31 0.0863949979860275
feito dict do ativo:  AXIA3 2021-12-31 0.1864886904823606
feito dict do ativo:  AXIA3 2020-12-31 0.1208797499579457
feito dict do ativo:  AXIA3 2019-12-31 0.1232061008742997
feito dict do ativo:  AXIA3 2018-12-31 0.290077106731664
feito dict do ativo:  AXIA3 2017-12-31 0.10261123234047846
feito dict do ativo:  AXIA3 2016-12-31 0.43765344807392387
feito dict do ativo:  AXIA3 2015-12-31 -0.2803575070611428
feito dict do ativo:  AZZA3 2025-12-31 0.17218008546705044
feito dict do ativo:  AZZA3 2024-12-31 0.06218776601061185
feito dict do ativo:  AZZA3 2023-12-31 0.22449677141697774
feito dict do ativo:  AZZA3 2022-12-31 0.2272988550799676
feito dict do ativo:  AZZA3 2021-12-31 0.4720334772463487
feito dict do ativo:  AZZA3 2020-12-31 0.23108633624637676
feito dict do ativo:  AZZA3 2019-12-31 0.1592624048085601
feito dict do ativo:  AZZA3 2018-12-31 0.16795910877337916
feito dict do ativo:  AZZA3 2017-12-31 0.1766990358270806
feito dict do ativo:  AZZA3 2016-12-31 0.18205100122835866
feito dict do ativo:  AZZA3 2015-12-31 0.18898138992582925
feito dict do ativo:  B3SA3 2025-12-31 0.3871316068593503
feito dict do ativo:  B3SA3 2024-12-31 0.47648693738333525
feito dict do ativo:  B3SA3 2023-12-31 0.37210588171393993
feito dict do ativo:  B3SA3 2022-12-31 0.35712235330546893
feito dict do ativo:  B3SA3 2021-12-31 0.40195673910410157
feito dict do ativo:  B3SA3 2020-12-31 0.3684393689516793
feito dict do ativo:  B3SA3 2019-12-31 0.5921164504448382
feito dict do ativo:  B3SA3 2018-12-31 0.5826283083132008
feito dict do ativo:  B3SA3 2017-12-31 0.5163726248617743
feito dict do ativo:  B3SA3 2016-12-31 0.15937331695474855
feito dict do ativo:  B3SA3 2015-12-31 0.6576070804644214
feito dict do ativo:  BBAS3 2025-12-31 0.0
feito dict do ativo:  BBAS3 2024-12-31 0.0
feito dict do ativo:  BBAS3 2023-12-31 0.0
feito dict do ativo:  BBAS3 2022-12-31 0.0
feito dict do ativo:  BBAS3 2021-12-31 0.0
feito dict do ativo:  BBAS3 2020-12-31 0.0
feito dict do ativo:  BBAS3 2019-12-31 0.0
feito dict do ativo:  BBAS3 2018-12-31 0.0
feito dict do ativo:  BBAS3 2017-12-31 0.0
feito dict do ativo:  BBAS3 2016-12-31 0.0
feito dict do ativo:  BBAS3 2015-12-31 0.0
feito dict do ativo:  BBDC3 2025-12-31 0.0
feito dict do ativo:  BBDC3 2024-12-31 0.0
feito dict do ativo:  BBDC3 2023-12-31 0.0
feito dict do ativo:  BBDC3 2022-12-31 0.0
feito dict do ativo:  BBDC3 2021-12-31 0.0
feito dict do ativo:  BBDC3 2020-12-31 0.0
feito dict do ativo:  BBDC3 2019-12-31 0.0
feito dict do ativo:  BBDC3 2018-12-31 0.0
feito dict do ativo:  BBDC3 2017-12-31 0.0
feito dict do ativo:  BBDC3 2016-12-31 0.0
feito dict do ativo:  BBDC3 2015-12-31 0.0
feito dict do ativo:  BBDC4 2025-12-31 0.0
feito dict do ativo:  BBDC4 2024-12-31 0.0
feito dict do ativo:  BBDC4 2023-12-31 0.0
feito dict do ativo:  BBDC4 2022-12-31 0.0
feito dict do ativo:  BBDC4 2021-12-31 0.0
feito dict do ativo:  BBDC4 2020-12-31 0.0
feito dict do ativo:  BBDC4 2019-12-31 0.0
feito dict do ativo:  BBDC4 2018-12-31 0.0
feito dict do ativo:  BBDC4 2017-12-31 0.0
feito dict do ativo:  BBDC4 2016-12-31 0.0
feito dict do ativo:  BBDC4 2015-12-31 0.0
feito dict do ativo:  BBSE3 2025-12-31 2.0753745252427933
feito dict do ativo:  BBSE3 2024-12-31 3.0855741501961327
feito dict do ativo:  BBSE3 2023-12-31 9.861036597674278
feito dict do ativo:  BBSE3 2022-12-31 2.6253644354066994
feito dict do ativo:  BBSE3 2021-12-31 1.4398233272468384
feito dict do ativo:  BBSE3 2020-12-31 1.935120903212727
feito dict do ativo:  BBSE3 2019-12-31 6.092117050040411
feito dict do ativo:  BBSE3 2018-12-31 0.8400804469030312
feito dict do ativo:  BBSE3 2017-12-31 0.7624327120127663
feito dict do ativo:  BBSE3 2016-12-31 8.30092303025193
feito dict do ativo:  BBSE3 2015-12-31 -9.966454847066405
feito dict do ativo:  BEEF3 2025-12-31 0.22275440679253722
feito dict do ativo:  BEEF3 2024-12-31 0.13633540112736775
feito dict do ativo:  BEEF3 2023-12-31 0.14820141315943686
feito dict do ativo:  BEEF3 2022-12-31 0.2043372704006172
feito dict do ativo:  BEEF3 2021-12-31 0.17651429087779055
feito dict do ativo:  BEEF3 2020-12-31 0.19014773505291754
feito dict do ativo:  BEEF3 2019-12-31 0.18250741296224826
feito dict do ativo:  BEEF3 2018-12-31 0.10176736813008516
feito dict do ativo:  BEEF3 2017-12-31 0.1324959052603814
feito dict do ativo:  BEEF3 2016-12-31 0.16588602705558053
feito dict do ativo:  BEEF3 2015-12-31 0.18094207031617432
feito dict do ativo:  BPAC11 2025-12-31 0.0
feito dict do ativo:  BPAC11 2024-12-31 0.0
feito dict do ativo:  BPAC11 2023-12-31 0.0
feito dict do ativo:  BPAC11 2022-12-31 0.0
feito dict do ativo:  BPAC11 2021-12-31 0.0
feito dict do ativo:  BPAC11 2020-12-31 0.0
feito dict do ativo:  BPAC11 2019-12-31 0.0
feito dict do ativo:  BPAC11 2018-12-31 0.0
feito dict do ativo:  BPAC11 2017-12-31 0.0
feito dict do ativo:  BPAC11 2016-12-31 0.0
feito dict do ativo:  BPAC11 2015-12-31 0.0
feito dict do ativo:  BRAP4 2025-12-31 1.1115547745521173
feito dict do ativo:  BRAP4 2024-12-31 2.470400155061656
feito dict do ativo:  BRAP4 2023-12-31 4.9314635082254155
feito dict do ativo:  BRAP4 2022-12-31 27.885003709821877
feito dict do ativo:  BRAP4 2021-12-31 17.109073129045967
feito dict do ativo:  BRAP4 2020-12-31 2.081669631543931
feito dict do ativo:  BRAP4 2019-12-31 -0.9425256772583969
feito dict do ativo:  BRAP4 2018-12-31 6.11076669813114
feito dict do ativo:  BRAP4 2017-12-31 -1.2312475629507134
feito dict do ativo:  BRAP4 2016-12-31 0.5662464360829212
feito dict do ativo:  BRAP4 2015-12-31 -4.348975686122801
feito dict do ativo:  BRAV3 2025-12-31 0.09670670756210739
feito dict do ativo:  BRAV3 2024-12-31 0.10315509685417465
feito dict do ativo:  BRAV3 2023-12-31 0.13210103832562364
feito dict do ativo:  BRAV3 2022-12-31 0.0609329492365719
feito dict do ativo:  BRAV3 2021-12-31 0.11294971673935439
feito dict do ativo:  BRAV3 2020-12-31 -0.10698610540329315
feito dict do ativo:  BRAV3 2019-12-31 -0.024633228048453998
feito dict do ativo:  BRAV3 2018-12-31 0.0
feito dict do ativo:  BRAV3 2017-12-31 0.0
feito dict do ativo:  BRAV3 2016-12-31 0.0
feito dict do ativo:  BRAV3 2015-12-31 0.0
feito dict do ativo:  BRKM5 2025-12-31 -0.043347576370339355
feito dict do ativo:  BRKM5 2024-12-31 -0.0176583349095655
feito dict do ativo:  BRKM5 2023-12-31 -0.04722649246317315
feito dict do ativo:  BRKM5 2022-12-31 0.07489015457393375
feito dict do ativo:  BRKM5 2021-12-31 0.3784709101685788
feito dict do ativo:  BRKM5 2020-12-31 -0.0013925977254297
feito dict do ativo:  BRKM5 2019-12-31 -0.00114130278796935
feito dict do ativo:  BRKM5 2018-12-31 0.2153183979479587
feito dict do ativo:  BRKM5 2017-12-31 0.25617875678497726
feito dict do ativo:  BRKM5 2016-12-31 0.20295425819644397
feito dict do ativo:  BRKM5 2015-12-31 0.17097534309555756
feito dict do ativo:  CMIG4 2025-12-31 0.8626841659439108
feito dict do ativo:  CMIG4 2024-12-31 2.844887848588837
feito dict do ativo:  CMIG4 2023-12-31 1.8729180458767898
feito dict do ativo:  CMIG4 2022-12-31 0.68426398729129
feito dict do ativo:  CMIG4 2021-12-31 0.825078050778421
feito dict do ativo:  CMIG4 2020-12-31 0.3386757696184143
feito dict do ativo:  CMIG4 2019-12-31 0.36473050381709654
feito dict do ativo:  CMIG4 2018-12-31 0.2068687712060877
feito dict do ativo:  CMIG4 2017-12-31 0.5469594898561008
feito dict do ativo:  CMIG4 2016-12-31 1.5017182660490214
feito dict do ativo:  CMIG4 2015-12-31 8.511375272326474
feito dict do ativo:  COGN3 2025-12-31 0.160382984661286
feito dict do ativo:  COGN3 2024-12-31 0.19175931014917658
feito dict do ativo:  COGN3 2023-12-31 0.0933006072765408
feito dict do ativo:  COGN3 2022-12-31 0.040444870179164996
feito dict do ativo:  COGN3 2021-12-31 0.0081185190259437
feito dict do ativo:  COGN3 2020-12-31 -0.2705394405693553
feito dict do ativo:  COGN3 2019-12-31 0.08212873205164929
feito dict do ativo:  COGN3 2018-12-31 0.14077940687357124
feito dict do ativo:  COGN3 2017-12-31 0.2392239869670402
feito dict do ativo:  COGN3 2016-12-31 0.33962787614040924
feito dict do ativo:  COGN3 2015-12-31 0.40836301686297805
feito dict do ativo:  CPFE3 2025-12-31 0.7379570414139054
feito dict do ativo:  CPFE3 2024-12-31 0.6858768201181811
feito dict do ativo:  CPFE3 2023-12-31 0.7118476207094178
feito dict do ativo:  CPFE3 2022-12-31 0.5808498528572436
feito dict do ativo:  CPFE3 2021-12-31 0.41195689348773773
feito dict do ativo:  CPFE3 2020-12-31 0.4113422671021893
feito dict do ativo:  CPFE3 2019-12-31 0.3137668380536196
feito dict do ativo:  CPFE3 2018-12-31 0.25214856456309465
feito dict do ativo:  CPFE3 2017-12-31 0.2670224277973613
feito dict do ativo:  CPFE3 2016-12-31 0.16447922084585945
feito dict do ativo:  CPFE3 2015-12-31 0.1513381079195136
feito dict do ativo:  CPLE3 2025-12-31 0.35789450256311467
feito dict do ativo:  CPLE3 2024-12-31 0.2291673869379505
feito dict do ativo:  CPLE3 2023-12-31 0.16517927908959856
feito dict do ativo:  CPLE3 2022-12-31 0.15987544414130034
feito dict do ativo:  CPLE3 2021-12-31 0.29282512146893763
feito dict do ativo:  CPLE3 2020-12-31 0.26529498938133717
feito dict do ativo:  CPLE3 2019-12-31 0.22799071840074864
feito dict do ativo:  CPLE3 2018-12-31 0.19267884943132818
feito dict do ativo:  CPLE3 2017-12-31 0.1949907888140957
feito dict do ativo:  CPLE3 2016-12-31 0.22440674056690169
feito dict do ativo:  CPLE3 2015-12-31 0.1927719936905758
feito dict do ativo:  CSAN3 2025-12-31 -0.0025293839862629
feito dict do ativo:  CSAN3 2024-12-31 0.0573015365516788
feito dict do ativo:  CSAN3 2023-12-31 0.21305091256424308
feito dict do ativo:  CSAN3 2022-12-31 0.14630662167698355
feito dict do ativo:  CSAN3 2021-12-31 0.16243843022901594
feito dict do ativo:  CSAN3 2020-12-31 0.22100376033628427
feito dict do ativo:  CSAN3 2019-12-31 0.39051932811624757
feito dict do ativo:  CSAN3 2018-12-31 0.42572784281725534
feito dict do ativo:  CSAN3 2017-12-31 0.5413177063043684
feito dict do ativo:  CSAN3 2016-12-31 0.5068078801098811
feito dict do ativo:  CSAN3 2015-12-31 0.5263275525639541
feito dict do ativo:  CSMG3 2025-12-31 0.5479194663048437
feito dict do ativo:  CSMG3 2024-12-31 0.5793886658138119
feito dict do ativo:  CSMG3 2023-12-31 0.5996375551384604
feito dict do ativo:  CSMG3 2022-12-31 0.47930950646770676
feito dict do ativo:  CSMG3 2021-12-31 0.31868783205967305
feito dict do ativo:  CSMG3 2020-12-31 0.4717908885237141
feito dict do ativo:  CSMG3 2019-12-31 0.4132221592182493
feito dict do ativo:  CSMG3 2018-12-31 0.29738858607048674
feito dict do ativo:  CSMG3 2017-12-31 0.3255230027013085
feito dict do ativo:  CSMG3 2016-12-31 0.6366174479328897
feito dict do ativo:  CSMG3 2015-12-31 0.3018761372504819
feito dict do ativo:  CSNA3 2025-12-31 0.10421314474457105
feito dict do ativo:  CSNA3 2024-12-31 0.08311858202002076
feito dict do ativo:  CSNA3 2023-12-31 0.1152115456072879
feito dict do ativo:  CSNA3 2022-12-31 0.19030181619044956
feito dict do ativo:  CSNA3 2021-12-31 0.5744687901856544
feito dict do ativo:  CSNA3 2020-12-31 0.1522132774564707
feito dict do ativo:  CSNA3 2019-12-31 0.12758828999431354
feito dict do ativo:  CSNA3 2018-12-31 0.28314013998003795
feito dict do ativo:  CSNA3 2017-12-31 0.1195325585865499
feito dict do ativo:  CSNA3 2016-12-31 0.0653118156720241
feito dict do ativo:  CSNA3 2015-12-31 0.17252612028428405
feito dict do ativo:  CVCB3 2025-12-31 -0.1529183670567973
feito dict do ativo:  CVCB3 2024-12-31 -0.16508983905276875
feito dict do ativo:  CVCB3 2023-12-31 0.7367005376552359
feito dict do ativo:  CVCB3 2022-12-31 0.0056565594801244005
feito dict do ativo:  CVCB3 2021-12-31 0.6668295804326098
feito dict do ativo:  CVCB3 2020-12-31 67.19655614275372
feito dict do ativo:  CVCB3 2019-12-31 0.9260341406524867
feito dict do ativo:  CVCB3 2018-12-31 0.3135478478054663
feito dict do ativo:  CVCB3 2017-12-31 0.38836828510497734
feito dict do ativo:  CVCB3 2016-12-31 0.8184530406197279
feito dict do ativo:  CVCB3 2015-12-31 0.7620389883713105
feito dict do ativo:  CXSE3 2025-12-31 2.772299921179611
feito dict do ativo:  CXSE3 2024-12-31 2.5775170465658714
feito dict do ativo:  CXSE3 2023-12-31 40.037099613108
feito dict do ativo:  CXSE3 2022-12-31 2.048093884925602
feito dict do ativo:  CXSE3 2021-12-31 1.311483773266576
feito dict do ativo:  CXSE3 2020-12-31 0.0
feito dict do ativo:  CXSE3 2019-12-31 0.0
feito dict do ativo:  CXSE3 2018-12-31 0.0
feito dict do ativo:  CXSE3 2017-12-31 0.0
feito dict do ativo:  CXSE3 2016-12-31 0.0
feito dict do ativo:  CXSE3 2015-12-31 0.0
feito dict do ativo:  CYRE3 2025-12-31 0.15699893346053145
feito dict do ativo:  CYRE3 2024-12-31 0.21225672190064665
feito dict do ativo:  CYRE3 2023-12-31 0.13923710809772735
feito dict do ativo:  CYRE3 2022-12-31 0.14325086689577265
feito dict do ativo:  CYRE3 2021-12-31 0.1736900316190976
feito dict do ativo:  CYRE3 2020-12-31 0.3873952300276515
feito dict do ativo:  CYRE3 2019-12-31 0.12388522797166604
feito dict do ativo:  CYRE3 2018-12-31 0.011443327860161251
feito dict do ativo:  CYRE3 2017-12-31 0.0037388193928721497
feito dict do ativo:  CYRE3 2016-12-31 0.047740370361733606
feito dict do ativo:  CYRE3 2015-12-31 0.1561925750552557
feito dict do ativo:  DIRR3 2025-12-31 0.13924379506737972
feito dict do ativo:  DIRR3 2024-12-31 0.17588285608866405
feito dict do ativo:  DIRR3 2023-12-31 0.1288285553510129
feito dict do ativo:  DIRR3 2022-12-31 0.14278186924494204
feito dict do ativo:  DIRR3 2021-12-31 0.1153943474778473
feito dict do ativo:  DIRR3 2020-12-31 0.0886336841085626
feito dict do ativo:  DIRR3 2019-12-31 0.0856297976895462
feito dict do ativo:  DIRR3 2018-12-31 -0.016560063630435003
feito dict do ativo:  DIRR3 2017-12-31 -0.0731736560182017
feito dict do ativo:  DIRR3 2016-12-31 0.00172583002023155
feito dict do ativo:  DIRR3 2015-12-31 0.10226420399241795
feito dict do ativo:  ECOR3 2025-12-31 0.8352830945049519
feito dict do ativo:  ECOR3 2024-12-31 -0.9414852374675213
feito dict do ativo:  ECOR3 2023-12-31 4.121450096560701
feito dict do ativo:  ECOR3 2022-12-31 -0.8666825387976875
feito dict do ativo:  ECOR3 2021-12-31 -0.6940130009974979
feito dict do ativo:  ECOR3 2020-12-31 -1.2617791059088466
feito dict do ativo:  ECOR3 2019-12-31 -0.326032056926091
feito dict do ativo:  ECOR3 2018-12-31 0.4232582546317755
feito dict do ativo:  ECOR3 2017-12-31 0.7038440695804218
feito dict do ativo:  ECOR3 2016-12-31 3.54260755813794
feito dict do ativo:  ECOR3 2015-12-31 1.878471340145306
feito dict do ativo:  EGIE3 2025-12-31 0.1515636884512122
feito dict do ativo:  EGIE3 2024-12-31 0.2318604152646736
feito dict do ativo:  EGIE3 2023-12-31 0.2326977742868507
feito dict do ativo:  EGIE3 2022-12-31 0.2549522938841564
feito dict do ativo:  EGIE3 2021-12-31 0.20452187085221518
feito dict do ativo:  EGIE3 2020-12-31 0.2287038984861624
feito dict do ativo:  EGIE3 2019-12-31 0.1914167335362545
feito dict do ativo:  EGIE3 2018-12-31 0.19525417446394
feito dict do ativo:  EGIE3 2017-12-31 0.22410823789263096
feito dict do ativo:  EGIE3 2016-12-31 0.19161797811614767
feito dict do ativo:  EGIE3 2015-12-31 0.0
feito dict do ativo:  EMBJ3 2025-12-31 0.08790322762018729
feito dict do ativo:  EMBJ3 2024-12-31 0.10866436786702804
feito dict do ativo:  EMBJ3 2023-12-31 0.0660813094404554
feito dict do ativo:  EMBJ3 2022-12-31 -0.0254347561978699
feito dict do ativo:  EMBJ3 2021-12-31 0.0358962109384138
feito dict do ativo:  EMBJ3 2020-12-31 -0.0675349171217357
feito dict do ativo:  EMBJ3 2019-12-31 -0.05223143404972465
feito dict do ativo:  EMBJ3 2018-12-31 0.00459771020271305
feito dict do ativo:  EMBJ3 2017-12-31 0.05065194120107945
feito dict do ativo:  EMBJ3 2016-12-31 0.0388944667777467
feito dict do ativo:  EMBJ3 2015-12-31 0.04466140102486585
feito dict do ativo:  ENEV3 2025-12-31 0.07753649398038825
feito dict do ativo:  ENEV3 2024-12-31 0.05659396329661905
feito dict do ativo:  ENEV3 2023-12-31 0.07491636862725021
feito dict do ativo:  ENEV3 2022-12-31 0.039081243819630795
feito dict do ativo:  ENEV3 2021-12-31 0.0872476707476512
feito dict do ativo:  ENEV3 2020-12-31 0.06581649974501315
feito dict do ativo:  ENEV3 2019-12-31 0.11100104915802744
feito dict do ativo:  ENEV3 2018-12-31 0.1671082855331812
feito dict do ativo:  ENEV3 2017-12-31 0.1207768523930544
feito dict do ativo:  ENEV3 2016-12-31 0.09761025650010044
feito dict do ativo:  ENEV3 2015-12-31 0.0
feito dict do ativo:  ENGI11 2025-12-31 0.32819112485823226
feito dict do ativo:  ENGI11 2024-12-31 0.48514361516406695
feito dict do ativo:  ENGI11 2023-12-31 0.660354555532051
feito dict do ativo:  ENGI11 2022-12-31 0.8685242631704135
feito dict do ativo:  ENGI11 2021-12-31 0.5723668912578656
feito dict do ativo:  ENGI11 2020-12-31 0.8491293999071269
feito dict do ativo:  ENGI11 2019-12-31 0.4575928608511293
feito dict do ativo:  ENGI11 2018-12-31 0.4014454389039089
feito dict do ativo:  ENGI11 2017-12-31 0.4162803072483684
feito dict do ativo:  ENGI11 2016-12-31 0.39020324361118947
feito dict do ativo:  ENGI11 2015-12-31 0.35024098821493865
feito dict do ativo:  EQTL3 2025-12-31 0.2957582891286056
feito dict do ativo:  EQTL3 2024-12-31 0.3255291576987439
feito dict do ativo:  EQTL3 2023-12-31 0.25391995102083303
feito dict do ativo:  EQTL3 2022-12-31 0.5906827974019332
feito dict do ativo:  EQTL3 2021-12-31 0.3274545431442362
feito dict do ativo:  EQTL3 2020-12-31 0.46115157220678576
feito dict do ativo:  EQTL3 2019-12-31 0.4657468984992479
feito dict do ativo:  EQTL3 2018-12-31 0.4254815586645191
feito dict do ativo:  EQTL3 2017-12-31 0.30842465089472826
feito dict do ativo:  EQTL3 2016-12-31 0.3385728923131457
feito dict do ativo:  EQTL3 2015-12-31 0.28649569902524197
feito dict do ativo:  EZTC3 2025-12-31 0.1287255040303249
feito dict do ativo:  EZTC3 2024-12-31 0.14876338488092128
feito dict do ativo:  EZTC3 2023-12-31 0.0809668383420163
feito dict do ativo:  EZTC3 2022-12-31 0.13540297947818136
feito dict do ativo:  EZTC3 2021-12-31 0.1637927315487179
feito dict do ativo:  EZTC3 2020-12-31 0.10267570168542796

In [13]:
score_todos_anos = dict_score_todos[0].rank(axis=1,pct=True)

In [14]:
score_todos_anos

,ABEV3,ALOS3,ANIM3,AXIA3,AZZA3,B3SA3,BBAS3,BBDC3,BBDC4,BBSE3,...,TAEE11,TEND3,TOTS3,UGPA3,USIM5,VALE3,VBBR3,VIVT3,WEGE3,YDUQ3
2015-12-31,0.884615,0.307692,0.641026,0.064103,0.692308,0.897436,0.307692,0.307692,0.307692,0.012821,...,0.948718,0.307692,0.769231,0.730769,0.051282,0.076923,0.307692,0.666667,0.564103,0.307692
2016-12-31,0.897436,0.243590,0.538462,0.833333,0.666667,0.602564,0.243590,0.243590,0.243590,1.000000,...,0.923077,0.243590,0.782051,0.679487,0.089744,0.551282,0.243590,0.730769,0.576923,0.243590
2017-12-31,0.910256,0.185897,0.551282,0.461538,0.628205,0.858974,0.185897,0.185897,0.185897,0.961538,...,0.820513,0.602564,0.576923,0.564103,0.371795,0.589744,0.185897,0.666667,0.474359,0.185897
2018-12-31,0.871795,0.173077,0.320513,0.756410,0.576923,0.884615,0.173077,0.173077,0.173077,0.961538,...,0.897436,0.538462,0.551282,0.346154,0.333333,0.602564,0.173077,0.730769,0.512821,0.173077
2019-12-31,0.833333,0.198718,0.448718,0.551282,0.679487,0.923077,0.198718,0.198718,0.198718,1.000000,...,0.807692,0.525641,0.512821,0.320513,0.333333,0.294872,0.198718,0.666667,0.602564,0.730769
2020-12-31,0.782051,0.179487,0.269231,0.525641,0.730769,0.794872,0.179487,0.179487,0.179487,0.961538,...,0.935897,0.500000,0.641026,0.358974,0.589744,0.602564,0.179487,0.564103,0.538462,0.307692
2021-12-31,0.717949,0.102564,0.269231,0.538462,0.794872,0.756410,0.102564,0.102564,0.102564,0.974359,...,0.987179,0.025641,0.384615,0.243590,0.807692,0.782051,0.410256,0.448718,0.487179,0.320513
2022-12-31,0.756410,0.115385,0.371795,0.307692,0.666667,0.743590,0.115385,0.115385,0.115385,0.987179,...,0.833333,0.025641,0.384615,0.615385,0.538462,0.717949,0.551282,0.448718,0.564103,0.410256
2023-12-31,0.794872,0.935897,0.538462,0.448718,0.628205,0.769231,0.096154,0.096154,0.096154,0.987179,...,0.833333,0.166667,0.384615,0.589744,0.179487,0.564103,0.730769,0.423077,0.576923,0.461538
2024-12-31,0.782051,0.794872,0.641026,0.615385,0.217949,0.820513,0.108974,0.108974,0.108974,1.000000,...,0.948718,0.435897,0.679487,0.705128,0.166667,0.538462,0.769231,0.371795,0.589744,0.564103
2025-12-31,0.846154,0.794872,0.705128,0.192308,0.551282,0.782051,0.108974,0.108974,0.108974,0.974359,...,0.935897,0.525641,0.692308,0.576923,0.025641,0.282051,0.397436,0.423077,0.628205,0.615385

In [15]:
index_novo = []
for indexx in score_todos_anos.index:
    novo = indexx.split('-')[0]
    index_novo.append(novo)
print(index_novo)

['2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

In [16]:
score_todos_anos.index=  index_novo

In [17]:
score_todos_anos.to_csv('score_mf/magic_formula.csv')