In [50]:
import pandas as pd

In [51]:
DATA_PRINCIPAL = ['2025-03-31', '2025-06-30', '2025-09-30']

## BPA --------- FEITO

In [52]:
df = pd.read_csv('bpa-2025.csv', sep=';', encoding='latin-1')
df=df[df['ORDEM_EXERC'] == 'ÚLTIMO']

In [53]:
df

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
1,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-03-31,1,Ativo Total,2.427052e+09,S
3,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-03-31,1.01,Caixa e Equivalentes de Caixa,7.151083e+07,S
5,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-03-31,1.01.01,Caixa,2.836636e+07,S
7,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-03-31,1.01.02,Aplicações de Liquidez,4.314448e+07,S
9,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-03-31,1.02,Ativos Financeiros,2.160717e+09,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181025,97.837.181/0001-47,2025-09-30,1,DEXCO S.A.,21091,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-09-30,1.02.04.02.09,Goodwill na aquisição da Massima Revestimentos...,6.110000e+03,N
181027,97.837.181/0001-47,2025-09-30,1,DEXCO S.A.,21091,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-09-30,1.02.04.02.10,Goodwill na aquisição da Cecrisa Revestimentos...,1.684300e+05,N
181029,97.837.181/0001-47,2025-09-30,1,DEXCO S.A.,21091,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-09-30,1.02.04.02.11,Goodwill Viva Decora,0.000000e+00,N
181031,97.837.181/0001-47,2025-09-30,1,DEXCO S.A.,21091,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-09-30,1.02.04.02.12,Goodwill na aquisição da Castelatto 2022,4.667000e+04,N
181033,97.837.181/0001-47,2025-09-30,1,DEXCO S.A.,21091,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-09-30,1.02.04.02.13,Goodwill na aquisição da Guarani Florestal 2025,2.446000e+04,N

In [54]:
lista_ativos = df['DENOM_CIA'].unique().tolist()
lista_final = []
data_refer = df['DT_REFER'].unique().tolist()
datas = df['DT_FIM_EXERC'].unique().tolist()
for ativo in lista_ativos:
    dfativo = df[df['DENOM_CIA']==ativo]
    
    caixa = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="1.01.01"')['VL_CONTA'].values
    ativo_total = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="1"')['VL_CONTA'].values
    

    if len(caixa) == 3 and len(ativo_total) == 3:
        dicio = {
            'ativo': ativo,
            
            f'caixa_{DATA_PRINCIPAL[0]}': caixa[0],
            f'caixa_{DATA_PRINCIPAL[1]}': caixa[1],
            f'caixa_{DATA_PRINCIPAL[2]}': caixa[2],
           

            f'ativo_total_{DATA_PRINCIPAL[0]}': ativo_total[0],
            f'ativo_total_{DATA_PRINCIPAL[1]}': ativo_total[1],
            f'ativo_total_{DATA_PRINCIPAL[2]}': ativo_total[2],
          

        
        }    
        lista_final.append(dicio)

In [55]:
df_bpa = pd.DataFrame(lista_final)
print(df_bpa.shape)
df_bpa.head()

(423, 7)

,ativo,caixa_2025-03-31,caixa_2025-06-30,caixa_2025-09-30,ativo_total_2025-03-31,ativo_total_2025-06-30,ativo_total_2025-09-30
0,BCO BRASIL S.A.,28366355.0,24468455.0,23732657.0,2.427052e+09,2.441421e+09,2.540770e+09
1,AXIA ENERGIA S.A.,23235009.0,22980254.0,18501361.0,2.820161e+08,2.749601e+08,2.665024e+08
2,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,681925.0,577724.0,486199.0,1.529712e+06,1.480516e+06,1.433244e+06
3,CARAMURU ALIMENTOS S.A.,1504595.0,760429.0,1846418.0,7.415662e+06,7.002071e+06,7.655100e+06
4,AUREN OPERAÇÕES S.A.,742038.0,1082926.0,977125.0,1.041356e+07,1.052999e+07,1.064951e+07

## BPP ------------ Fazendo

In [56]:
df2 = pd.read_csv('bpp-2025.csv', sep=';', encoding='latin-1')
df2=df2[df2['ORDEM_EXERC'] == 'ÚLTIMO']
df2.head()

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
1,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2025-03-31,2,Passivo Total,2.427052e+09,S
3,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2025-03-31,2.01,Passivos Financeiros Avaliados ao Valor Justo ...,5.098161e+06,S
5,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2025-03-31,2.02,Passivos Financeiros ao Custo Amortizado,2.135864e+09,S
7,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2025-03-31,2.02.01,Depósitos,8.649724e+08,S
9,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2025-03-31,2.02.02,Captações no Mercado Aberto,7.495654e+08,S

In [57]:
lista_ativos = df2['DENOM_CIA'].unique().tolist()
lista_final = []
data_refer = df2['DT_REFER'].unique().tolist()
datas = df2['DT_FIM_EXERC'].unique().tolist()
for ativo in lista_ativos:
    dfativo = df2[df2['DENOM_CIA']==ativo]
    # datas = dfativo['DT_REFER'].unique().tolist() 
    divida_cp = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="2.01.04"')['VL_CONTA'].values
    divida_lp = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="2.02.01"')['VL_CONTA'].values
    pl = dfativo.query('DT_FIM_EXERC==@DATA_PRINCIPAL and CD_CONTA=="2.03"')['VL_CONTA'].values

    if len(divida_cp) == 3 and len(divida_lp) == 3 and len(pl) == 3:
        dicio = {
            'ativo': ativo,
            
            f'divida_cp_{DATA_PRINCIPAL[0]}': divida_cp[0],
            f'divida_cp_{DATA_PRINCIPAL[1]}': divida_cp[1],
            f'divida_cp_{DATA_PRINCIPAL[2]}': divida_cp[2],
            
            
            f'divida_lp_{DATA_PRINCIPAL[0]}': divida_lp[0],
            f'divida_lp_{DATA_PRINCIPAL[1]}': divida_lp[1],
            f'divida_lp_{DATA_PRINCIPAL[2]}': divida_lp[2],
        
            
            f'pl_{DATA_PRINCIPAL[0]}': pl[0],
            f'pl_{DATA_PRINCIPAL[1]}': pl[1],
            f'pl_{DATA_PRINCIPAL[2]}': pl[2]
        
        }    
        lista_final.append(dicio)

In [58]:
df_bpp = pd.DataFrame(lista_final)
print(df_bpp.shape)
df_bpp.head()

(412, 10)

,ativo,divida_cp_2025-03-31,divida_cp_2025-06-30,divida_cp_2025-09-30,divida_lp_2025-03-31,divida_lp_2025-06-30,divida_lp_2025-09-30,pl_2025-03-31,pl_2025-06-30,pl_2025-09-30
0,AXIA ENERGIA S.A.,8750047.0,10944211.0,11210908.0,62313538.0,59345657.0,59625045.0,121577682.0,118754822.0,109340402.0
1,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,0.0,0.0,0.0,0.0,0.0,0.0,1377898.0,1318912.0,1247545.0
2,CARAMURU ALIMENTOS S.A.,1816453.0,1887354.0,1796545.0,1521246.0,1378235.0,1859507.0,2352745.0,2526941.0,2709193.0
3,AUREN OPERAÇÕES S.A.,1406119.0,1411244.0,1327750.0,3703186.0,3768827.0,3019375.0,3888873.0,3922687.0,4692809.0
4,"ARMAC LOCAÇÃO, LOGÍSTICA E SERVIÇOS S.A.",60100.0,95393.0,61861.0,2410424.0,2434294.0,2436423.0,1312437.0,1281222.0,1319396.0

## DRE ------------ Fazendo

In [59]:
df3 = pd.read_csv('dre-2025.csv', sep=';', encoding='latin-1')
df3=df3[df3['ORDEM_EXERC'] == 'ÚLTIMO']

In [60]:
print(df3.shape)
df3.head(200)

(78185, 15)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
1,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-03-31,3.01,Receitas de Intermediação Financeira,71720089.0,S
3,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-03-31,3.01.01,Receita de Juros,71720089.0,N
5,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-03-31,3.02,Despesas de Intermediação Financeira,-47952209.0,S
7,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-03-31,3.02.01,Despesa de Juros,-47952209.0,N
9,00.000.000/0001-91,2025-03-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-03-31,3.03,Resultado Bruto de Intermediação Financeira,23767880.0,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,00.000.208/0001-00,2025-03-31,2,BRB BANCO DE BRASILIA S.A.,14206,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-03-31,3.04.03,Despesas com Pessoal,-383826.0,S
393,00.000.208/0001-00,2025-03-31,2,BRB BANCO DE BRASILIA S.A.,14206,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-03-31,3.04.04,Outras Despesas de Administrativas,-188478.0,S
395,00.000.208/0001-00,2025-03-31,2,BRB BANCO DE BRASILIA S.A.,14206,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-03-31,3.04.05,Despesas Tributárias,-86269.0,S
397,00.000.208/0001-00,2025-03-31,2,BRB BANCO DE BRASILIA S.A.,14206,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-03-31,3.04.06,Outras Receitas Operacionais,0.0,S
399,00.000.208/0001-00,2025-03-31,2,BRB BANCO DE BRASILIA S.A.,14206,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2025-01-01,2025-03-31,3.04.07,Outras Despesas Operacionais,-111029.0,S

In [62]:
lista_ativos = df3['DENOM_CIA'].unique().tolist()
lista_final = []
for ativo in lista_ativos:
    dfativo = df3[df3['DENOM_CIA']==ativo]

    # RECEITA LIQUIDA 3.01

    dfativo_3_01 = dfativo[dfativo['CD_CONTA']=='3.01']
    datas_unicas_ini = dfativo_3_01['DT_INI_EXERC'].unique().tolist()
    datas_unicas_fim = dfativo_3_01['DT_FIM_EXERC'].unique().tolist()

    receita_liquida_total = []
    if len(datas_unicas_ini) == 3 and len(datas_unicas_fim) == 3:
        for i in range(len(datas_unicas_ini)):
            data_ini = datas_unicas_ini[i]
            data_fim = datas_unicas_fim[i]
            # print(f'Para o ativo {ativo}, a Data de início é {data_ini} e a data de fim é {data_fim}.')
            receita_liquida = dfativo_3_01.query('DT_INI_EXERC==@data_ini and DT_FIM_EXERC==@data_fim')['VL_CONTA'].values
            receita_liquida_total.extend(receita_liquida)
    
    # EBIT 3.05

    dfativo_3_05 = dfativo[dfativo['CD_CONTA']=='3.05']
    datas_unicas_ini_3_05 = dfativo_3_05['DT_INI_EXERC'].unique().tolist()
    datas_unicas_fim_3_05 = dfativo_3_05['DT_FIM_EXERC'].unique().tolist() 
    ebit_total = []
    if len(datas_unicas_ini_3_05) == 3 and len(datas_unicas_fim_3_05) == 3:
        for i in range(len(datas_unicas_ini_3_05)):
            data_ini = datas_unicas_ini_3_05[i]
            data_fim = datas_unicas_fim_3_05[i]
            # print(f'Para o ativo {ativo}, a Data de início é {data_ini} e a data de fim é {data_fim}.')
            ebit = dfativo_3_05.query('DT_INI_EXERC==@data_ini and DT_FIM_EXERC==@data_fim')['VL_CONTA'].values
            ebit_total.extend(ebit)

    #  LUCRO LIQUIDO 3.11

    dfativo_3_11 = dfativo[dfativo['CD_CONTA']=='3.11']
    datas_unicas_ini_3_11 = dfativo_3_11['DT_INI_EXERC'].unique().tolist()
    datas_unicas_fim_3_11 = dfativo_3_11['DT_FIM_EXERC'].unique().tolist() 
    lucro_liquido_total = []
    if len(datas_unicas_ini_3_11) == 3  and len(datas_unicas_fim_3_11) == 3:
        for i in range(len(datas_unicas_ini_3_11)):
            data_ini = datas_unicas_ini_3_11[i]
            data_fim = datas_unicas_fim_3_11[i]
            # print(f'Para o ativo {ativo}, a Data de início é {data_ini} e a data de fim é {data_fim}.')
            lucro_liquido = dfativo_3_11.query('DT_INI_EXERC==@data_ini and DT_FIM_EXERC==@data_fim')['VL_CONTA'].values
            lucro_liquido_total.extend(lucro_liquido)

    # print(f'Ativo: {ativo}')
    # print(f'Receita Líquida: {receita_liquida_total}')
    # print(f'EBIT: {ebit_total}')
    # print(f'Lucro Líquido: {lucro_liquido_total}')
    # print('-----------------------------')

    if len(receita_liquida_total) == 3 and len(ebit_total) == 3 and len(lucro_liquido_total) == 3:  
        dicio ={
            'ativo': ativo,
            f'receita_liquida_{DATA_PRINCIPAL[0]}': receita_liquida_total[0],
            f'receita_liquida_{DATA_PRINCIPAL[1]}': receita_liquida_total[1],
            f'receita_liquida_{DATA_PRINCIPAL[2]}': receita_liquida_total[2],

            f'ebit_{DATA_PRINCIPAL[0]}': ebit_total[0],
            f'ebit_{DATA_PRINCIPAL[1]}': ebit_total[1],
            f'ebit_{DATA_PRINCIPAL[2]}': ebit_total[2],

            f'lucro_liquido_{DATA_PRINCIPAL[0]}': lucro_liquido_total[0],
            f'lucro_liquido_{DATA_PRINCIPAL[1]}': lucro_liquido_total[1],
            f'lucro_liquido_{DATA_PRINCIPAL[2]}': lucro_liquido_total[2]
        }
        lista_final.append(dicio)

Ativo: BCO BRASIL S.A.
Receita Líquida: [71720089.0, 77532482.0, 84767065.0]
EBIT: [281839.0, 1361531.0, 929375.0]
Lucro Líquido: [4177854.0, 3582262.0, 3006743.0]
-----------------------------
Ativo: BRB BANCO DE BRASILIA S.A.
Receita Líquida: []
EBIT: []
Lucro Líquido: []
-----------------------------
Ativo: AXIA ENERGIA S.A.
Receita Líquida: [10414179.0, 10198955.0, 10002503.0]
EBIT: [3205299.0, 127334.0, -2650621.0]
Lucro Líquido: [-353614.0, -1325105.0, -5448117.0]
-----------------------------
Ativo: COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB
Receita Líquida: [135294.0, 128514.0, 123057.0]
EBIT: [68140.0, 54936.0, 52379.0]
Lucro Líquido: [64394.0, 59286.0, 53637.0]
-----------------------------
Ativo: CARAMURU ALIMENTOS S.A.
Receita Líquida: [1764715.0, 1992560.0, 2287804.0]
EBIT: [58252.0, 129986.0, 270811.0]
Lucro Líquido: [115708.0, 174196.0, 202252.0]
-----------------------------
Ativo: AUREN OPERAÇÕES S.A.
Receita Líquida: [831230.0, 855338.0, 935249.0]
EBIT: [237966.0, 149586.0, 83253.0]
Lucro Líquido: [13546.0, 7137.0, 14239.0]
-----------------------------
Ativo: ARMAC LOCAÇÃO, LOGÍSTICA E SERVIÇOS S.A.
Receita Líquida: [439917.0, 451467.0, 494579.0]
EBIT: [92427.0, 82075.0, 140264.0]
Lucro Líquido: [12512.0, -6715.0, 38304.0]
-----------------------------
Ativo: AXIA ENERGIA NORTE S.A.
Receita Líquida: [2868784.0, 2777695.0, 2584737.0]
EBIT: [754329.0, 269838.0, 1712012.0]
Lucro Líquido: [-165311.0, 32663.0, 1215131.0]
-----------------------------
Ativo: FICTOR ALIMENTOS S.A.
Receita Líquida: []
EBIT: []
Lucro Líquido: []
-----------------------------
Ativo: LM TRANSPORTES INTERESTADUAIS SERVIÇOS E COMÉRCIO S.A.
Receita Líquida: [1048933.0, 1220260.0, 1446044.0]
EBIT: [368889.0, 410408.0, 462102.0]
Lucro Líquido: [27222.0, 6088.0, 9094.0]
-----------------------------
Ativo: AMERICANAS S.A. - EM RECUPERAÇÃO JUDICIAL
Receita Líquida: [3058000.0, 3843000.0, 2690000.0]
EBIT: [-284000.0, 82000.0, 324000.0]
Lucro Líquido: [-496000.0, -98000.0, 367000.0]
-----------------------------
Ativo: ENERGISA S.A.
Receita Líquida: [8409616.0, 8563865.0, 9181985.0]
EBIT: [1911607.0, 1676739.0, 1683933.0]
Lucro Líquido: [1026715.0, 489761.0, 648430.0]
-----------------------------
Ativo: CIELO S.A. -  INSTITUIÇÃO DE PAGAMENTO
Receita Líquida: [2591937.0, 2714790.0, 2803608.0]
EBIT: [546717.0, 447469.0, 474445.0]
Lucro Líquido: [464656.0, 347696.0, 416875.0]
-----------------------------
Ativo: NEOENERGIA S.A.
Receita Líquida: [12285000.0, 12856000.0, 13485000.0]
EBIT: [2996000.0, 2448000.0, 2659000.0]
Lucro Líquido: [1006000.0, 1640000.0, 930000.0]
-----------------------------
Ativo: BBM LOGÍSTICA S.A.
Receita Líquida: [315491.0, 336604.0, 350237.0]
EBIT: [-3256.0, -2382.0, 6392.0]
Lucro Líquido: [-43812.0, -45601.0, -40074.0]
-----------------------------
Ativo: MRS LOGISTICA S.A.
Receita Líquida: [1676602.0, 1930890.0, 2029040.0]
EBIT: [582362.0, 759939.0, 808556.0]
Lucro Líquido: [282716.0, 482234.0, 460675.0]
-----------------------------
Ativo: GAFISA S.A.
Receita Líquida: [226841.0, 162291.0, 120832.0]
EBIT: [-19553.0, 43716.0, -71308.0]
Lucro Líquido: [21138.0, 6825.0, -92114.0]
-----------------------------
Ativo: SEQUOIA LOGÍSTICA E TRANSPORTES S.A.
Receita Líquida: [153642.0, 157528.0, 152389.0]
EBIT: [115838.0, -61704.0, -59132.0]
Lucro Líquido: [101153.0, -120753.0, -105049.0]
-----------------------------
Ativo: VOTORANTIM CIMENTOS S.A.
Receita Líquida: [5620000.0, 7451000.0, 8678000.0]
EBIT: [-123000.0, 1098000.0, 1683000.0]
Lucro Líquido: [-325000.0, 1804000.0, 967000.0]
-----------------------------
Ativo: BRF S.A.
Receita Líquida: [15512021.0, 15364631.0, 16397194.0]
EBIT: [1884532.0, 1580083.0, 1619053.0]
Lucro Líquido: [1185070.0, 734921.0, 790064.0]
-----------------------------
Ativo: CSU DIGITAL S.A.
Receita Líquida: [150692.0, 154705.0, 153698.0]
EBIT: [32041.0, 32014.0, 30477.0]
Lucro Líquido: [24434.0, 23680.0, 23801.0]
-----------------------------
Ativo: LIGHT ENERGIA S.A.
Receita Líquida: [158149.0, 155038.0, 180266.0]
EBIT: [90338.0, 86635.0, 39483.0]
Lucro Líquido: [84183.0, 85541.0, 5937.0]
-----------------------------
Ativo: CIA PARTICIPACOES ALIANCA DA BAHIA
Receita Líquida: [26511.0, 30909.0, 29697.0]
EBIT: [2841.0, 12946.0, 5982.0]
Lucro Líquido: [2809.0, 10648.0, 7903.0]
-----------------------------
Ativo: SUL 116 PARTICIPACOES S.A.
Receita Líquida: [0.0, 0.0, 0.0]
EBIT: [-142.0, -14.0, 5.0]
Lucro Líquido: [-144.0, -29.0, -18.0]
-----------------------------
Ativo: ELETRORIVER S.A.
Receita Líquida: [175712.0, 181015.0, 185954.0]
EBIT: [129246.0, 133579.0, 136893.0]
Lucro Líquido: [59558.0, 88658.0, 98361.0]
-----------------------------
Ativo: AXIA ENERGIA SUL S.A.
Receita Líquida: [786362.0, 819702.0, 763495.0]
EBIT: [343351.0, 81014.0, 582067.0]
Lucro Líquido: [183286.0, 21839.0, 440639.0]
-----------------------------
Ativo: V. TAL - REDE NEUTRA DE TELECOMUNICAÇÕES S.A.
Receita Líquida: [1900440.0, 1828379.0, 1828563.0]
EBIT: [87290.0, -467635.0, -711709.0]
Lucro Líquido: [24036.0, -380256.0, -343666.0]
-----------------------------
Ativo: PORTO SEGURO S.A.
Receita Líquida: [9705869.0, 10047836.0, 10487450.0]
EBIT: [836945.0, 820410.0, 795869.0]
Lucro Líquido: [845446.0, 889710.0, 842650.0]
-----------------------------
Ativo: DEXXOS PARTICIPAÇÕES S.A.
Receita Líquida: [603154.0, 597308.0, 516678.0]
EBIT: [82316.0, 61892.0, 43652.0]
Lucro Líquido: [52601.0, 38904.0, 29455.0]
-----------------------------
Ativo: CEL PARTICIPAÇÕES S.A. - CELPAR
Receita Líquida: [20114496.0, 18630544.0, 20061875.0]
EBIT: [4784375.0, 2959029.0, 3415308.0]
Lucro Líquido: [48169.0, 23302.0, 43525.0]
-----------------------------
Ativo: YBYRÁ CAPITAL S.A.
Receita Líquida: [0.0, 0.0, 0.0]
EBIT: [290257.0, -32340.0, -32340.0]
Lucro Líquido: [290280.0, -32340.0, -32340.0]
-----------------------------
Ativo: UNIFIQUE TELECOMUNICAÇÕES S.A.
Receita Líquida: [269713.0, 286142.0, 306218.0]
EBIT: [71427.0, 77473.0, 87345.0]
Lucro Líquido: [36978.0, 45168.0, 64831.0]
-----------------------------
Ativo: INEPAR EQUIPAMENTOS E MONTAGENS S/A - EM RECUPERACAO JUDICIA
Receita Líquida: [60.0, 1698.0, 1758.0]
EBIT: [-642.0, -6175.0, -70.0]
Lucro Líquido: [-935.0, -4249.0, -499.0]
-----------------------------
Ativo: LOCALIZA FLEET S.A.
Receita Líquida: [2377124.0, 2547967.0, 2806118.0]
EBIT: [743014.0, 752498.0, 606924.0]
Lucro Líquido: [287602.0, 264043.0, 146554.0]
-----------------------------
Ativo: PRODUTORES ENERGET.DE MANSO S.A.- PROMAN
Receita Líquida: [2209.0, 2208.0, 2209.0]
EBIT: [1305.0, 1168.0, 1338.0]
Lucro Líquido: [57.0, 53.0, 58.0]
-----------------------------
Ativo: EMAE - EMPRESA METROP. DE AGUAS E ENERGIA S.A.
Receita Líquida: [148450.0, 159555.0, 154256.0]
EBIT: [26226.0, 29995.0, 291444.0]
Lucro Líquido: [34379.0, 31668.0, 287470.0]
-----------------------------
Ativo: TEGMA GESTAO LOGISTICA S.A.
Receita Líquida: [440357.0, 540540.0, 634223.0]
EBIT: [60161.0, 88586.0, 108616.0]
Lucro Líquido: [43734.0, 67119.0, 79891.0]
-----------------------------
Ativo: LWSA S/A
Receita Líquida: [348890.0, 370776.0, 387405.0]
EBIT: [31948.0, 35244.0, -398796.0]
Lucro Líquido: [14808.0, 15808.0, -287827.0]
-----------------------------
Ativo: LIFEMED INDUSTRIAL DE EQUIP. E ART. MEDICOS E HOSP. S.A
Receita Líquida: [26681.0, 29601.0, 31791.0]
EBIT: [2096.0, 4500.0, 8200.0]
Lucro Líquido: [-3670.0, 239.0, 2426.0]
-----------------------------
Ativo: PADTEC HOLDING S.A.
Receita Líquida: [72301.0, 73009.0, 76563.0]
EBIT: [3002.0, 158.0, 9742.0]
Lucro Líquido: [-50.0, -7906.0, 4094.0]
-----------------------------
Ativo: RUMO S.A.
Receita Líquida: [2966750.0, 3711393.0, 3819265.0]
EBIT: [792804.0, 1311835.0, 1428983.0]
Lucro Líquido: [-97176.0, 333257.0, 415896.0]
-----------------------------
Ativo: CPFL ENERGIA S.A.
Receita Líquida: [10655220.0, 10549126.0, 11329141.0]
EBIT: [3261606.0, 2425258.0, 2564850.0]
Lucro Líquido: [1615392.0, 1185802.0, 1376387.0]
-----------------------------
Ativo: ENGIE BRASIL ENERGIA S.A.
Receita Líquida: [3013069.0, 3086121.0, 3343256.0]
EBIT: [1722276.0, 1540469.0, 1527372.0]
Lucro Líquido: [826349.0, 567456.0, 738105.0]
-----------------------------
Ativo: VITAL ENGENHARIA AMBIENTAL S.A.
Receita Líquida: [555669.0, 579366.0, 565777.0]
EBIT: [132175.0, 107072.0, 139808.0]
Lucro Líquido: [96808.0, 70623.0, 97895.0]
-----------------------------
Ativo: TELEFÔNICA BRASIL S.A
Receita Líquida: [14390273.0, 14645092.0, 14949056.0]
EBIT: [1984968.0, 2244555.0, 2768653.0]
Lucro Líquido: [1056270.0, 1338805.0, 1887220.0]
-----------------------------
Ativo: HOSPITAL ANCHIETA S.A.
Receita Líquida: [140591.0, 148325.0, 150327.0]
EBIT: [-1974.0, 49423.0, 24341.0]
Lucro Líquido: [-36781.0, 7602.0, -16409.0]
-----------------------------
Ativo: TIM BRASIL SERVIÇOS E PARTICIPAÇÕES S.A.
Receita Líquida: [6393641.0, 6599933.0, 6710987.0]
EBIT: [1291403.0, 1547990.0, 1664055.0]
Lucro Líquido: [596911.0, 804960.0, 878301.0]
-----------------------------
Ativo: JALLES MACHADO S.A.
Receita Líquida: [505096.0, 640689.0, 515327.0]
EBIT: [-164692.0, 80070.0, 38718.0]
Lucro Líquido: [-13963.0, 18918.0, 55414.0]
-----------------------------
Ativo: SANTOS BRASIL PARTICIPACOES S.A.
Receita Líquida: [883648.0, 880911.0, 920437.0]
EBIT: [425130.0, 381321.0, 424253.0]
Lucro Líquido: [198458.0, 193376.0, 231479.0]
-----------------------------
Ativo: COGNA EDUCAÇÃO S.A.
Receita Líquida: [1627628.0, 1664600.0, 1523369.0]
EBIT: [301790.0, 300056.0, 198369.0]
Lucro Líquido: [94248.0, 105897.0, 177957.0]
-----------------------------
Ativo: MOTIVA INFRAESTRUTURA DE MOBILIDADE S.A.
Receita Líquida: [4595872.0, 4662280.0, 6347121.0]
EBIT: [1899754.0, 1649224.0, 3081306.0]
Lucro Líquido: [549283.0, 884434.0, 1419122.0]
-----------------------------
Ativo: T4F ENTRETENIMENTO S.A.
Receita Líquida: [22952.0, 54398.0, 33016.0]
EBIT: [-4895.0, 1402.0, -21222.0]
Lucro Líquido: [-11893.0, -105.0, -25940.0]
-----------------------------
Ativo: JBS S.A.
Receita Líquida: [114127485.0, 118973531.0, 123099514.0]
EBIT: [5176368.0, 6310877.0, 6668902.0]
Lucro Líquido: [3251604.0, 3411057.0, 3505224.0]
-----------------------------
Ativo: ARTERIS S.A.
Receita Líquida: [1324977.0, 1345118.0, 1532300.0]
EBIT: [153373.0, 233215.0, 311059.0]
Lucro Líquido: [-343532.0, -196425.0, -132676.0]
-----------------------------
Ativo: HYPERA S.A.
Receita Líquida: [1080906.0, 2153937.0, 2227247.0]
EBIT: [-226039.0, 646656.0, 677205.0]
Lucro Líquido: [-141142.0, 425414.0, 456076.0]
-----------------------------
Ativo: PDG REALTY S.A. EMPREEND E PARTICIPACOES
Receita Líquida: [25108.0, 29333.0, 37714.0]
EBIT: [7053.0, -7844.0, -10835.0]
Lucro Líquido: [-103784.0, -82089.0, 22588.0]
-----------------------------
Ativo: ISA ENERGIA BRASIL
Receita Líquida: [2412040.0, 1432874.0, 2558971.0]
EBIT: [1265841.0, 407966.0, 1279675.0]
Lucro Líquido: [724705.0, 232275.0, 802797.0]
-----------------------------
Ativo: TPI - TRIUNFO PARTICIP. E INVEST. S.A.
Receita Líquida: [275574.0, 255552.0, 284372.0]
EBIT: [25153.0, 15903.0, 37314.0]
Lucro Líquido: [-10966.0, -40964.0, -23435.0]
-----------------------------
Ativo: EQUATORIAL S.A.
Receita Líquida: [11709093.0, 12795327.0, 14145096.0]
EBIT: [2399395.0, 2964999.0, 2391714.0]
Lucro Líquido: [706281.0, 1289635.0, 609805.0]
-----------------------------
Ativo: ORIZON MEIO AMBIENTE S.A.
Receita Líquida: [199696.0, 217930.0, 231222.0]
EBIT: [43412.0, 60107.0, 62074.0]
Lucro Líquido: [961.0, 25983.0, 19446.0]
-----------------------------
Ativo: PETRORECÔNCAVO S.A.
Receita Líquida: [860752.0, 806302.0, 786385.0]
EBIT: [259765.0, 178405.0, 157604.0]
Lucro Líquido: [227529.0, 238139.0, 121937.0]
-----------------------------
Ativo: LIGHT S.A. - EM RECUPERAÇÃO JUDICIAL
Receita Líquida: [3742196.0, 3456412.0, 3631313.0]
EBIT: [653051.0, 97048.0, 261587.0]
Lucro Líquido: [419248.0, -51444.0, 32617.0]
-----------------------------
Ativo: INVESTIMENTOS E PARTICIP. EM INFRA S.A. - INVEPAR
Receita Líquida: [884471.0, 945210.0, 993448.0]
EBIT: [357147.0, 471054.0, 457642.0]
Lucro Líquido: [-90505.0, 128926.0, 215787.0]
-----------------------------
Ativo: CLEAR SALE S.A.
Receita Líquida: []
EBIT: []
Lucro Líquido: []
-----------------------------
Ativo: MARFRIG GLOBAL FOODS S.A.
Receita Líquida: [39405009.0, 38692048.0, 41765532.0]
EBIT: [1273644.0, 1107327.0, 1574947.0]
Lucro Líquido: [424620.0, 197092.0, 183478.0]
-----------------------------
Ativo: CPFL GERACAO DE ENERGIA S.A.
Receita Líquida: [1053599.0, 354164.0, 386414.0]
EBIT: [624185.0, 312146.0, 499090.0]
Lucro Líquido: [388114.0, 260498.0, 408357.0]
-----------------------------
Ativo: EDP - ENERGIAS DO BRASIL S.A.
Receita Líquida: [4563475.0, 4691940.0, 5432713.0]
EBIT: [1086964.0, 810971.0, 1289102.0]
Lucro Líquido: [512394.0, 417029.0, 728644.0]
-----------------------------
Ativo: CONTAX PARTICIPAÇÕES S.A. - EM RECUPERAÇÃO JUDICIAL
Receita Líquida: [109460.0, 112241.0, 112436.0]
EBIT: [-23842.0, 17783.0, 2942.0]
Lucro Líquido: [-41917.0, -3072.0, -15262.0]
-----------------------------
Ativo: BRZ EMPREENDIMENTOS E CONSTRUÇÕES S.A.
Receita Líquida: [250658.0, 304962.0, 262772.0]
EBIT: [28337.0, 43837.0, -26510.0]
Lucro Líquido: [17451.0, 23924.0, -45155.0]
-----------------------------
Ativo: BIONEXO S.A.
Receita Líquida: [48243.0, 49418.0, 51183.0]
EBIT: [-2381.0, -2478.0, -1563.0]
Lucro Líquido: [-1143.0, -818.0, 371.0]
-----------------------------
Ativo: ECORODOVIAS INFRAESTRUTURA E LOGÍSTICA S.A.
Receita Líquida: [2426119.0, 2718137.0, 2993330.0]
EBIT: [930515.0, 1003813.0, 1309163.0]
Lucro Líquido: [136679.0, 199251.0, 431304.0]
-----------------------------
Ativo: VOKE S.A.
Receita Líquida: [138076.0, 136942.0, 132944.0]
EBIT: [78137.0, 48564.0, 42843.0]
Lucro Líquido: [20274.0, 339.0, -10458.0]
-----------------------------
Ativo: COPEL GERAÇÃO E TRANSMISSÃO S.A.
Receita Líquida: [1239546.0, 1161384.0, 1252299.0]
EBIT: [821297.0, 759033.0, 560291.0]
Lucro Líquido: [416045.0, 365513.0, 249324.0]
-----------------------------
Ativo: ENEVA S.A
Receita Líquida: [4423556.0, 3513980.0, 4428021.0]
EBIT: [972874.0, 1006542.0, 1062599.0]
Lucro Líquido: [468859.0, 485949.0, 544696.0]
-----------------------------
Ativo: BRISANET SERVIÇOS DE TELECOMUNICAÇÕES S.A.
Receita Líquida: [391583.0, 410216.0, 433610.0]
EBIT: [65257.0, 54641.0, 94474.0]
Lucro Líquido: [20445.0, 6219.0, 38382.0]
-----------------------------
Ativo: BTG PACTUAL COMMODITIES SERTRADING S.A.
Receita Líquida: [3796761.0, 10613171.0, 10597889.0]
EBIT: [76244.0, 91065.0, 12820.0]
Lucro Líquido: [116098.0, 418602.0, 301508.0]
-----------------------------
Ativo: BIOMM S.A.
Receita Líquida: [39591.0, 27174.0, 35761.0]
EBIT: [-12836.0, -12836.0, -11285.0]
Lucro Líquido: [-11735.0, -13737.0, -10598.0]
-----------------------------
Ativo: METALFRIO SOLUTIONS S.A.
Receita Líquida: [543602.0, 702073.0, 600025.0]
EBIT: [33096.0, 63218.0, 52485.0]
Lucro Líquido: [-9198.0, 27318.0, 12992.0]
-----------------------------
Ativo: GRUPO FARTURA DE HORTIFRUT S.A.
Receita Líquida: [772823.0, 761193.0, 795981.0]
EBIT: [53711.0, 42187.0, 48951.0]
Lucro Líquido: [20810.0, 12347.0, 16740.0]
-----------------------------
Ativo: SER EDUCACIONAL S.A.
Receita Líquida: [539989.0, 589237.0, 514451.0]
EBIT: [115036.0, 129490.0, 74413.0]
Lucro Líquido: [43633.0, 81326.0, 14919.0]
-----------------------------
Ativo: HAPVIDA PARTICIPAÇÕES E INVESTIMENTOS S.A.
Receita Líquida: [1469235.0, 862763.0, 7918125.0]
EBIT: [671024.0, 145252.0, 351145.0]
Lucro Líquido: [185897.0, -331511.0, 87109.0]
-----------------------------
Ativo: UNIGEL PARTICIPAÇÕES S.A.
Receita Líquida: []
EBIT: []
Lucro Líquido: []
-----------------------------
Ativo: ALLOS S.A.
Receita Líquida: [649842.0, 697295.0, 678318.0]
EBIT: [447683.0, 345599.0, 345757.0]
Lucro Líquido: [278103.0, 229938.0, 155922.0]
-----------------------------
Ativo: LIVETECH DA BAHIA INDÚSTRIA E COMÉRCIO S.A.
Receita Líquida: [213555.0, 222235.0, 222303.0]
EBIT: [27351.0, 8212.0, 9170.0]
Lucro Líquido: [8149.0, -16744.0, -2535.0]
-----------------------------
Ativo: REDE D'OR SÃO LUIZ S.A.
Receita Líquida: [12973032.0, 13960847.0, 14415537.0]
EBIT: [2206277.0, 2271518.0, 2748411.0]
Lucro Líquido: [1066778.0, 1047761.0, 1538127.0]
-----------------------------
Ativo: GOL LINHAS AEREAS INTELIGENTES S.A.
Receita Líquida: [5628768.0, 4836945.0, 5536574.0]
EBIT: [536459.0, -348557.0, 850100.0]
Lucro Líquido: [1376364.0, -1531832.0, 247842.0]
-----------------------------
Ativo: COMPANHIA BRASILEIRA DE EDUCAÇÃO E SISTEMA DE ENSINO S.A.
Receita Líquida: []
EBIT: []
Lucro Líquido: []
-----------------------------
Ativo: SBF COMÉRCIO DE PRODUTOS ESPORTIVOS S.A.
Receita Líquida: [2199046.0, 2767478.0, 3167287.0]
EBIT: [151891.0, 210682.0, 267554.0]
Lucro Líquido: [90887.0, 126825.0, 195495.0]
-----------------------------
Ativo: EMPREENDIMENTOS PAGUE MENOS S.A.
Receita Líquida: [3370706.0, 3693371.0, 3853222.0]
EBIT: [140704.0, 229562.0, 251001.0]
Lucro Líquido: [5095.0, 50343.0, 75982.0]
-----------------------------
Ativo: BR MALLS PARTICIPACOES S.A.
Receita Líquida: [374800.0, 407181.0, 393796.0]
EBIT: [254651.0, 278068.0, 273454.0]
Lucro Líquido: [144469.0, 153019.0, 142827.0]
-----------------------------
Ativo: CEMIG GERACAO E TRANSMISSAO S.A.
Receita Líquida: [1702854.0, 1752437.0, 1796540.0]
EBIT: [665096.0, 322028.0, 447518.0]
Lucro Líquido: [541277.0, 342120.0, 386500.0]
-----------------------------
Ativo: CTC - CENTRO DE TECNOLOGIA CANAVIEIRA S.A.
Receita Líquida: [110588.0, 117221.0, 121794.0]
EBIT: [40398.0, 57977.0, 46809.0]
Lucro Líquido: [49177.0, 67836.0, 59545.0]
-----------------------------
Ativo: CLARO TELECOM PARTICIPAÇÕES S.A.
Receita Líquida: [12511427.0, 12830698.0, 13058754.0]
EBIT: [2489613.0, 2642334.0, 2748330.0]
Lucro Líquido: [1342722.0, 1102795.0, 1047971.0]
-----------------------------
Ativo: M.DIAS BRANCO S.A. IND COM DE ALIMENTOS
Receita Líquida: [2208908.0, 2723395.0, 2784387.0]
EBIT: [65240.0, 242027.0, 216801.0]
Lucro Líquido: [69409.0, 216382.0, 216077.0]
-----------------------------
Ativo: ELDORADO BRASIL CELULOSE S.A.
Receita Líquida: [1623756.0, 1455678.0, 1390404.0]
EBIT: [680067.0, 693311.0, 274627.0]
Lucro Líquido: [458501.0, 751418.0, 458121.0]
-----------------------------
Ativo: SIMPAR S.A.
Receita Líquida: [10531165.0, 10611623.0, 11390347.0]
EBIT: [1791520.0, 1855709.0, 1797578.0]
Lucro Líquido: [11521.0, -42923.0, -237989.0]
-----------------------------
Ativo: AMBEV S.A.
Receita Líquida: [22497378.0, 20090194.0, 20847262.0]
EBIT: [5712727.0, 4393661.0, 6299885.0]
Lucro Líquido: [3804649.0, 2790566.0, 4863720.0]
-----------------------------
Ativo: SMARTFIT ESCOLA DE GINÁSTICA E DANÇA S.A.
Receita Líquida: [1678174.0, 1791140.0, 1824155.0]
EBIT: [380500.0, 429540.0, 431029.0]
Lucro Líquido: [120947.0, 160889.0, 144268.0]
-----------------------------
Ativo: BRASILAGRO - CIA BRAS DE PROP AGRICOLAS
Receita Líquida: []
EBIT: []
Lucro Líquido: []
-----------------------------
Ativo: CONCESSIONÁRIA DA LINHA 4 DO METRÔ DE SÃO PAULO S.A.
Receita Líquida: [302154.0, 275905.0, 1157806.0]
EBIT: [191244.0, 167099.0, 1036674.0]
Lucro Líquido: [96305.0, 81014.0, 659474.0]
-----------------------------
Ativo: EMBRAER S.A.
Receita Líquida: [6405270.0, 10270363.0, 10866683.0]
EBIT: [295867.0, 1017361.0, 859869.0]
Lucro Líquido: [470895.0, 397478.0, 688122.0]
-----------------------------
Ativo: GIGA MAIS FIBRA TELECOMUNICAÇÕES S.A.
Receita Líquida: [433972.0, 443436.0, 426144.0]
EBIT: [81372.0, 77924.0, 8240.0]
Lucro Líquido: [-3605.0, -11491.0, -63050.0]
-----------------------------
Ativo: ESSENTIA PCHS S.A.
Receita Líquida: [86118.0, 82483.0, 82568.0]
EBIT: [61176.0, 52727.0, 46811.0]
Lucro Líquido: [24092.0, 26558.0, 15333.0]
-----------------------------
Ativo: MULTIPLAN - EMPREEND IMOBILIARIOS S.A.
Receita Líquida: [525677.0, 694056.0, 617538.0]
EBIT: [361754.0, 426550.0, 403691.0]
Lucro Líquido: [234085.0, 264390.0, 221163.0]
-----------------------------
Ativo: FICA EMPREENDIMENTOS IMOBILIÁRIOS S.A.
Receita Líquida: [46.0, 54.0, -345.0]

In [63]:
df_dre = pd.DataFrame(lista_final)
df_dre.head()

,ativo,receita_liquida_2025-03-31,receita_liquida_2025-06-30,receita_liquida_2025-09-30,ebit_2025-03-31,ebit_2025-06-30,ebit_2025-09-30,lucro_liquido_2025-03-31,lucro_liquido_2025-06-30,lucro_liquido_2025-09-30
0,BCO BRASIL S.A.,71720089.0,77532482.0,84767065.0,281839.0,1361531.0,929375.0,4177854.0,3582262.0,3006743.0
1,AXIA ENERGIA S.A.,10414179.0,10198955.0,10002503.0,3205299.0,127334.0,-2650621.0,-353614.0,-1325105.0,-5448117.0
2,COMPANHIA ENERGÉTICA DE BRASÍLIA - CEB,135294.0,128514.0,123057.0,68140.0,54936.0,52379.0,64394.0,59286.0,53637.0
3,CARAMURU ALIMENTOS S.A.,1764715.0,1992560.0,2287804.0,58252.0,129986.0,270811.0,115708.0,174196.0,202252.0
4,AUREN OPERAÇÕES S.A.,831230.0,855338.0,935249.0,237966.0,149586.0,83253.0,13546.0,7137.0,14239.0

In [64]:
print(df_bpa.info())
print(df_bpp.info())
print(df_dre.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 423 entries, 0 to 422
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ativo                   423 non-null    object
 1   caixa_2025-03-31        423 non-null    float64
 2   caixa_2025-06-30        423 non-null    float64
 3   caixa_2025-09-30        423 non-null    float64
 4   ativo_total_2025-03-31  423 non-null    float64
 5   ativo_total_2025-06-30  423 non-null    float64
 6   ativo_total_2025-09-30  423 non-null    float64
dtypes: float64(6), object(1)
memory usage: 23.3+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 412 entries, 0 to 411
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ativo                 412 non-null    object
 1   divida_cp_2025-03-31  412 non-null    float64
 2   divida_cp_2025-06-30  412 non-null    float64
 3   divida_cp_2025-09-30  412 non-null    float64
 4   divida_lp_2025-03-31  412 non-null    float64
 5   divida_lp_2025-06-30  412 non-null    float64
 6   divida_lp_2025-09-30  412 non-null    float64
 7   pl_2025-03-31         412 non-null    float64
 8   pl_2025-06-30         412 non-null    float64
 9   pl_2025-09-30         412 non-null    float64
dtypes: float64(9), object(1)
memory usage: 32.3+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 428 entries, 0 to 427
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ativo                       428 non-null    object
 1   receita_liquida_2025-03-31  428 non-null    float64
 2   receita_liquida_2025-06-30  428 non-null    float64
 3   receita_liquida_2025-09-30  428 non-null    float64
 4   ebit_2025-03-31             428 non-null    float64
 5   ebit_2025-06-30             428 non-null    float64
 6   ebit_2025-09-30             428 non-null    float64
 7   lucro_liquido_2025-03-31    428 non-null    float64
 8   lucro_liquido_2025-06-30    428 non-null    float64
 9   lucro_liquido_2025-09-30    428 non-null    float64
dtypes: float64(9), object(1)
memory usage: 33.6+ KB
None

In [65]:
df_final = df_bpa.merge(df_bpp, on="ativo", how="inner") \
           .merge(df_dre, on="ativo", how="inner")

print(df_bpa.shape)
print(df_bpp.shape)
print(df_dre.shape)
print('----')
print(df_final.shape)

(423, 7)
(412, 10)
(428, 10)
----
(411, 25)

In [67]:
df_final.to_excel('dados_final_2025.xlsx', index=False)