In [1]:
import pandas as pd
import numpy as np
import random
import pyomo.environ as pyo
from pyomo.environ import *
from pyomo.environ import SolverFactory
import yfinance as yf
from pathlib import Path
import os
import matplotlib.pyplot as plt

In [2]:
anos = ['2025-12-31',
 '2024-12-31',
 '2023-12-31',
 '2022-12-31',
 '2021-12-31',
 '2020-12-31',
 '2019-12-31',
 '2018-12-31',
 '2017-12-31',
 '2016-12-31',
 '2015-12-31',
 ]

## LER OS RETORNOS, SCORE e SELIC

In [3]:
# Retornos

dfs = {}
for ano in anos:
    ano_usado = ano.split('-')[0]
    nome = f'df_ativos_{ano_usado}.csv'
    caminho = Path('../retornos_ativos_otimizacao') / nome
    dfs[ano_usado] = pd.read_csv(caminho).set_index('date')
    dfs[ano_usado] = dfs[ano_usado].drop(columns=dfs[ano_usado].columns[(dfs[ano_usado] == 0).all()])
    print(ano,'-',len(dfs[ano_usado].columns))

2025-12-31 - 78
2024-12-31 - 78
2023-12-31 - 78
2022-12-31 - 77
2021-12-31 - 77
2020-12-31 - 73
2019-12-31 - 73
2018-12-31 - 70
2017-12-31 - 70
2016-12-31 - 67
2015-12-31 - 62

In [4]:
## SELIC para Sigma e excesso
selic_d = pd.read_csv('../selic/selic_diario.csv').set_index('date')

In [5]:
selic_d

            valor_anual  valor_diario
date
2026-07-23        14.25       0.01087
2026-07-22        14.25       0.01087
2026-07-21        14.25       0.01087
2026-07-20        14.25       0.01087
2026-07-19        14.25       0.01087
...                 ...           ...
2016-01-05        14.25       0.01087
2016-01-04        14.25       0.01087
2016-01-03        14.25       0.01087
2016-01-02        14.25       0.01087
2016-01-01        14.25       0.01087

[3857 rows x 2 columns]

In [6]:
##### EXCESSO PARA TODOS
dict_excesso = {}
for an in anos:
    ano = an.split("-")[0]

    try:
        print(f"=============== \n EXCESSO {ano}\n ============")
        print("Atualização, Ano: ",ano)
        df = dfs[ano]
        # df_f = pd.DataFrame(eval(df))
        df_f = df.copy()
        slc = selic_d[selic_d.index.isin(df_f.index)]
        slc['valor_diario'] = slc['valor_diario']/100

        print(f"Tamanho DF de {ano}: ", len(df_f))
        print(f"Tamanho Selic: ", len(slc['valor_diario']))
        ano = int(ano)
        dict_excesso[ano] = df_f.sub(slc['valor_diario'],axis=0)
        print("tamanho final do Excesso: ",len(dict_excesso[ano]))

        print(f"============\n SIGMA {ano}\n===========")            

    except Exception as e:
        print(e)
        print("ERror")

===============
 EXCESSO 2025
 ============
Atualização, Ano:  2025
Tamanho DF de 2025:  123
Tamanho Selic:  123
tamanho final do Excesso:  123
============
 SIGMA 2025
===========
===============
 EXCESSO 2024
 ============
Atualização, Ano:  2024
Tamanho DF de 2024:  122
Tamanho Selic:  122
tamanho final do Excesso:  122
============
 SIGMA 2024
===========
===============
 EXCESSO 2023
 ============
Atualização, Ano:  2023
Tamanho DF de 2023:  121
Tamanho Selic:  121
tamanho final do Excesso:  121
============
 SIGMA 2023
===========
===============
 EXCESSO 2022
 ============
Atualização, Ano:  2022
Tamanho DF de 2022:  124
Tamanho Selic:  124
tamanho final do Excesso:  124
============
 SIGMA 2022
===========
===============
 EXCESSO 2021
 ============
Atualização, Ano:  2021
Tamanho DF de 2021:  123
Tamanho Selic:  123
tamanho final do Excesso:  123
============
 SIGMA 2021
===========
===============
 EXCESSO 2020
 ============
Atualização, Ano:  2020
Tamanho DF de 2020:  120
Tamanho Selic:  120
tamanho final do Excesso:  120
============
 SIGMA 2020
===========
===============
 EXCESSO 2019
 ============
Atualização, Ano:  2019
Tamanho DF de 2019:  123
Tamanho Selic:  123
tamanho final do Excesso:  123
============
 SIGMA 2019
===========
===============
 EXCESSO 2018
 ============
Atualização, Ano:  2018
Tamanho DF de 2018:  119
Tamanho Selic:  119
tamanho final do Excesso:  119
============
 SIGMA 2018
===========
===============
 EXCESSO 2017
 ============
Atualização, Ano:  2017
Tamanho DF de 2017:  119
Tamanho Selic:  119
tamanho final do Excesso:  119
============
 SIGMA 2017
===========
===============
 EXCESSO 2016
 ============
Atualização, Ano:  2016
Tamanho DF de 2016:  123
Tamanho Selic:  123
tamanho final do Excesso:  123
============
 SIGMA 2016
===========
===============
 EXCESSO 2015
 ============
Atualização, Ano:  2015
Tamanho DF de 2015:  120
Tamanho Selic:  60
tamanho final do Excesso:  120
============
 SIGMA 2015
===========

In [7]:
vb_cardinalidade_max = 10
vb_cardinalidade_min = 10
vb_peso_maximo = 0.20
vb_peso_minimo = 0.02
vb_theta = 0.5

## MODEO FINAL COM TODOS OS ANOS

In [34]:
y = []
carteiras_anuais = {}
melhor_pesos = None
historico = []
carteiras_criadas = []
for a in anos:
    y.append(a.split('-')[0])
print("=-"*48)
print("Anos totais: ",y)
print("=-"*48)
lista_ativos_finais = {}
for an in anos:
    ano = an.split("-")[0]
    ano_int = int(ano)
    print("COMEÇANDO ANO NOVO: ",ano)
    #deletar modelo
    if 'model' in locals():
        del model
        print('Modelo Antigo deletado \n Iniciando Novo')
    else:
        print("Nao consta model")
        pass
    try:
        #SCORE MF------------
        score_todos_anos = pd.read_csv(f'../score_mf/{ano}/mf_{ano}.csv').set_index('ano')
        score_usado = score_todos_anos.dropna(axis=1).copy()

        score_min = score_usado.min().min()
        score_max = score_usado.max().max()
        media_score = np.array(score_usado).mean()
        # print(score_usado)
        print("Score Atualizado")
        print("Score Min:",score_min)
        print("Score MAX:",score_max)

        # retorno_usado = pd.DataFrame(eval(df_usado))
        df_usado = dfs[str(ano_int)]
        retorno_usado = df_usado[score_usado.columns].copy()

        # COV
        df_cov = retorno_usado.cov()
        print("VARIANCIA Atualizado")
        
        # Lista ativos
        lista_ativos_finais[ano] = retorno_usado.columns.tolist()


    except Exception as e:
            print("=========ERRRRRRRRRRRROR")
            print(e)    

    print("# ------ CRIAÇÃO DO MODELO")
    print("## Carteira criada para o ano: ",ano_int+1)
    print("## UTILIZANDO DADOS DE RETORNO DE: ",ano)

    #  --------- MODELO
    model = pyo.ConcreteModel()
    #---------VARIÁVEIS-----------
    model.nome_ativos = pyo.Set(initialize = retorno_usado.columns)
    model.ativos = pyo.RangeSet(0, len(retorno_usado.columns)-1)
    model.dias = pyo.RangeSet(0, len(retorno_usado)-1)
    model.retornos_ativos = pyo.Param(model.dias, model.ativos, initialize=lambda model,dia, ativo: retorno_usado.iloc[dia, ativo])    
    model.sigma = pyo.Param(model.ativos, model.ativos, initialize=lambda model,a,b: df_cov.iloc[a,b])
    model.sigma_min = pyo.Param(initialize=0, mutable=True)
    model.sigma_max = pyo.Param(initialize=1, mutable=True)
    model.score = pyo.Param(model.ativos, initialize=lambda model,a: score_usado.iloc[0,a])
    model.theta = pyo.Param(initialize=vb_theta)
    # model.score_min = pyo.Param(initialize=score_min)
    # model.score_max = pyo.Param(initialize=score_max)
    model.score_m = pyo.Param(initialize= media_score)
    #linearizar Sharpe
    # z:= kx
    model.z = pyo.Var(model.ativos, domain=pyo.NonNegativeReals)
    model.k = pyo.Var(domain=pyo.NonNegativeReals)
    model.y = pyo.Var(model.ativos, domain=pyo.Binary)
    model.w = pyo.Var(model.ativos, domain=pyo.NonNegativeReals)
    model.KMAX = pyo.Param(initialize=100)

    # Com a problemática de cardinalidade y e bilinearidade, resolve-se
    # PESO
    # antes era model.x[a] <= model.pesomax * model.y[a]
    #  z=kx  -> model.z[a] <= model.pesomax * modely[a] * model.k[a]
    # CARDINALIDADE
    # era sum(model.y[a] ...) >= e <=

    # Com y=0
    def res_y_zero(model,a):
        return model.w[a] <= model.KMAX * model.y[a]
    model.y_zero = pyo.Constraint(model.ativos, rule=res_y_zero)

    # com y=1
        #  segundo teto
    def res_y_1_teto2(model,a):
        return model.w[a] <= model.k 
    model.res_teto2 = pyo.Constraint(model.ativos, rule=res_y_1_teto2)

        # Limite inf 1
    def limite_1(model,a):
        return model.w[a] >= model.k - model.KMAX*(1-model.y[a])
    model.r_limite1 = pyo.Constraint(model.ativos, rule=limite_1)

    #  PESOS MIN MAX
    def pesomin(model,a):
        return model.z[a] >= vb_peso_minimo * model.w[a]
    model.r_pesomin = pyo.Constraint(model.ativos, rule=pesomin)

    def pesomax(model,a):
        return model.z[a] <= vb_peso_maximo * model.w[a]
    model.r_pesomax = pyo.Constraint(model.ativos, rule=pesomax)

    #  cardinalidade
    def card_min(model):
        return sum(model.y[a] for a in model.ativos) >= vb_cardinalidade_min
    model.r_cardmin = pyo.Constraint(rule=card_min)
    def card_max(model):
        return sum(model.y[a] for a in model.ativos) <= vb_cardinalidade_max
    model.r_card_max = pyo.Constraint(rule=card_max)

    # Restrições Sharpe
    def restricao_z(model):
        return sum(model.z[a] for a in model.ativos) == model.k
    model.r_restricao_z = pyo.Constraint(rule=restricao_z)

    def restricao_z_retorno(model):
        return sum(sum(model.retornos_ativos[t,a]*model.z[a] for a in model.ativos) for t in model.dias) == 1
    model.r_res_z_retorno = pyo.Constraint(rule=restricao_z_retorno)
    
    def score_r(model):
        return sum(model.score[a]*model.y[a] for a in model.ativos) >= vb_cardinalidade_max * model.score_m
    model.r_score = pyo.Constraint(rule=score_r)
    ## OBJETIVOS:  1 para pegar z min, 2 para z max, 3 para normalização
    def obj_1(model):
        var = sum(model.sigma[a,b]*model.z[a]*model.z[b] for a in model.ativos for b in model.ativos)
        # var_normalisum(model.y[a] * model.score[a] for a in model.ativos)
        return var
    model.obj1 = pyo.Objective(rule=obj_1, sense=pyo.minimize)
    # ------------------- solver 1
    opt = SolverFactory('cplex', executable='C:\\Program Files\\IBM\\ILOG\\CPLEX_Studio_Community222\\cplex\\bin\\x64_win64\\cplex.exe')
    res = opt.solve(model,tee=True,symbolic_solver_labels=True)
    model.write('modelo_debug.lp', io_options={'symbolic_solver_labels': True})
    # if res.opt.termination_condition  == pyo.TerminationCondition.optimal:
    #     print(f"-----MODELO FOI RESOLVIDO {an}------------")
    # else:
    #     print(f"MODEO NAO FOI RESOLVIDO {an}----------")
    melhor_pesos = {list(model.nome_ativos.data())[a]:(model.z[a].value/model.k.value) for a in model.ativos}
    carteiras_anuais[ano_int+1] = {
        'pesos':  melhor_pesos,
        'z[a]': {a:model.z[a].value for a in model.ativos},
        'score': {a:model.score[a] for a in model.ativos}
        # 'sharpe_anual': s_lo*np.sqrt(252),
    }

    print(f"{ano} -> {melhor_pesos}")
    print("+-="*30)
    print("=====================")
    print(model.display())
    print("=====================")
    if 'model' in locals():
        del model
        print('DELETADO DPS DO WHILE')
    else:
        print("Nao consta model")
        pass

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Anos totais:  ['2025', '2024', '2023', '2022', '2021', '2020', '2019', '2018', '2017', '2016', '2015']
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
COMEÇANDO ANO NOVO:  2025
Modelo Antigo deletado
 Iniciando Novo
Score Atualizado
Score Min: 0.0
Score MAX: 1.0
VARIANCIA Atualizado
# ------ CRIAÇÃO DO MODELO
## Carteira criada para o ano:  2026
## UTILIZANDO DADOS DE RETORNO DE:  2025

Welcome to IBM(R) ILOG(R) CPLEX(R) Interactive Optimizer Community Edition 22.2.0.0
  with Simplex, Mixed Integer & Barrier Optimizers
5725-A06 5725-A29 5724-Y48 5724-Y49 5724-Y54 5724-Y55 5655-Y21
Copyright IBM Corp. 1988, 2026.  All Rights Reserved.

Type 'help' for a list of available commands.
Type 'help' followed by a command name for more
information on commands.

CPLEX> Logfile 'cplex.log' closed.
Logfile 'C:\Users\Pichau\AppData\Local\Temp\tmp_cy45p4f.cplex.log' open.
CPLEX> Problem 'C:\Users\Pichau\AppData\Local\Temp\tmpoof2l9ot.pyomo.lp' read.
Read time = 0.00 sec. (0.32 ticks)
CPLEX> Problem name         : C:\Users\Pichau\AppData\Local\Temp\tmpoof2l9ot.pyomo.lp
Objective sense      : Minimize
Variables            :     211  [Nneg: 141,  Binary: 70,  Qobj: 70]
Objective nonzeros   :       0
Objective Q nonzeros :    4900
Linear constraints   :     355  [Less: 351,  Greater: 2,  Equal: 2]
  Nonzeros           :    1120
  RHS nonzeros       :      74

Variables            : Min LB: 0.000000         Max UB: 1.000000
Objective nonzeros   : Min   : all zero         Max   : all zero
Objective Q nonzeros : Min   : 7.509035e-07     Max   : 0.003935287
Linear constraints   :
  Nonzeros           : Min   : 0.002610014      Max   : 100.0000
  RHS nonzeros       : Min   : 1.000000         Max   : 100.0000
CPLEX> Version identifier: 22.2.0.0 | 2026-05-04 | 5dff98e58
Tried aggregator 1 time.
MIQP Presolve eliminated 1 rows and 0 columns.
MIQP Presolve modified 70 coefficients.
Reduced MIQP has 354 rows, 211 columns, and 1049 nonzeros.
Reduced MIQP has 70 binaries, 0 generals, 0 SOSs, and 0 indicators.
Reduced MIQP objective Q matrix has 4900 nonzeros.
Presolve time = 0.00 sec. (1.48 ticks)
Probing fixed 0 vars, tightened 1 bounds.
Probing time = 0.00 sec. (0.31 ticks)
Cover probing fixed 0 vars, tightened 1 bounds.
Tried aggregator 1 time.
Reduced MIQP has 354 rows, 211 columns, and 1049 nonzeros.
Reduced MIQP has 70 binaries, 0 generals, 0 SOSs, and 0 indicators.
Reduced MIQP objective Q matrix has 4900 nonzeros.
Presolve time = 0.00 sec. (1.03 ticks)
Classifier predicts products in MIQP should not be linearized.
Represolve...

Tried aggregator 1 time.
MIQP Presolve eliminated 1 rows and 0 columns.
MIQP Presolve modified 70 coefficients.
Reduced MIQP has 354 rows, 211 columns, and 1049 nonzeros.
Reduced MIQP has 70 binaries, 0 generals, 0 SOSs, and 0 indicators.
Reduced MIQP objective Q matrix has 4900 nonzeros.
Presolve time = 0.00 sec. (1.42 ticks)
Probing fixed 0 vars, tightened 1 bounds.
Probing time = 0.00 sec. (0.31 ticks)
Cover probing fixed 0 vars, tightened 1 bounds.
Tried aggregator 1 time.
Reduced MIQP has 354 rows, 211 columns, and 1049 nonzeros.
Reduced MIQP has 70 binaries, 0 generals, 0 SOSs, and 0 indicators.
Reduced MIQP objective Q matrix has 4900 nonzeros.
Presolve time = 0.00 sec. (0.97 ticks)
Probing time = 0.00 sec. (0.27 ticks)
Cover probing fixed 0 vars, tightened 1 bounds.
MIP emphasis: balance optimality and feasibility.
MIP search method: dynamic search.
Parallel mode: deterministic, using up to 12 threads.
Root relaxation solution time = 0.00 sec. (8.29 ticks)

        Nodes                                         Cuts/
   Node  Left     Objective  IInf  Best Integer    Best Bound    ItCnt     Gap

      0     0        0.0004    19                      0.0004       17
*     0+    0                            0.0031        0.0004            87.25%
      0     0        0.0004     6        0.0031      Cuts: 21      123   87.23%
*     0+    0                            0.0004        0.0004            10.04%
      0     0        0.0004     2        0.0004       Cuts: 9      137   10.04%
*     0+    0                            0.0004        0.0004             0.20%
*     0+    0                            0.0004        0.0004             0.16%

Implied bound cuts applied:  22
Mixed integer rounding cuts applied:  1

Root node processing (before b&c):
  Real time             =    0.05 sec. (30.43 ticks)
Parallel b&c, 12 threads:
  Real time             =    0.00 sec. (0.00 ticks)
  Sync time (average)   =    0.00 sec.
  Wait time (average)   =    0.00 sec.
                          ------------
Total (root+branch&cut) =    0.05 sec. (30.43 ticks)

Solution pool: 4 solutions saved.

MIP - Integer optimal, tolerance (0.0001/1e-06):  Objective =  3.9343304884e-04
Current MIP best bound =  3.9280262524e-04 (gap = 6.30424e-07, 0.16%)
Solution time =    0.05 sec.  Iterations = 137  Nodes = 0 (1)
Deterministic time = 30.43 ticks  (647.36 ticks/sec)

CPLEX> Incumbent solution written to file 'C:\Users\Pichau\AppData\Local\Temp\tmp574i1qc1.cplex.sol'.
CPLEX> 2025 -> {'ABEV3': 0.15946063460456097, 'ALOS3': 0.0, 'ANIM3': 0.0, 'AXIA3': 0.0, 'AZZA3': 0.0, 'B3SA3': 0.0, 'BBSE3': 0.0, 'BEEF3': 0.0, 'BRAP4': 0.020000000000000004, 'BRAV3': 0.0, 'BRKM5': 0.0, 'CMIG4': 0.0, 'COGN3': 0.0, 'CPFE3': 0.0, 'CPLE3': 0.0, 'CSAN3': 0.0, 'CSMG3': 0.19395893925088395, 'CSNA3': 0.0, 'CVCB3': 0.0, 'CXSE3': 0.019999999999999997, 'CYRE3': 0.0, 'DIRR3': 0.0, 'ECOR3': 0.0, 'EGIE3': 0.0, 'EMBJ3': 0.0, 'ENEV3': 0.0, 'ENGI11': 0.0, 'EQTL3': 0.0, 'EZTC3': 0.0, 'FLRY3': 0.0, 'GGBR4': 0.0, 'GOAU4': 0.0, 'HYPE3': 0.0, 'IGTI11': 0.0, 'IRBR3': 0.0, 'ISAE4': 0.0, 'ITSA4': 0.0, 'JHSF3': 0.0, 'KLBN11': 0.0, 'LREN3': 0.0, 'MDNE3': 0.0, 'MGLU3': 0.0, 'MOTV3': 0.0, 'MOVI3': 0.0, 'MRVE3': 0.0, 'MULT3': 0.0, 'PETR3': 0.0, 'PETR4': 0.1535094462092954, 'POMO4': 0.0, 'PRIO3': 0.16757923149520945, 'PSSA3': 0.0, 'RADL3': 0.0, 'RAIL3': 0.0, 'RAPT4': 0.0, 'RENT3': 0.0, 'SAPR11': 0.0, 'SBSP3': 0.0, 'SLCE3': 0.08452295441892378, 'SMFT3': 0.0, 'SUZB3': 0.0, 'TAEE11': 0.0, 'TEND3': 0.0, 'TOTS3': 0.0, 'UGPA3': 0.0, 'USIM5': 0.046157107673453886, 'VALE3': 0.08943223476244334, 'VBBR3': 0.0, 'VIVT3': 0.0, 'WEGE3': 0.06537945158522905, 'YDUQ3': 0.0}
+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=+-=
=====================
Model unknown

  Variables:
    z : Size=70, Index=ativos
        Key : Lower : Value                : Upper : Fixed : Stale : Domain
          0 :     0 :  0.35032455345621943 :  None : False : False : NonNegativeReals
          1 :     0 :                  0.0 :  None : False : False : NonNegativeReals
          2 :     0 :                  0.0 :  None : False : False : NonNegativeReals
          3 :     0 :                  0.0 :  None : False : False : NonNegativeReals
          4 :     0 :                  0.0 :  None : False : False : NonNegativeReals
          5 :     0 :                  0.0 :  None : False : False : NonNegativeReals
          6 :     0 :                  0.0 :  None : False : False : NonNegativeReals
          7 :     0 :                  0.0 :  None : False : False : NonNegativeReals
          8 :     0 : 0.043938687980889214 :  None : False : False : NonNegativeReals
          9 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         10 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         11 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         12 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         13 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         14 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         15 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         16 :     0 :   0.4261150656424417 :  None : False : False : NonNegativeReals
         17 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         18 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         19 :     0 :   0.0439386879808892 :  None : False : False : NonNegativeReals
         20 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         21 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         22 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         23 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         24 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         25 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         26 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         27 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         28 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         29 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         30 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         31 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         32 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         33 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         34 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         35 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         36 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         37 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         38 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         39 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         40 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         41 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         42 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         43 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         44 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         45 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         46 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         47 :     0 :   0.3372501829554663 :  None : False : False : NonNegativeReals
         48 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         49 :     0 :  0.36816057823726045 :  None : False : False : NonNegativeReals
         50 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         51 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         52 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         53 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         54 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         55 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         56 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         57 :     0 :  0.18569138607180063 :  None : False : False : NonNegativeReals
         58 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         59 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         60 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         61 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         62 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         63 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         64 :     0 :  0.10140413760820986 :  None : False : False : NonNegativeReals
         65 :     0 :  0.19647675293303155 :  None : False : False : NonNegativeReals
         66 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         67 :     0 :                  0.0 :  None : False : False : NonNegativeReals
         68 :     0 :  0.14363436617825157 :  None : False : False : NonNegativeReals
         69 :     0 :                  0.0 :  None : False : False : NonNegativeReals
    k : Size=1, Index=None
        Key  : Lower : Value              : Upper : Fixed : Stale : Domain
        None :     0 : 2.1969343990444603 :  None : False : False : NonNegativeReals
    y : Size=70, Index=ativos
        Key : Lower : Value : Upper : Fixed : Stale : Domain
          0 :     0 :   1.0 :     1 : False : False : Binary
          1 :     0 :  -0.0 :     1 : False : False : Binary
          2 :     0 :  -0.0 :     1 : False : False : Binary
          3 :     0 :  -0.0 :     1 : False : False : Binary
          4 :     0 :  -0.0 :     1 : False : False : Binary
          5 :     0 :  -0.0 :     1 : False : False : Binary
          6 :     0 :  -0.0 :     1 : False : False : Binary
          7 :     0 :  -0.0 :     1 : False : False : Binary
          8 :     0 :   1.0 :     1 : False : False : Binary
          9 :     0 :  -0.0 :     1 : False : False : Binary
         10 :     0 :  -0.0 :     1 : False : False : Binary
         11 :     0 :  -0.0 :     1 : False : False : Binary
         12 :     0 :  -0.0 :     1 : False : False : Binary
         13 :     0 :  -0.0 :     1 : False : False : Binary
         14 :     0 :  -0.0 :     1 : False : False : Binary
         15 :     0 :  -0.0 :     1 : False : False : Binary
         16 :     0 :   1.0 :     1 : False : False : Binary
         17 :     0 :  -0.0 :     1 : False : False : Binary
         18 :     0 :   0.0 :     1 : False : False : Binary
         19 :     0 :   1.0 :     1 : False : False : Binary
         20 :     0 :  -0.0 :     1 : False : False : Binary
         21 :     0 :  -0.0 :     1 : False : False : Binary
         22 :     0 :  -0.0 :     1 : False : False : Binary
         23 :     0 :  -0.0 :     1 : False : False : Binary
         24 :     0 :  -0.0 :     1 : False : False : Binary
         25 :     0 :   0.0 :     1 : False : False : Binary
         26 :     0 :  -0.0 :     1 : False : False : Binary
         27 :     0 :  -0.0 :     1 : False : False : Binary
         28 :     0 :  -0.0 :     1 : False : False : Binary
         29 :     0 :  -0.0 :     1 : False : False : Binary
         30 :     0 :  -0.0 :     1 : False : False : Binary
         31 :     0 :  -0.0 :     1 : False : False : Binary
         32 :     0 :  -0.0 :     1 : False : False : Binary
         33 :     0 :  -0.0 :     1 : False : False : Binary
         34 :     0 :  -0.0 :     1 : False : False : Binary
         35 :     0 :  -0.0 :     1 : False : False : Binary
         36 :     0 :  -0.0 :     1 : False : False : Binary
         37 :     0 :  -0.0 :     1 : False : False : Binary
         38 :     0 :  -0.0 :     1 : False : False : Binary
         39 :     0 :  -0.0 :     1 : False : False : Binary
         40 :     0 :  -0.0 :     1 : False : False : Binary
         41 :     0 :  -0.0 :     1 : False : False : Binary
         42 :     0 :   0.0 :     1 : False : False : Binary
         43 :     0 :  -0.0 :     1 : False : False : Binary
         44 :     0 :  -0.0 :     1 : False : False : Binary
         45 :     0 :  -0.0 :     1 : False : False : Binary
         46 :     0 :   0.0 :     1 : False : False : Binary
         47 :     0 :   1.0 :     1 : False : False : Binary
         48 :     0 :  -0.0 :     1 : False : False : Binary
         49 :     0 :   1.0 :     1 : False : False : Binary
         50 :     0 :   0.0 :     1 : False : False : Binary
         51 :     0 :  -0.0 :     1 : False : False : Binary
         52 :     0 :  -0.0 :     1 : False : False : Binary
         53 :     0 :  -0.0 :     1 : False : False : Binary
         54 :     0 :  -0.0 :     1 : False : False : Binary
         55 :     0 :  -0.0 :     1 : False : False : Binary
         56 :     0 :  -0.0 :     1 : False : False : Binary
         57 :     0 :   1.0 :     1 : False : False : Binary
         58 :     0 :  -0.0 :     1 : False : False : Binary
         59 :     0 :  -0.0 :     1 : False : False : Binary
         60 :     0 :  -0.0 :     1 : False : False : Binary
         61 :     0 :  -0.0 :     1 : False : False : Binary
         62 :     0 :  -0.0 :     1 : False : False : Binary
         63 :     0 :   0.0 :     1 : False : False : Binary
         64 :     0 :   1.0 :     1 : False : False : Binary
         65 :     0 :   1.0 :     1 : False : False : Binary
         66 :     0 :  -0.0 :     1 : False : False : Binary
         67 :     0 :  -0.0 :     1 : False : False : Binary
         68 :     0 :   1.0 :     1 : False : False : Binary
         69 :     0 :  -0.0 :     1 : False : False : Binary
    w : Size=70, Index=ativos
        Key : Lower : Value              : Upper : Fixed : Stale : Domain
          0 :     0 : 2.1969343990444603 :  None : False : False : NonNegativeReals
          1 :     0 :                0.0 :  None : False : False : NonNegativeReals
          2 :     0 :                0.0 :  None : False : False : NonNegativeReals
          3 :     0 :                0.0 :  None : False : False : NonNegativeReals
          4 :     0 :                0.0 :  None : False : False : NonNegativeReals
          5 :     0 :                0.0 :  None : False : False : NonNegativeReals
          6 :     0 :                0.0 :  None : False : False : NonNegativeReals
          7 :     0 :                0.0 :  None : False : False : NonNegativeReals
          8 :     0 : 2.1969343990444603 :  None : False : False : NonNegativeReals
          9 :     0 :                0.0 :  None : False : False : NonNegativeReals
         10 :     0 :                0.0 :  None : False : False : NonNegativeReals
         11 :     0 :                0.0 :  None : False : False : NonNegativeReals
         12 :     0 :                0.0 :  None : False : False : NonNegativeReals
         13 :     0 :                0.0 :  None : False : False : NonNegativeReals
         14 :     0 :                0.0 :  None : False : False : NonNegativeReals
         15 :     0 :                0.0 :  None : False : False : NonNegativeReals
         16 :     0 : 2.1969343990444603 :  None : False : False : NonNegativeReals
         17 :     0 :                0.0 :  None : False : False : NonNegativeReals
         18 :     0 :                0.0 :  None : False : False : NonNegativeReals
         19 :     0 : 2.1969343990444603 :  None : False : False : NonNegativeReals
         20 :     0 :                0.0 :  None : False : False : NonNegativeReals
         21 :     0 :                0.0 :  None : False : False : NonNegativeReals
         22 :     0 :                0.0 :  None : False : False : NonNegativeReals
         23 :     0 :                0.0 :  None : False : False : NonNegativeReals
         24 :     0 :                0.0 :  None : False : False : NonNegativeReals
         25 :     0 :                0.0 :  None : False : False : NonNegativeReals
         26 :     0 :                0.0 :  None : False : False : NonNegativeReals
         27 :     0 :                0.0 :  None : False : False : NonNegativeReals
         28 :     0 :                0.0 :  None : False : False : NonNegativeReals
         29 :     0 :                0.0 :  None : False : False : NonNegativeReals
         30 :     0 :                0.0 :  None : False : False : NonNegativeReals
         31 :     0 :                0.0 :  None : False : False : NonNegativeReals

In [37]:
carteiras_anuais[2016]

{'pesos': {'ABEV3': 0.0,
  'ANIM3': 0.0,
  'AXIA3': 0.0,
  'AZZA3': 0.0,
  'B3SA3': 0.0,
  'BBSE3': 0.0,
  'BEEF3': 0.0,
  'BRAP4': 0.0,
  'BRKM5': 0.12453372943246492,
  'CMIG4': 0.0,
  'COGN3': 0.0,
  'CPFE3': 0.0,
  'CPLE3': 0.0,
  'CSAN3': 0.09608144534693083,
  'CSMG3': 0.0,
  'CSNA3': 0.0,
  'CVCB3': 0.0,
  'CYRE3': 0.0,
  'DIRR3': 0.04292844392062733,
  'ECOR3': 0.0,
  'EMBJ3': 0.0,
  'ENGI11': 0.05740466746120151,
  'EQTL3': 0.0,
  'EZTC3': 0.0,
  'FLRY3': 0.14873285366897226,
  'GGBR4': 0.0,
  'GOAU4': 0.0,
  'HYPE3': 0.19999999999999998,
  'ISAE4': 0.0,
  'ITSA4': 0.0,
  'JHSF3': 0.0,
  'KLBN11': 0.0,
  'LREN3': 0.0,
  'MGLU3': 0.03349677523165688,
  'MOTV3': 0.0,
  'MRVE3': 0.20000000000000004,
  'MULT3': 0.0,
  'PETR3': 0.0,
  'PETR4': 0.0,
  'POMO4': 0.02,
  'PRIO3': 0.0,
  'PSSA3': 0.0,
  'RADL3': 0.0,
  'RAPT4': 0.0,
  'RENT3': 0.0,
  'SBSP3': 0.07682208493814624,
  'SLCE3': 0.0,
  'SUZB3': 0.0,
  'TAEE11': 0.0,
  'TOTS3': 0.0,
  'UGPA3': 0.0,
  'USIM5': 0.0,
  'VALE3': 0.0,
  'VIVT3': 0.0,
  'WEGE3': 0.0},
 'z[a]': {0: 0.0,
  1: 0.0,
  2: 0.0,
  3: 0.0,
  4: 0.0,
  5: 0.0,
  6: 0.0,
  7: 0.0,
  8: 0.24225082684730564,
  9: 0.0,
  10: 0.0,
  11: 0.0,
  12: 0.0,
  13: 0.18690365803748576,
  14: 0.0,
  15: 0.0,
  16: 0.0,
  17: 0.0,
  18: 0.0835071035167209,
  19: 0.0,
  20: 0.0,
  21: 0.11166716214752194,
  22: 0.0,
  23: 0.0,
  24: 0.289324482169366,
  25: 0.0,
  26: 0.0,
  27: 0.38905255299316976,
  28: 0.0,
  29: 0.0,
  30: 0.0,
  31: 0.0,
  32: 0.0,
  33: 0.06516002960457243,
  34: 0.0,
  35: 0.3890525529931699,
  36: 0.0,
  37: 0.0,
  38: 0.0,
  39: 0.03890525529931698,
  40: 0.0,
  41: 0.0,
  42: 0.0,
  43: 0.0,
  44: 0.0,
  45: 0.14943914135721964,
  46: 0.0,
  47: 0.0,
  48: 0.0,
  49: 0.0,
  50: 0.0,
  51: 0.0,
  52: 0.0,
  53: 0.0,
  54: 0.0},
 'score': {0: np.float64(0.1976979339286147),
  1: np.float64(0.189913643140866),
  2: np.float64(0.1813146447792266),
  3: np.float64(0.1901002281159537),
  4: np.float64(0.1988724608978285),
  5: np.float64(0.0),
  6: np.float64(0.1899497396035916),
  7: np.float64(0.1051539338154787),
  8: np.float64(0.189763171831022),
  9: np.float64(0.3458876249933282),
  10: np.float64(0.1942068461234882),
  11: np.float64(0.1893955812323105),
  12: np.float64(0.1901711846581996),
  13: np.float64(0.1964150314365585),
  14: np.float64(0.1922135117522917),
  15: np.float64(0.1897922009234661),
  16: np.float64(0.2008273281287771),
  17: np.float64(0.1894864522976542),
  18: np.float64(0.1884769638422372),
  19: np.float64(0.2217258931727072),
  20: np.float64(0.1873986934726826),
  21: np.float64(0.1931188563368647),
  22: np.float64(0.1919256043944087),
  23: np.float64(0.1932936379074644),
  24: np.float64(0.190011096825259),
  25: np.float64(0.1849389849161056),
  26: np.float64(0.1846198837285419),
  27: np.float64(0.1884291507212859),
  28: np.float64(0.2009099590686154),
  29: np.float64(0.2004425184177874),
  30: np.float64(0.1930348470151393),
  31: np.float64(0.1874921826776662),
  32: np.float64(0.1905259300631744),
  33: np.float64(0.191632212170357),
  34: np.float64(0.1789940835031026),
  35: np.float64(0.188603434026077),
  36: np.float64(0.2098263490235604),
  37: np.float64(0.1861451447773928),
  38: np.float64(0.1861407906173353),
  39: np.float64(0.1880172918786947),
  40: np.float64(0.1846241490296531),
  41: np.float64(0.1862290389520409),
  42: np.float64(0.1911277760730226),
  43: np.float64(0.1868421085348662),
  44: np.float64(0.1901477679143581),
  45: np.float64(1.0),
  46: np.float64(0.1890590102680034),
  47: np.float64(0.1888613234817643),
  48: np.float64(0.201137030225279),
  49: np.float64(0.1911354499695549),
  50: np.float64(0.1904242273294561),
  51: np.float64(0.1810716531844566),
  52: np.float64(0.1840442311894395),
  53: np.float64(0.1899761273622693),
  54: np.float64(0.1889067466919107)}}

In [ ]:
print(max(carteiras_anuais[2018]['z[a]'].values()))
print(min(carteiras_anuais[2018]['z[a]'].values()))

0.4723832562736914
0.0

In [39]:
linhas = []
for an in anos:
    an = int(an.split('-')[0])+1
    print(an)
    for k, v in carteiras_anuais[an]['pesos'].items():
        # print(v)
        if v >= vb_peso_minimo:
            linhas.append({'ano': an, 'ativo': k, 'peso': round(v, 4)})

df_portfolios = pd.DataFrame(linhas)

# # visões instantâneas:
# df_portfolios[df_portfolios['ano'] == 2016].sort_values('peso', ascending=False)  # uma carteira
# df_portfolios.pivot(index='ativo', columns='ano', values='peso')                  # matriz ativo × ano
# df_portfolios.groupby('ativo')['ano'].count().sort_values(ascending=False)

2026
2025
2024
2023
2022
2021
2020
2019
2018
2017
2016

In [43]:
df_portfolios[df_portfolios['ano']==2024]

     ano  ativo    peso
19  2024  CSMG3  0.0466
20  2024  CXSE3  0.2000
21  2024  EMBJ3  0.1997
22  2024  PETR4  0.0661
23  2024  POMO4  0.0211
24  2024  PSSA3  0.0200
25  2024  SBSP3  0.0342
26  2024  SUZB3  0.1249
27  2024  UGPA3  0.1463
28  2024  USIM5  0.1410

In [ ]:
df_portfolios.to_csv('carteiras_mf_linear_sharpe.csv')